// Generated by @canonical/summon-application:application/react v0.1.0

import { HeadProvider } from "@canonical/react-head";
import type { ServerEntrypointProps } from "@canonical/react-ssr/renderer";
import { Outlet, RouterProvider } from "@canonical/router-react";
import { RelayEnvironmentProvider } from "react-relay";
import type { RecordMap } from "relay-runtime/store/RelayStoreTypes.js";
import { createStaticRouter } from "#lib/router";
import { createEnvironment } from "#relay";
import { appRoutes, middleware, notFoundRoute } from "../routes.js";
import "../styles/app.css";

interface InitialData extends Record<string, unknown> {
  readonly url?: string;
  /** Colour-scheme preference resolved from the request cookie, if any. */
  readonly theme?: "light" | "dark";
  /**
   * Relay hydration payload from the server's prepare step: the serialised
   * record map of the route's executed query. `__INITIAL_DATA__` is an
   * app-level namespaced map owned by `JSXRenderer` (P-2 D8); `relay` is its
   * first data namespace (`router` stays reserved).
   */
  readonly relay?: {
    readonly records?: RecordMap;
  };
}

export default function EntryServer(props: ServerEntrypointProps<InitialData>) {
  const initialData = props.initialData ?? {};
  const url = initialData.url ?? "/";
  const router = createStaticRouter(appRoutes, url, {
    middleware: [...middleware],
    notFound: notFoundRoute,
  });

  // A fresh Relay environment per server render, so no store state leaks
  // between requests — seeded from the prepare step's serialised records
  // (the same bytes the client hydrates from, so data-driven hydration
  // mismatch is excluded by construction). With a warm store the page's
  // queries render without fetching.
  //
  // `fetchFn` is the COLD-STORE guard, and the PRD-3 process split made it
  // MORE necessary, not less. A server render that reaches the network is
  // still always a bug: the prepare step already ran (all four SSR bricks
  // run it now), so a miss means the store and the render disagree about
  // the operation or its variables — refetching would paper over that.
  // What changed is the failure mode without the guard. The endpoint used
  // to be the same-origin `/graphql`, which the default HTTP path could
  // not even resolve server-side (ERR_INVALID_URL). It is an ABSOLUTE URL
  // now, so a cold render would quietly make a REAL request to the graph
  // server, per component, mid-render — a slow, invisible fallback instead
  // of a loud one.
  //
  // The miss is reported as a REJECTED PROMISE, not a synchronous throw.
  // A throw here escapes during the render pass itself, which the
  // express brick turns into a hard 500 (the bun brick, which has
  // already flushed the shell, degrades more gracefully — the two must
  // not disagree). A rejection is what Relay's network contract expects
  // for a failed operation, so the miss lands in the suspended
  // boundary's error path: shell, frame, and authored prose still
  // render, and the canvas shows its honest "the graph query failed"
  // state on both bricks.
  const relayEnvironment = createEnvironment({
    records: initialData.relay?.records,
    fetchFn: (params) =>
      Promise.reject(
        new Error(
          `no server-side GraphQL network: operation ${params.name} was not ` +
            "served from the prepared store (the prepare step either did " +
            "not run for this route, or ran with different variables)",
        ),
      ),
  });

  // Paint the cookie-resolved theme on <html> for a flash-free first render —
  // the same element `usePreferredTheme` toggles on the client, and one React
  // does not hydrate (only `#root` is), so there is no mismatch to reconcile.
  return (
    <html lang={props.lang} className={initialData.theme}>
      <head>
        {props.otherHeadElements}
        {props.scriptElements}
        {props.linkElements}
      </head>
      <body>
        <div id="root">
          <HeadProvider>
            <RelayEnvironmentProvider environment={relayEnvironment}>
              <RouterProvider router={router}>
                <Outlet fallback={<p>Loading…</p>} />
              </RouterProvider>
            </RelayEnvironmentProvider>
          </HeadProvider>
        </div>
      </body>
    </html>
  );
}

export type { InitialData };
