import type { IconMetadata, IconName } from "./types.js";

/**
 * Searchable metadata for every icon in `ICON_NAMES`, in the same order.
 *
 * Tags are the words someone might search for; aliases are the names an icon
 * was previously published under. Both feed icon search. The first pass of tags
 * was seeded from an existing tag set and corrected against the rendered
 * glyphs; the file is maintained by hand from here on, under the rules in
 * `docs/ICONS.md` and the invariants in `icons.test.ts`.
 */
export const ICON_METADATA: Readonly<Record<IconName, IconMetadata>> = {
  "add-canvas": {
    tags: [
      "add",
      "canvas",
      "new",
      "create",
      "page",
      "document",
      "artboard",
      "board",
    ],
    categories: ["action", "product"],
    description: "Create a new canvas.",
  },
  "add-logical-volume": {
    tags: [
      "volume",
      "logical volume",
      "add",
      "plus",
      "storage",
      "disk",
      "block",
      "data",
      "create",
      "new",
      "lvm",
    ],
    categories: ["action", "product"],
    description: "Create a logical volume on a storage device.",
  },
  "add-partition": {
    tags: [
      "add",
      "partition",
      "plus",
      "block",
      "segment",
      "create",
      "new",
      "storage",
      "disk",
      "layout",
      "section",
      "divide",
      "split",
    ],
    categories: ["action", "product"],
    description: "Create a partition on a disk.",
  },
  anchor: {
    tags: [
      "boat",
      "ship",
      "sea",
      "ocean",
      "marine",
      "nautical",
      "port",
      "harbor",
      "harbour",
      "secure",
      "stability",
      "maritime",
    ],
    categories: ["object"],
  },
  applications: {
    tags: [
      "network",
      "connections",
      "distributed",
      "services",
      "nodes",
      "platform",
      "architecture",
      "structure",
      "juju",
      "workload",
      "charm",
    ],
    categories: ["product"],
    description: "Applications deployed in a model.",
  },
  archive: {
    tags: [
      "box",
      "storage",
      "save",
      "organize",
      "organise",
      "document",
      "file",
      "container",
      "inbox",
      "outbox",
    ],
    categories: ["action", "object"],
  },
  "arrow-bottom-left": {
    tags: [
      "arrow",
      "bottom",
      "left",
      "diagonal",
      "down-left",
      "direction",
      "indicator",
      "southwest",
      "bottom left",
      "navigation",
      "down",
    ],
    categories: ["navigation"],
  },
  "arrow-bottom-right": {
    tags: [
      "arrow",
      "bottom right",
      "diagonal",
      "direction",
      "pointer",
      "indicate",
      "navigation",
      "southeast",
      "bottom",
      "right",
      "down",
      "indicator",
    ],
    categories: ["navigation"],
  },
  "arrow-down": {
    tags: [
      "arrow",
      "down",
      "direction",
      "collapse",
      "navigate",
      "south",
      "navigation",
      "indicator",
    ],
    categories: ["navigation"],
  },
  "arrow-left": {
    tags: [
      "arrow",
      "left",
      "previous",
      "back",
      "direction",
      "move",
      "navigate",
      "navigation",
      "indicator",
      "west",
    ],
    categories: ["navigation"],
  },
  "arrow-right": {
    tags: [
      "arrow",
      "right",
      "forward",
      "next",
      "direction",
      "pointer",
      "navigation",
      "indicator",
      "go",
      "move",
      "east",
    ],
    categories: ["navigation"],
  },
  "arrow-top-left": {
    tags: [
      "arrow",
      "diagonal",
      "direction",
      "up-left",
      "northwest",
      "top left",
      "navigation",
      "indicator",
      "up",
      "left",
    ],
    categories: ["navigation"],
  },
  "arrow-top-right": {
    tags: [
      "arrow",
      "diagonal",
      "direction",
      "point",
      "northeast",
      "up",
      "right",
      "navigation",
      "up-right",
      "top right",
      "indicator",
    ],
    categories: ["navigation"],
  },
  "arrow-up": {
    tags: [
      "arrow",
      "up",
      "direction",
      "indicator",
      "move up",
      "scroll up",
      "sort up",
      "increase",
      "top",
      "north",
      "navigation",
    ],
    categories: ["navigation"],
  },
  "back-to-top": {
    tags: ["arrow", "up", "top", "back", "scroll", "elevate", "return"],
    categories: ["navigation", "action"],
  },
  bug: {
    tags: [
      "insect",
      "error",
      "problem",
      "debugging",
      "software",
      "creature",
      "animal",
      "defect",
      "issue",
    ],
    categories: ["object"],
    aliases: ["submit-bug"],
  },
  blueprint: {
    tags: [
      "plan",
      "drawing",
      "scheme",
      "architecture",
      "design",
      "engineering",
      "construction",
      "document",
    ],
    categories: ["product"],
    description: "A blueprint describing how something is built.",
  },
  book: {
    tags: [
      "reading",
      "literature",
      "education",
      "library",
      "knowledge",
      "story",
      "novel",
      "documentation",
      "docs",
      "guide",
    ],
    categories: ["object"],
  },
  bundle: {
    tags: [
      "group",
      "package",
      "collection",
      "modules",
      "components",
      "items",
      "multiple",
      "services",
      "products",
      "inventory",
      "assembly",
      "juju",
      "charm",
    ],
    categories: ["product"],
    description: "A bundle of applications deployed together.",
  },
  canvas: {
    tags: [
      "drawing",
      "graphic",
      "frame",
      "layers",
      "creative",
      "board",
      "artboard",
      "workspace",
    ],
    categories: ["product"],
    description: "A canvas holding a visual layout.",
  },
  certificate: {
    tags: [
      "document",
      "diploma",
      "award",
      "medal",
      "seal",
      "validation",
      "achievement",
      "quality",
      "official",
      "authentic",
      "license",
      "licence",
      "permit",
      "badge",
    ],
    categories: ["object"],
  },
  certification: {
    tags: [
      "award",
      "badge",
      "guarantee",
      "approval",
      "quality",
      "verified",
      "official",
      "license",
      "licence",
      "achievement",
      "rosette",
      "seal",
      "approved",
    ],
    categories: ["object"],
    description: "An award rosette marking something as certified.",
  },
  "change-version": {
    tags: [
      "change",
      "version",
      "update",
      "refresh",
      "history",
      "revert",
      "rollback",
      "cycle",
      "arrow",
      "rotate",
      "switch version",
      "upgrade",
    ],
    categories: ["action"],
  },
  chart: {
    tags: [
      "bar chart",
      "graph",
      "data",
      "analytics",
      "statistics",
      "report",
      "bars",
      "metrics",
      "visualisation",
      "visualization",
    ],
    categories: ["object"],
    description: "A bar chart summarising data.",
  },
  checkmark: {
    tags: [
      "check",
      "tick",
      "complete",
      "done",
      "success",
      "approve",
      "confirm",
      "mark",
      "validation",
      "verified",
      "correct",
    ],
    categories: ["status"],
  },
  "chevron-down": {
    tags: [
      "chevron",
      "down",
      "arrow",
      "expand",
      "collapse",
      "direction",
      "caret",
      "indicator",
      "fold",
    ],
    categories: ["navigation"],
  },
  "chevron-left": {
    tags: [
      "chevron",
      "left",
      "arrow",
      "back",
      "previous",
      "direction",
      "navigation",
      "pointer",
    ],
    categories: ["navigation"],
  },
  "chevron-right": {
    tags: [
      "chevron",
      "right",
      "arrow",
      "next",
      "navigate",
      "forward",
      "pointer",
      "direction",
      "indicator",
      "caret",
    ],
    categories: ["navigation"],
  },
  "chevron-up": {
    tags: ["chevron", "up", "arrow", "direction", "indicator", "caret"],
    categories: ["navigation"],
  },
  clipboard: {
    tags: ["board", "paste", "notes", "document", "form", "record", "task"],
    categories: ["object"],
    description: "An empty clipboard.",
  },
  "clipboard-chart": {
    tags: [
      "clipboard",
      "chart",
      "bar chart",
      "report",
      "graph",
      "data",
      "analytics",
      "summary",
      "metrics",
    ],
    categories: ["object"],
    description: "A clipboard showing a bar chart.",
  },
  "clipboard-list": {
    tags: [
      "clipboard",
      "list",
      "checklist",
      "tasks",
      "items",
      "notes",
      "todo",
      "inventory",
    ],
    categories: ["object"],
    description: "A clipboard showing a list of items.",
  },
  close: {
    tags: ["cancel", "exit", "remove", "cross", "x mark", "dismiss"],
    categories: ["action"],
  },
  "cluster-host": {
    tags: [
      "cluster",
      "host",
      "network",
      "connection",
      "data",
      "server",
      "computing",
      "infrastructure",
      "grid",
      "hexagonal",
      "system",
      "group",
      "distributed",
      "clustered",
    ],
    categories: ["product"],
    description: "A host that belongs to a cluster.",
  },
  code: {
    tags: [
      "coding",
      "programming",
      "developer",
      "develop",
      "script",
      "terminal",
      "shell",
      "command",
      "prompt",
      "snippet",
      "dollar",
      "cli",
    ],
    categories: ["object"],
  },
  "collapse-side-nav": {
    tags: [
      "collapse",
      "side nav",
      "sidebar",
      "navigation",
      "panel",
      "drawer",
      "hide",
      "close panel",
      "menu",
      "left",
    ],
    categories: ["navigation", "action"],
    description: "Collapse the side navigation panel.",
  },
  comments: {
    tags: [
      "speech",
      "bubble",
      "chat",
      "message",
      "discussion",
      "talk",
      "communication",
      "feedback",
    ],
    categories: ["object"],
  },
  connected: {
    tags: [
      "link",
      "connection",
      "network",
      "join",
      "relationship",
      "connect",
      "online",
      "attached",
      "plug",
      "cable",
      "connector",
    ],
    categories: ["status"],
  },
  containers: {
    tags: [
      "container",
      "box",
      "storage",
      "stack",
      "package",
      "cargo",
      "lxd",
      "lxc",
      "instance",
    ],
    categories: ["product"],
    description: "Containers running a workload.",
  },
  controllers: {
    tags: [
      "controller",
      "juju",
      "dial",
      "gauge",
      "manage",
      "management",
      "control plane",
      "infrastructure",
      "meter",
    ],
    categories: ["product"],
    description: "Controllers that manage a cloud environment.",
  },
  copy: {
    tags: ["document", "file", "duplicate", "clone", "pages", "clipboard"],
    categories: ["action"],
  },
  cursor: {
    tags: ["mouse", "arrow", "pointer", "click", "select", "interface", "ui"],
    categories: ["object"],
  },
  cut: {
    tags: ["scissors", "snip", "trim", "clipboard", "move", "remove"],
    categories: ["action"],
  },
  "dark-theme": {
    tags: [
      "dark",
      "theme",
      "moon",
      "night",
      "colour scheme",
      "color scheme",
      "appearance",
      "mode",
      "crescent",
    ],
    categories: ["theme"],
    description: "Switch to the dark colour scheme.",
  },
  debug: {
    tags: [
      "bug",
      "fix",
      "error",
      "tool",
      "troubleshoot",
      "development",
      "inspect",
      "diagnose",
      "no bug",
      "slash",
      "troubleshooting",
    ],
    categories: ["action"],
    aliases: ["inspector-debug"],
  },
  delete: {
    tags: ["trash", "bin", "remove", "garbage", "erase", "dispose", "discard"],
    categories: ["action"],
  },
  desktop: {
    tags: [
      "computer",
      "monitor",
      "screen",
      "display",
      "work",
      "office",
      "device",
      "technology",
    ],
    categories: ["object"],
  },
  disconnected: {
    tags: [
      "broken",
      "connection",
      "network",
      "signal",
      "error",
      "offline",
      "wire",
      "interrupted",
    ],
    categories: ["status"],
    aliases: ["disconnect"],
  },
  download: {
    tags: ["arrow", "save", "file", "install", "retrieve", "get", "data"],
    categories: ["action"],
    aliases: ["begin-downloading"],
  },
  drag: {
    tags: ["reorder", "move", "handle", "grip", "sort", "draggable"],
    categories: ["action"],
    description: "Grab this to move an item.",
  },
  edit: {
    tags: [
      "pencil",
      "write",
      "modify",
      "change",
      "update",
      "create",
      "document",
      "tool",
      "compose",
      "rename",
    ],
    categories: ["action"],
  },
  email: {
    tags: [
      "mail",
      "message",
      "envelope",
      "send",
      "receive",
      "communication",
      "inbox",
    ],
    categories: ["object"],
  },
  error: {
    tags: [
      "wrong",
      "close",
      "cross",
      "fail",
      "incorrect",
      "warning",
      "caution",
      "alert",
    ],
    categories: ["status"],
  },
  "error-fill": {
    tags: [
      "error",
      "close",
      "wrong",
      "deny",
      "stop",
      "cancel",
      "alert",
      "notification",
      "warning",
      "fail",
      "problem",
      "issue",
      "cross",
      "circle",
      "filled",
    ],
    categories: ["status"],
  },
  "expand-side-nav": {
    tags: [
      "expand",
      "side nav",
      "sidebar",
      "navigation",
      "panel",
      "drawer",
      "show",
      "open panel",
      "menu",
      "right",
    ],
    categories: ["navigation", "action"],
    aliases: ["toggle-side-nav"],
    description: "Expand the side navigation panel.",
  },
  export: {
    tags: [
      "share",
      "upload",
      "save",
      "arrow",
      "box",
      "send",
      "move",
      "transfer",
    ],
    categories: ["action"],
  },
  exposed: {
    tags: [
      "globe",
      "world",
      "earth",
      "sphere",
      "global",
      "juju",
      "public",
      "internet",
      "external",
    ],
    categories: ["status", "product"],
    description:
      "The application is exposed to traffic from outside the model.",
  },
  "external-link": {
    tags: [
      "link",
      "new tab",
      "new window",
      "open",
      "arrow",
      "outbound",
      "redirect",
    ],
    categories: ["navigation"],
  },
  facebook: {
    tags: [
      "social media",
      "network",
      "app",
      "share",
      "f",
      "communication",
      "connection",
      "logo",
      "brand",
    ],
    categories: ["social-brand"],
  },
  file: {
    tags: [
      "document",
      "page",
      "paper",
      "content",
      "text",
      "form",
      "note",
      "report",
      "data",
    ],
    categories: ["object"],
  },
  "file-blank": {
    tags: [
      "file",
      "document",
      "blank",
      "empty",
      "new",
      "paper",
      "page",
      "sheet",
      "note",
    ],
    categories: ["object"],
  },
  filter: {
    tags: [
      "sort",
      "options",
      "funnel",
      "organize",
      "organise",
      "adjust",
      "preferences",
    ],
    categories: ["action"],
  },
  folder: {
    tags: ["directory", "storage", "organize", "organise", "browse"],
    categories: ["object"],
  },
  fork: {
    tags: [
      "branch",
      "repository",
      "git",
      "split",
      "diverge",
      "version control",
      "copy",
      "clone",
    ],
    categories: ["action"],
    description: "Fork a repository or branch a line of work.",
  },
  fullscreen: {
    tags: [
      "expand",
      "maximize",
      "screen",
      "display",
      "view",
      "corners",
      "brackets",
    ],
    categories: ["action"],
    description: "Fill the screen with the current view.",
  },
  gift: {
    tags: [
      "present",
      "birthday",
      "christmas",
      "celebration",
      "surprise",
      "package",
      "ribbon",
      "holiday",
    ],
    categories: ["object"],
  },
  github: {
    tags: [
      "code",
      "development",
      "programmer",
      "developer",
      "social coding",
      "version control",
      "git",
      "platform",
      "repository",
      "programming",
      "software",
      "logo",
      "brand",
    ],
    categories: ["social-brand"],
  },
  help: {
    tags: [
      "question",
      "info",
      "information",
      "support",
      "assistance",
      "query",
      "faq",
      "ask",
      "problem",
      "question mark",
    ],
    categories: ["status"],
  },
  hide: {
    tags: [
      "invisible",
      "eye",
      "slash",
      "private",
      "off",
      "view",
      "toggle",
      "mask",
      "concealed",
      "unseen",
      "visibility",
    ],
    categories: ["action"],
  },
  "highlight-off": {
    tags: [
      "lightbulb",
      "bulb",
      "light",
      "off",
      "idea",
      "disabled",
      "inactive",
      "dim",
      "unlit",
    ],
    categories: ["action"],
    description: "An unlit lightbulb: highlighting is off.",
  },
  "highlight-on": {
    tags: [
      "lightbulb",
      "bulb",
      "light",
      "on",
      "idea",
      "active",
      "enabled",
      "bright",
      "lit",
    ],
    categories: ["action"],
    description: "A lit lightbulb: highlighting is on.",
  },
  home: {
    tags: [
      "house",
      "building",
      "residence",
      "homepage",
      "start",
      "index",
      "main",
      "dashboard",
    ],
    categories: ["navigation"],
  },
  image: {
    tags: [
      "os",
      "operating system",
      "disk image",
      "system image",
      "distro",
      "distribution",
      "install media",
      "base image",
    ],
    categories: ["product"],
    description: "An operating system image.",
  },
  "image-registries": {
    tags: ["registry", "image", "catalogue", "catalog", "source", "store"],
    categories: ["product"],
    description: "Registries that images are pulled from.",
  },
  import: {
    tags: [
      "arrow",
      "down",
      "box",
      "entry",
      "load",
      "bring in",
      "receive",
      "ingest",
    ],
    categories: ["action"],
  },
  "in-progress": {
    tags: [
      "progress",
      "loading",
      "pending",
      "processing",
      "status",
      "dot",
      "partial",
      "running",
    ],
    categories: ["status"],
    aliases: ["status-in-progress"],
  },
  information: {
    tags: ["help", "about", "details", "query", "guide", "support"],
    categories: ["status"],
    aliases: ["info"],
  },
  instagram: {
    tags: [
      "social media",
      "photo",
      "sharing",
      "app",
      "network",
      "camera",
      "brand",
      "logo",
      "platform",
      "photography",
    ],
    categories: ["social-brand"],
  },
  iso: {
    tags: [
      "disc",
      "disk image",
      "optical",
      "cd",
      "dvd",
      "install media",
      "image",
      "burn",
    ],
    categories: ["product"],
    description: "An ISO disc image.",
  },
  "light-theme": {
    tags: [
      "light",
      "theme",
      "sun",
      "day",
      "bright",
      "colour scheme",
      "color scheme",
      "appearance",
      "mode",
    ],
    categories: ["theme"],
    description: "Switch to the light colour scheme.",
  },
  link: {
    tags: [
      "chain",
      "url",
      "hyperlink",
      "connection",
      "web",
      "attach",
      "share",
      "website",
    ],
    categories: ["action"],
    aliases: ["get-link"],
  },
  linkedin: {
    tags: [
      "social media",
      "network",
      "professional",
      "job",
      "career",
      "business",
      "connection",
      "logo",
      "brand",
    ],
    categories: ["social-brand"],
  },
  location: {
    tags: [
      "map",
      "marker",
      "pointer",
      "navigation",
      "address",
      "position",
      "geotag",
    ],
    categories: ["navigation", "object"],
  },
  locked: {
    tags: [
      "lock",
      "padlock",
      "secure",
      "security",
      "private",
      "privacy",
      "closed",
      "restricted",
    ],
    categories: ["status"],
    aliases: ["lock-locked"],
  },
  "log-out": {
    tags: [
      "exit",
      "logout",
      "sign out",
      "leave",
      "arrow",
      "quit",
      "account",
      "session",
    ],
    categories: ["action"],
  },
  machines: {
    tags: [
      "machine",
      "server",
      "host",
      "node",
      "hardware",
      "compute",
      "bare metal",
      "instance",
      "rack",
    ],
    categories: ["product"],
    description: "Machines that host workloads.",
  },
  map: {
    tags: [
      "navigation",
      "location",
      "geography",
      "atlas",
      "travel",
      "guide",
      "direction",
      "discover",
      "journey",
    ],
    categories: ["navigation"],
  },
  maximize: {
    tags: [
      "expand",
      "enlarge",
      "grow",
      "fullscreen",
      "arrows",
      "outward",
      "zoom in",
      "bigger",
    ],
    categories: ["action"],
    description: "Expand the view to fill the available space.",
  },
  menu: {
    tags: [
      "hamburger",
      "navigation",
      "lines",
      "list",
      "options",
      "burger",
      "nav",
    ],
    categories: ["navigation"],
  },
  "menu-contextual": {
    tags: [
      "menu",
      "contextual",
      "options",
      "more",
      "overflow",
      "dots",
      "vertical ellipsis",
      "kebab menu",
      "three dots",
    ],
    categories: ["navigation"],
    aliases: ["contextual-menu"],
  },
  minimize: {
    tags: [
      "shrink",
      "collapse",
      "reduce",
      "arrows",
      "inward",
      "zoom out",
      "smaller",
      "restore",
    ],
    categories: ["action"],
    description: "Shrink the view back to its smaller size.",
  },
  minus: {
    tags: [
      "subtract",
      "remove",
      "decrease",
      "hyphen",
      "dash",
      "horizontal line",
      "math",
      "arithmetic",
      "reduction",
    ],
    categories: ["action"],
  },
  models: {
    tags: [
      "model",
      "juju",
      "deployment",
      "environment",
      "workspace",
      "topology",
      "nodes",
      "graph",
    ],
    categories: ["product"],
    description: "Models grouping deployed applications.",
  },
  mount: {
    tags: [
      "hard drive",
      "storage",
      "disk",
      "add",
      "connect",
      "filesystem",
      "external drive",
      "hdd",
      "ssd",
      "server",
      "hardware",
    ],
    categories: ["action", "product"],
    description: "Attach a storage device to the filesystem.",
  },
  notifications: {
    tags: ["bell", "alert", "reminder", "alarm", "message", "sound", "signal"],
    categories: ["object"],
  },
  "notifications-off": {
    tags: [
      "notifications",
      "off",
      "disable",
      "mute",
      "quiet",
      "alert",
      "bell",
      "silent",
    ],
    categories: ["object"],
    aliases: ["turn-off-notification"],
  },
  "open-terminal": {
    tags: [
      "terminal",
      "console",
      "command line",
      "cli",
      "shell",
      "developer",
      "code",
      "programmer",
      "window",
      "execute",
      "prompt",
      "script",
      "open",
    ],
    categories: ["action"],
  },
  paste: {
    tags: ["clipboard", "insert", "place", "duplicate", "document", "file"],
    categories: ["action"],
  },
  pause: {
    tags: ["media", "player", "control", "music", "video", "audio", "sound"],
    categories: ["action"],
  },
  pin: {
    tags: [
      "pushpin",
      "thumbtack",
      "mark",
      "point",
      "attach",
      "fasten",
      "stationery",
      "office",
      "board",
    ],
    categories: ["action"],
  },
  plans: {
    tags: [
      "plan",
      "subscription",
      "tier",
      "badge",
      "rosette",
      "approved",
      "offer",
      "package",
      "award",
    ],
    categories: ["product"],
    description: "Plans available for a subscription or workload.",
  },
  play: {
    tags: [
      "media",
      "video",
      "audio",
      "start",
      "circle",
      "button",
      "control",
      "resume",
      "run",
      "triangle",
    ],
    categories: ["action"],
  },
  "play-fill": {
    tags: [
      "play",
      "button",
      "media",
      "start",
      "circle",
      "multimedia",
      "video",
      "audio",
      "player",
      "triangle",
      "filled",
    ],
    categories: ["action"],
  },
  "play-pending": {
    tags: [
      "play",
      "pending",
      "loading",
      "buffer",
      "waiting",
      "media",
      "video",
      "audio",
      "stream",
      "progress",
      "circle",
      "refresh",
    ],
    categories: ["action", "status"],
  },
  plus: {
    tags: [
      "add",
      "create",
      "new",
      "increment",
      "addition",
      "math",
      "sum",
      "cross",
      "positive",
    ],
    categories: ["action"],
  },
  pods: {
    tags: [
      "pod",
      "kubernetes",
      "k8s",
      "container",
      "workload",
      "unit",
      "hexagon",
      "box",
    ],
    categories: ["product"],
    description: "Pods running containerised workloads.",
  },
  "power-off": {
    tags: [
      "power",
      "off",
      "switch",
      "button",
      "stop",
      "shutdown",
      "turn off",
      "energy",
      "standby",
      "indicator",
    ],
    categories: ["action"],
  },
  "power-on": {
    tags: ["power", "on", "button", "switch", "start", "enable", "boot"],
    categories: ["action"],
  },
  "priority-critical": {
    tags: [
      "priority",
      "critical",
      "urgency",
      "important",
      "alert",
      "warning",
      "high priority",
      "danger",
      "severe",
      "indicator",
      "importance",
      "status",
      "level",
      "severity",
      "gauge",
      "dial",
      "needle",
    ],
    categories: ["status"],
  },
  "priority-high": {
    tags: [
      "priority",
      "high",
      "important",
      "urgent",
      "alert",
      "information",
      "notice",
      "importance",
      "status",
      "level",
      "severity",
      "gauge",
      "dial",
      "needle",
    ],
    categories: ["status"],
  },
  "priority-low": {
    tags: [
      "priority",
      "low",
      "importance",
      "status",
      "task",
      "level",
      "minimal",
      "lesser",
      "severity",
      "indicator",
      "gauge",
      "dial",
      "needle",
    ],
    categories: ["status"],
  },
  "priority-medium": {
    tags: [
      "priority",
      "medium",
      "level",
      "importance",
      "moderate",
      "grade",
      "ranking",
      "status",
      "severity",
      "gauge",
      "dial",
      "needle",
    ],
    categories: ["status"],
  },
  "priority-negligible": {
    tags: [
      "priority",
      "negligible",
      "low",
      "importance",
      "status",
      "indicator",
      "minimal",
      "trivial",
      "ranking",
      "minor",
      "unimportant",
      "trend",
      "decrease",
      "severity",
      "level",
      "gauge",
      "dial",
      "needle",
    ],
    categories: ["status"],
  },
  "priority-unknown": {
    tags: [
      "priority",
      "unknown",
      "question mark",
      "query",
      "information",
      "status",
      "help",
      "level",
      "importance",
      "undecided",
      "undefined",
      "unclear",
      "severity",
      "indicator",
      "gauge",
      "dial",
      "needle",
    ],
    categories: ["status"],
  },
  "private-key": {
    tags: [
      "key",
      "private",
      "security",
      "access",
      "password",
      "encryption",
      "secret",
      "locked",
      "secure",
      "cryptographic",
    ],
    categories: ["object"],
  },
  profiles: {
    tags: [
      "profile",
      "lxd",
      "configuration",
      "config",
      "template",
      "preset",
      "cube",
      "instance",
    ],
    categories: ["product"],
    description: "Profiles describing how an instance is configured.",
  },
  queued: {
    tags: ["queue", "pending", "waiting", "status", "sequence", "next"],
    categories: ["status"],
    aliases: ["status-queued"],
  },
  repository: {
    tags: [
      "storage",
      "archive",
      "code",
      "version control",
      "git",
      "data",
      "database",
      "vault",
      "project",
      "history",
      "backup",
      "layers",
      "stack",
    ],
    categories: ["object"],
  },
  restart: {
    tags: ["refresh", "reload", "reset", "update", "arrow", "cycle"],
    categories: ["action"],
  },
  revisions: {
    tags: [
      "version",
      "history",
      "changes",
      "updates",
      "restore",
      "revert",
      "timeline",
      "progress",
      "clock",
      "rollback",
    ],
    categories: ["product"],
    description: "Revisions of a charm or package over time.",
  },
  rss: {
    tags: [
      "feed",
      "subscribe",
      "news",
      "blog",
      "content",
      "syndication",
      "web feed",
    ],
    categories: ["object"],
  },
  search: {
    tags: [
      "find",
      "explore",
      "magnify",
      "zoom",
      "glass",
      "looking",
      "investigate",
      "discover",
      "magnifying glass",
      "filter",
    ],
    categories: ["action"],
  },
  security: {
    tags: [
      "shield",
      "protection",
      "secure",
      "defense",
      "defence",
      "privacy",
      "guard",
      "safeguard",
      "safety",
    ],
    categories: ["status", "object"],
  },
  "security-error": {
    tags: [
      "security",
      "error",
      "shield",
      "fail",
      "protection",
      "warning",
      "danger",
      "incorrect",
      "threat",
      "malware",
      "virus",
      "defense",
      "defence",
      "denied",
      "problem",
      "access denied",
      "secure",
    ],
    categories: ["status"],
  },
  "security-tick": {
    tags: [
      "security",
      "shield",
      "check",
      "tick",
      "verified",
      "safe",
      "protected",
      "validation",
      "secure",
      "approval",
      "protection",
    ],
    categories: ["status"],
  },
  "security-warning": {
    tags: [
      "security",
      "warning",
      "shield",
      "alert",
      "danger",
      "protection",
      "privacy",
      "secure",
      "caution",
      "exclamation",
      "error",
    ],
    categories: ["status"],
  },
  select: {
    tags: [
      "selection",
      "dashed",
      "outline",
      "area",
      "border",
      "tool",
      "highlight",
    ],
    categories: ["action"],
  },
  "select-add": {
    tags: [
      "select",
      "add",
      "plus",
      "selection",
      "choose",
      "create",
      "mark",
      "tool",
      "new",
    ],
    categories: ["action"],
  },
  "select-remove": {
    tags: [
      "select",
      "remove",
      "delete",
      "selection",
      "minus",
      "dashed",
      "border",
      "area",
    ],
    categories: ["action"],
  },
  settings: {
    tags: [
      "gear",
      "cog",
      "configuration",
      "preferences",
      "options",
      "tools",
      "adjust",
      "customize",
      "customise",
    ],
    categories: ["action"],
  },
  share: {
    tags: [
      "social",
      "network",
      "connect",
      "link",
      "distribute",
      "send",
      "upload",
      "export",
    ],
    categories: ["action"],
  },
  show: {
    tags: [
      "eye",
      "visible",
      "visibility",
      "view",
      "look",
      "open",
      "see",
      "unhide",
      "watch",
    ],
    categories: ["action"],
  },
  "single-host": {
    tags: [
      "host",
      "server",
      "computer",
      "machine",
      "hexagon",
      "single",
      "network",
      "standalone",
    ],
    categories: ["product"],
    description: "A single host outside a cluster.",
  },
  snapshot: {
    tags: [
      "camera",
      "photo",
      "picture",
      "capture",
      "lens",
      "backup",
      "restore point",
      "state",
    ],
    categories: ["product"],
    description: "A point-in-time snapshot of an instance.",
  },
  snooze: {
    tags: ["sleep", "nap", "rest", "tired", "zzz", "slumber"],
    categories: ["action"],
  },
  spinner: {
    tags: [
      "loading",
      "progress",
      "indicator",
      "wait",
      "refresh",
      "circle",
      "processing",
      "loop",
      "asynchronous",
    ],
    categories: ["status"],
    description: "Something is loading.",
  },
  starred: {
    tags: [
      "star",
      "favorite",
      "favourite",
      "important",
      "bookmark",
      "rating",
      "achievement",
      "mark",
      "highlighted",
      "selected",
    ],
    categories: ["action"],
  },
  "starred-off": {
    tags: [
      "star",
      "off",
      "favorite",
      "favourite",
      "bookmark",
      "rating",
      "not starred",
      "remove favourite",
      "remove favorite",
    ],
    categories: ["action"],
    aliases: ["unstarred"],
  },
  statistics: {
    tags: [
      "chart",
      "graph",
      "data",
      "analysis",
      "growth",
      "trend",
      "progress",
      "report",
      "performance",
      "analytics",
      "line chart",
      "up",
      "increase",
      "arrow",
    ],
    categories: ["object"],
    description: "A line chart showing a trend over time.",
  },
  status: {
    tags: [
      "graph",
      "line",
      "data",
      "chart",
      "signal",
      "activity",
      "monitoring",
      "pulse",
      "heartbeat",
      "health",
    ],
    categories: ["object"],
  },
  stop: {
    tags: [
      "square",
      "media",
      "player",
      "button",
      "control",
      "end",
      "finish",
      "halt",
    ],
    categories: ["action"],
  },
  success: {
    tags: [
      "check",
      "complete",
      "done",
      "tick",
      "approve",
      "confirm",
      "accept",
      "correct",
      "right",
      "mark",
      "circle",
    ],
    categories: ["status"],
  },
  "success-fill": {
    tags: [
      "success",
      "check",
      "done",
      "complete",
      "mark",
      "tick",
      "verified",
      "approved",
      "good",
      "correct",
      "circle",
      "ok",
    ],
    categories: ["status"],
  },
  switcher: {
    tags: [
      "switch",
      "layout",
      "change",
      "rearrange",
      "swap",
      "toggle",
      "alternate",
      "exchange",
    ],
    categories: ["navigation"],
  },
  "switcher-dashboard": {
    tags: [
      "dashboard",
      "grid",
      "layout",
      "squares",
      "modules",
      "widgets",
      "overview",
      "control panel",
      "interface",
      "switcher",
    ],
    categories: ["navigation"],
  },
  "switcher-environments": {
    tags: [
      "switcher",
      "switch",
      "options",
      "list",
      "stages",
      "choose",
      "multiple",
    ],
    categories: ["navigation"],
  },
  "system-theme": {
    tags: [
      "system",
      "theme",
      "auto",
      "automatic",
      "os",
      "colour scheme",
      "color scheme",
      "appearance",
      "mode",
      "default theme",
    ],
    categories: ["theme"],
    description: "Follow the operating system's colour scheme.",
  },
  table: {
    tags: [
      "grid",
      "rows",
      "columns",
      "spreadsheet",
      "data",
      "list",
      "cells",
      "tabular",
    ],
    categories: ["object"],
    description: "Data laid out in rows and columns.",
  },
  tag: {
    tags: [
      "label",
      "identification",
      "mark",
      "brand",
      "product",
      "category",
      "bookmark",
      "favorite",
      "favourite",
      "organize",
      "organise",
      "metadata",
      "key",
      "symbol",
      "identifier",
      "badge",
      "marker",
      "flag",
    ],
    categories: ["object"],
  },
  "thumbs-down": {
    tags: [
      "dislike",
      "disapproval",
      "negative",
      "no",
      "bad",
      "vote down",
      "hand",
      "thumb down",
      "social media",
      "feedback",
    ],
    categories: ["action"],
  },
  "thumbs-up": {
    tags: [
      "like",
      "approve",
      "agree",
      "positive",
      "hand gesture",
      "good",
      "social media",
      "feedback",
    ],
    categories: ["action"],
  },
  tidy: {
    tags: [
      "clean",
      "organize",
      "organise",
      "broom",
      "sweep",
      "neat",
      "arrange",
      "sort",
      "housekeeping",
      "dust",
    ],
    categories: ["action"],
    description: "Clean up the current arrangement.",
  },
  "timed-out": {
    tags: [
      "timeout",
      "time",
      "clock",
      "timer",
      "expired",
      "overdue",
      "stop",
      "cancelled",
      "deadline",
      "out of time",
      "process",
      "waiting",
      "delay",
      "canceled",
    ],
    categories: ["status"],
  },
  units: {
    tags: [
      "unit",
      "juju",
      "instance",
      "blocks",
      "components",
      "workload",
      "replica",
      "scale",
    ],
    categories: ["product"],
    description: "Units of a deployed application.",
  },
  unlocked: {
    tags: [
      "open",
      "padlock",
      "security",
      "access",
      "lock",
      "permission",
      "authorized",
      "authorised",
    ],
    categories: ["status"],
    aliases: ["lock-unlock"],
  },
  unmount: {
    tags: [
      "eject",
      "disconnect",
      "drive",
      "storage",
      "remove",
      "detach",
      "device",
    ],
    categories: ["action", "product"],
    description: "Detach a storage device from the filesystem.",
  },
  upload: {
    tags: ["share", "send", "transfer", "data", "file", "arrow", "up", "save"],
    categories: ["action"],
  },
  usb: {
    tags: [
      "universal serial bus",
      "connector",
      "port",
      "data",
      "cable",
      "peripheral",
      "electronic",
      "device",
      "interface",
    ],
    categories: ["object"],
    description: "A USB connector.",
  },
  user: {
    tags: [
      "profile",
      "person",
      "avatar",
      "account",
      "contact",
      "human",
      "member",
    ],
    categories: ["object"],
  },
  "user-profile": {
    tags: [
      "user",
      "person",
      "account",
      "avatar",
      "human",
      "contact",
      "member",
      "login",
    ],
    categories: ["object"],
    aliases: ["profile"],
  },
  "user-group": {
    tags: [
      "user",
      "group",
      "people",
      "team",
      "community",
      "social",
      "network",
      "crowd",
      "profiles",
    ],
    categories: ["object"],
  },
  waiting: {
    tags: [
      "loading",
      "processing",
      "ellipsis",
      "dots",
      "progress",
      "indicator",
      "busy",
    ],
    categories: ["status"],
    aliases: ["status-waiting"],
  },
  warning: {
    tags: [
      "alert",
      "error",
      "caution",
      "danger",
      "problem",
      "triangle",
      "exclamation",
      "sign",
      "symbol",
    ],
    categories: ["status"],
  },
  "warning-fill": {
    tags: [
      "warning",
      "alert",
      "error",
      "caution",
      "danger",
      "exclamation",
      "triangle",
      "problem",
      "issue",
      "attention",
      "important",
    ],
    categories: ["status"],
  },
  website: {
    tags: [
      "browser",
      "internet",
      "web",
      "page",
      "layout",
      "window",
      "screen",
      "ui",
      "interface",
    ],
    categories: ["object"],
  },
  x: {
    tags: [
      "social media",
      "twitter",
      "platform",
      "network",
      "share",
      "communication",
      "app",
      "logo",
      "brand",
    ],
    categories: ["social-brand"],
  },
  youtube: {
    tags: [
      "video",
      "play",
      "social media",
      "streaming",
      "platform",
      "media",
      "logo",
      "brand",
    ],
    categories: ["social-brand"],
  },
};
