// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import * as decorators from "storybook/decorators.js";
import { NumberInput } from "./NumberInput.js";

const meta: Meta<typeof NumberInput> = {
  title: "subcomponents/NumberInput",
  component: NumberInput,
};

export default meta;
type Story = StoryObj<typeof NumberInput>;

export const Default: Story = {
  args: { name: "quantity", defaultValue: 1 },
};

export const WithRange: Story = {
  args: { name: "quantity", min: 0, max: 10, step: 1, defaultValue: 5 },
};

export const WithUnits: Story = {
  args: { name: "price", prefix: "$", suffix: "USD", defaultValue: 9.99 },
};

export const Disabled: Story = {
  args: { name: "quantity", defaultValue: 1, disabled: true },
};

/**
 * Presentational error state: the bare input wrapped in the field `.danger`
 * context (the visual layer the Wrapper applies on a real validation error).
 * For the react-hook-form-driven error see NumberField's `WithError`.
 */
export const ErrorState: Story = {
  decorators: [decorators.danger()],
  args: { name: "quantity" },
};
