// Generated by @canonical/summon-component:react v0.1.0

import type { ComponentProps, ReactNode } from "react";

type OwnProps = {
  /** Prefix element, rendered inside `span.prefix` (e.g. a currency symbol). */
  prefix?: ReactNode;

  /** Suffix element, rendered inside `span.suffix` (e.g. a unit). */
  suffix?: ReactNode;
};

/**
 * Props for the presentational Number input (no react-hook-form).
 *
 * The rendered root is a presentational `<div class="ds input number chrome">`
 * that only exists to position the prefix/suffix slots; the component's native
 * props are the inner `<input type="number">`'s — the labelable, registered
 * control every attribute is spread onto. `className` and `style` are applied to
 * the chrome wrapper, `id` to the control so the field label's `htmlFor` targets
 * a labelable element.
 *
 * `type` is omitted: the component always renders a number input.
 */
export type NumberInputProps = OwnProps &
  Omit<ComponentProps<"input">, keyof OwnProps | "type">;
