// Generated by @canonical/summon:component-svelte v0.1.0

import type { ComponentProps } from "svelte";
import { describe, expect, it } from "vitest";
import type { Locator } from "vitest/browser";
import { page as pageContext, userEvent } from "vitest/browser";
import type { RenderResult } from "vitest-browser-svelte";
import { render } from "vitest-browser-svelte";
import { tabToNextFocusable } from "../../../../testing/tabToNextFocusable.js";
import Component from "./Breadcrumbs.svelte";
import type { Segment } from "./types.js";

describe("Breadcrumbs component", () => {
  const baseProps = {
    segments: [
      { label: "Home", href: "/" },
      { label: "Category", href: "/category" },
      { label: "Subcategory", href: "/category/subcategory" },
      { label: "Current Page" },
    ],
  } satisfies ComponentProps<typeof Component>;

  it("renders", async () => {
    const page = await render(Component, { ...baseProps });
    await expect.element(componentLocator(page)).toBeInTheDocument();
  });

  describe("attributes", () => {
    it.each([
      ["id", "test-id"],
      ["aria-label", "test-aria-label"],
    ])("applies %s", async (attribute, expected) => {
      const page = await render(Component, {
        ...baseProps,
        [attribute]: expected,
      });
      await expect
        .element(page.getByRole("navigation"))
        .toHaveAttribute(attribute, expected);
    });

    it("applies classes", async () => {
      const page = await render(Component, {
        ...baseProps,
        class: "test-class",
      });
      await expect.element(componentLocator(page)).toHaveClass("test-class");
      await expect.element(componentLocator(page)).toHaveClass("ds");
      await expect.element(componentLocator(page)).toHaveClass("breadcrumbs");
    });

    it("applies style", async () => {
      const page = await render(Component, {
        ...baseProps,
        style: "color: orange;",
      });
      await expect
        .element(componentLocator(page))
        .toHaveStyle({ color: "orange" });
    });
  });

  describe("basic rendering", () => {
    it("renders breadcrumbs navigation", async () => {
      const page = await render(Component, { ...baseProps });
      await expect
        .element(page.getByRole("navigation", { name: "Breadcrumbs" }))
        .toBeInTheDocument();
      await expect.element(page.getByRole("list")).toBeInTheDocument();
    });

    it("renders all segments", async () => {
      const page = await render(Component, { ...baseProps });
      for (const segment of baseProps.segments) {
        if (segment.href) {
          const linkElement = page.getByRole("link", {
            name: segment.label,
            exact: true,
          });
          await expect.element(linkElement).toBeInTheDocument();
          await expect
            .element(linkElement)
            .toHaveAttribute("href", segment.href);
        } else {
          await expect
            .element(page.getByText(segment.label))
            .toBeInTheDocument();
        }
      }
    });
  });

  describe("basic attributes", () => {
    it("marks last linked segment as current page", async () => {
      const segments = [
        { label: "Home", href: "/" },
        { label: "Category", href: "/category" },
        { label: "Current", href: "/current" },
      ];
      const page = await render(Component, {
        ...baseProps,
        segments,
      });

      await expect
        .element(page.getByRole("link", { name: "Home" }))
        .not.toHaveAttribute("aria-current");
      await expect
        .element(page.getByRole("link", { name: "Category" }))
        .not.toHaveAttribute("aria-current");
      await expect
        .element(page.getByRole("link", { name: "Current" }))
        .toHaveAttribute("aria-current", "page");
    });
  });

  describe("collapse mechanism", () => {
    const collapseProps = {
      ...baseProps,
      segments: [
        { label: "Home", href: "/" },
        { label: "Level 1", href: "/level1" },
        { label: "Level 2", href: "/level1/level2" },
        { label: "Level 3", href: "/level1/level2/level3" },
        { label: "Level 4", href: "/level1/level2/level3/level4" },
        {
          label: "Current Page",
          href: "/level1/level2/level3/level4/current",
        },
      ],
    };

    it("has all segments visible if no collapse is applied", async () => {
      const page = await render(Component, {
        ...collapseProps,
        minNumExpanded: "all",
      });

      for (const segment of collapseProps.segments) {
        await expect
          .element(page.getByRole("link", { name: segment.label }))
          .toBeVisible();
      }
    });

    it("properly collapses if width is insufficient", async () => {
      const page = await render(Component, {
        ...collapseProps,
        minNumExpanded: 0,
      });

      // Mock narrow container
      pageContext.viewport(100, 800);

      await expectAreCollapsed(page);

      // Make sure the collapsed segments are not accessible and all links are in the document
      expect(page.getByRole("link").elements()).toHaveLength(
        collapseProps.segments.length,
      );
      // Make sure that all of the segments are collapsed
      expect(
        collapsedLocator(page).getByRole("listitem").elements(),
      ).toHaveLength(collapseProps.segments.length);

      // Expand the container
      pageContext.viewport(1000, 800);

      // Check that no segments are collapsed again
      await expectNoCollapsed(page);
      expect(page.getByRole("link").elements()).toHaveLength(
        collapseProps.segments.length,
      );
    });

    it("properly works with the numeric collapse value", async () => {
      const minNumExpanded = 3;
      const page = await render(Component, {
        ...collapseProps,
        minNumExpanded,
      });

      // Mock narrow container
      pageContext.viewport(100, 800);

      // Check that maxNumCollapsed segments are collapsed
      await expectAreCollapsed(page);
      expect(
        collapsedLocator(page).getByRole("listitem").elements(),
      ).toHaveLength(collapseProps.segments.length - minNumExpanded);
    });

    describe("edge cases", () => {
      it("works properly when minNumExpanded is greater than segments count", async () => {
        const page = await render(Component, {
          ...collapseProps,
          minNumExpanded: 1000,
        });

        pageContext.viewport(100, 800);

        await expectNoCollapsed(page);
        expect(page.getByRole("link").elements()).toHaveLength(
          collapseProps.segments.length,
        );
      });

      it("works properly when minNumExpanded is set to negative value", async () => {
        const page = await render(Component, {
          ...collapseProps,
          minNumExpanded: -1,
        });

        pageContext.viewport(100, 800);

        await expectAreCollapsed(page);
        expect(
          collapsedLocator(page).getByRole("listitem").elements(),
        ).toHaveLength(collapseProps.segments.length);
      });
    });
  });

  describe("accessibility", () => {
    describe("list structure", () => {
      it("uses proper flat list structure", async () => {
        const page = await render(Component, { ...baseProps });

        await expect.element(page.getByRole("list")).toBeInTheDocument();
        expect(page.getByRole("listitem").elements()).toHaveLength(
          baseProps.segments.length,
        );
      });

      it("uses proper flat list structure with collapsed segments", async () => {
        const segments = [
          { label: "Home", href: "/" },
          { label: "Level 1", href: "/level1" },
          { label: "Level 2", href: "/level1/level2" },
          { label: "Level 3", href: "/level1/level2/level3" },
          { label: "Level 4", href: "/level1/level2/level3/level4" },
          {
            label: "Current Page",
            href: "/level1/level2/level3/level4/current",
          },
        ];
        const page = await render(Component, {
          ...baseProps,
          segments,
          minNumExpanded: 1,
        });

        pageContext.viewport(100, 800);

        await expectAreCollapsed(page);
        expect(
          page.getByRole("list").getByRole("listitem").elements(),
        ).toHaveLength(segments.length);
      });
    });

    describe("focus management", () => {
      it("allows focusing links with tab key", async () => {
        const page = await render(Component, { ...baseProps });

        const firstLink = page.getByRole("link", { name: "Home" });
        await expect.element(firstLink).toBeVisible();
        await userEvent.click(page.baseElement);

        await tabToNextFocusable();
        await expect.element(firstLink).toHaveFocus();
        await tabToNextFocusable();
        await expect
          .element(
            page.getByRole("link", {
              name: "Category",
              exact: true,
            }),
          )
          .toHaveFocus();
      });

      it("allows focusing links with tab key when segments are collapsed", async () => {
        const page = await render(Component, {
          ...baseProps,
          minNumExpanded: 2,
        });

        pageContext.viewport(100, 800);

        await expectAreCollapsed(page);

        const firstLink = page.getByRole("link", { name: "Home" });
        await expect.element(firstLink).toBeInTheDocument();
        await userEvent.click(page.baseElement);

        await tabToNextFocusable();
        await expect.element(firstLink).toHaveFocus();
        await tabToNextFocusable();
        await expect
          .element(
            page.getByRole("link", {
              name: "Category",
              exact: true,
            }),
          )
          .toHaveFocus();
        await tabToNextFocusable();
        await expect
          .element(
            page.getByRole("link", {
              name: "Subcategory",
            }),
          )
          .toHaveFocus();
      });
    });
  });

  describe("segments", () => {
    it("segments with href are rendered as links", async () => {
      const page = await render(Component, {
        ...baseProps,
        segments: [
          { label: "Linked Segment", href: "/linked" },
          { label: "Text Segment" },
        ],
      });

      const linkedSegment = page.getByRole("link", { name: "Linked Segment" });
      await expect.element(linkedSegment).toBeInTheDocument();
      await expect.element(linkedSegment).toHaveAttribute("href", "/linked");

      await expect
        .element(page.getByText("Text Segment"))
        .not.toHaveRole("link");
    });

    it("segments props are reactive", async () => {
      const segment = $state<Segment>({ label: "Initial", href: "/initial" });

      const page = await render(Component, {
        ...baseProps,
        segments: [segment],
      });

      const linkElement = page.getByRole("link", { name: "Initial" });
      await expect.element(linkElement).toBeInTheDocument();

      segment.label = "Updated";

      await expect
        .element(page.getByRole("link", { name: "Updated" }))
        .toBeInTheDocument();

      segment.href = undefined;

      await expect.element(page.getByText("Updated")).not.toHaveRole("link");
    });
  });
});

function componentLocator(page: RenderResult<typeof Component>): Locator {
  return page.getByRole("navigation");
}

function collapsedLocator(page: RenderResult<typeof Component>): Locator {
  return page.getByTestId("collapsed-segments");
}

// Utility functions to await for Svelte to settle the collapsed state
async function expectAreCollapsed(page: RenderResult<typeof Component>) {
  await expect.element(collapsedLocator(page)).toBeInTheDocument();
}

async function expectNoCollapsed(page: RenderResult<typeof Component>) {
  await expect.element(collapsedLocator(page)).not.toBeInTheDocument();
}
