// Generated by @canonical/summon:component-svelte v0.1.0

import type { SvelteHTMLElements } from "svelte/elements";
import type { LinkProps } from "../Link/index.js";

type LinkSegment = Omit<LinkProps, "children" | "href"> & {
  label: string;
  href: string;
};

type TextSegment = Omit<SvelteHTMLElements["span"], "children"> & {
  label: string;
  href?: never;
};

export type BreadcrumbsSegment = LinkSegment | TextSegment;

export interface BreadcrumbsProps
  extends Omit<SvelteHTMLElements["nav"], "children"> {
  /**
   * Breadcrumb segments.
   */
  segments: BreadcrumbsSegment[];
  /**
   * The number of segments, from the end, that should never be collapsed.
   * If set to `all` or a number greater or equal to the total number of segments, no segments will be collapsed.
   *
   * @default 1
   */
  minNumExpanded?: "all" | number;
}

export type PossiblyCollapsedSegment = BreadcrumbsSegment & {
  collapsed?: boolean;
};
