// Generated by @canonical/summon-application:application/react v0.1.0

import { group, route, wrapper } from "@canonical/router-core";
import type { ReactElement, ReactNode } from "react";
import { JourneyViewProvider, journeysRoutes } from "#addons/journeys";
import { accountRoutes } from "#domains/account";
import { componentsRoutes } from "#domains/components";
import { lensRoutes } from "#domains/lenses";
import {
  definitionsRoutes,
  LensFilterProvider,
} from "#domains/lenses/definitions";
import { standardsRoutes } from "#domains/lenses/standards";
import { marketingRoutes } from "#domains/marketing";
import { playgroundRoutes } from "#domains/playground";
import { withAuth } from "#lib/authGuard";
import Shell from "#lib/Shell";

/**
 * Every public route mounts inside the DocsShell — the one shell instance
 * of `layout.shell` (P-4.1). The wrapper is deliberately just the Shell:
 * the frame owns rail/strip/canvas/footer, routes own only their canvas.
 *
 * Two additions, same shape, same reason (AV-274 and RULING 1): the
 * Definitions lens's filter provider and the Journeys lens's view provider
 * sit ABOVE the Shell. They have to. The Shell renders the mode strip, and a
 * route claims the strip's sockets with static `meta` — so the strip's
 * Controls are mounted BY THE FRAME, as siblings of the canvas rather than
 * descendants of the page. No prop path exists from the explorer up to
 * them, so the shared state has to cross that boundary through context, and
 * each provider must therefore enclose both the strip and the canvas.
 *
 * Routes outside those lenses pay effectively nothing: each provider is one
 * `useState` holding a no-op value that nothing reads, since the other
 * lenses claim no sockets that consume it. The alternative — widening
 * `StripSlotsEntry` so every claim can carry live state — would make every
 * future lens pay for these two's requirement, which is the larger cost.
 */
const publicLayout = wrapper<ReactElement>({
  id: "public-layout",
  component: ({ children }: { children: ReactNode }) => (
    <LensFilterProvider>
      <JourneyViewProvider>
        <Shell>{children}</Shell>
      </JourneyViewProvider>
    </LensFilterProvider>
  ),
});

const notFoundRoute = route({
  url: "/not-found",
  content: () => (
    <section>
      <h1>Page not found</h1>
      <p>The page you are looking for does not exist.</p>
    </section>
  ),
});

const [guide, home] = group(publicLayout, [
  marketingRoutes.guide,
  marketingRoutes.home,
] as const);

const [account, login] = group(publicLayout, [
  accountRoutes.account,
  accountRoutes.login,
] as const);

const [playground] = group(publicLayout, [
  playgroundRoutes.playground,
] as const);

// The v1 lens set (owner-ruled order): Home · Components · Definitions ·
// Standards · Guides. Home is marketingRoutes.home above; the Components
// lens is live (catalog + entity, P-5) from `#domains/components`; the
// Definitions lens is live (the explorer triptych + term view, P-5) from
// `#domains/lenses/definitions`; the Standards lens is live (the
// category-grouped index + reading pages, P-5) from
// `#domains/lenses/standards`; Guides stays a stub until P-5 builds its
// views.
//
// Journeys is in this table but is NOT one of them. It is a pragma-specific
// ADD-ON (`#addons/journeys`, not `#domains/lenses/…`) — an owner
// reclassification, because it reads pragma's own ontology through generic
// instance-level relation traversal, which the provider-neutral contract
// cannot express. It is wired in BY HAND here, alongside the core lenses,
// only because the docsite has no plugin mechanism yet; when one exists the
// add-on registers its own routes and these two lines go away. Until then it
// stays live and addressable — the ruling was "keep it on side", not "hide
// it". See `src/addons/journeys/index.ts`.
const [
  components,
  definitions,
  standards,
  journeys,
  guides,
  componentEntity,
  definitionsTerm,
  standardEntity,
  journeysJob,
] = group(publicLayout, [
  componentsRoutes.components,
  definitionsRoutes.definitions,
  standardsRoutes.standards,
  journeysRoutes.journeys,
  lensRoutes.guides,
  componentsRoutes.componentEntity,
  definitionsRoutes.definitionsTerm,
  standardsRoutes.standardEntity,
  journeysRoutes.journeysJob,
] as const);

const appRoutes = {
  guide,
  home,
  account,
  login,
  playground,
  components,
  definitions,
  standards,
  journeys,
  guides,
  componentEntity,
  definitionsTerm,
  standardEntity,
  journeysJob,
} as const;

export type AppRoutes = typeof appRoutes;

declare module "@canonical/router-react" {
  interface RouterRegister {
    routes: AppRoutes;
  }
}

/**
 * The client half of the demo auth guard. The server half is
 * `getAuthRedirectHref`, called by each HTTP entry point before it renders —
 * both live in `#lib/authGuard`, so the two halves cannot drift apart about
 * which paths are protected.
 */
export const middleware = [withAuth("/login")] as const;

export { appRoutes, notFoundRoute };
