// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import * as decorators from "storybook/decorators.js";
import { RadioInput } from "./RadioInput.js";

const meta: Meta<typeof RadioInput> = {
  title: "subcomponents/RadioInput",
  component: RadioInput,
};

export default meta;
type Story = StoryObj<typeof RadioInput>;

export const Default: Story = {
  args: { name: "choice", value: "a" },
};

export const Checked: Story = {
  args: { name: "choice", value: "a", defaultChecked: true },
};

export const Disabled: Story = {
  args: { name: "choice", value: "a", disabled: true },
};

/**
 * Presentational error state: the bare radio wrapped in the field `.danger`
 * context. A single radio control has no error border of its own — the error is
 * conveyed by the `FieldError` message (radio groups signal validity at the
 * group/message level, not per control). For the react-hook-form-driven error
 * on a radio group see ChoicesField's `WithError`.
 */
export const ErrorState: Story = {
  decorators: [decorators.danger()],
  args: { name: "choice" },
};
