// Generated by @canonical/summon-component:react v0.1.0

import type { ComponentProps } from "react";

/**
 * Props for the presentational Radio input (no react-hook-form). Renders an
 * `<input>` as its root.
 *
 * `type` is omitted: the component always renders a radio, so exposing it would
 * be confusing/ineffective.
 */
export type RadioInputProps = Omit<ComponentProps<"input">, "type">;
