// Generated by @canonical/summon-application:application/react v0.1.0

import * as matchers from "@testing-library/jest-dom/matchers";
import { cleanup } from "@testing-library/react";
import { afterEach, expect, vi } from "vitest";

expect.extend(matchers as unknown as Parameters<typeof expect.extend>[0]);

// relay-test-utils' `createMockEnvironment` wraps environment methods in
// `jest.fn` mocks whenever NODE_ENV === "test", reaching for a global `jest`
// object. Vitest sets NODE_ENV=test but exposes `vi` instead, so alias it —
// `vi.fn` is API-compatible with the `jest.fn` surface relay-test-utils uses
// (`.mock`, `.mockClear`).
(globalThis as { jest?: typeof vi }).jest = vi;

// jsdom implements no `window.matchMedia`, but `usePreferredTheme` (the
// rail's ThemeSelector) resolves its initial value through it whenever a
// `window` exists. A minimal always-false stub is the standard shim; node-
// environment test files (`@vitest-environment node`) have no window and
// exercise the hook's real SSR branch instead, so the stub is jsdom-only.
if (typeof window !== "undefined" && typeof window.matchMedia === "undefined") {
  const matchMediaStub = (query: string): MediaQueryList =>
    ({
      addEventListener: () => {},
      addListener: () => {},
      dispatchEvent: () => false,
      matches: false,
      media: query,
      onchange: null,
      removeEventListener: () => {},
      removeListener: () => {},
    }) as unknown as MediaQueryList;
  window.matchMedia = matchMediaStub;
}

afterEach(() => {
  cleanup();
});
