// Generated by @canonical/summon-component:react v0.1.0

import { fireEvent, render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import type { FooterRoot } from "../../types.js";
import Footer from "./Footer.js";

describe("Footer", () => {
  it("applies custom className", () => {
    render(<Footer className="custom-class" />);
    const element = document.querySelector("footer");
    expect(element?.className).toContain("ds footer");
    expect(element?.className).toContain("custom-class");
  });

  it("passes through additional props", () => {
    render(<Footer data-testid="test-component" />);
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });

  it("renders an empty region with no root", () => {
    const { container } = render(<Footer />);
    const element = container.querySelector("footer");
    expect(element).toBeEmptyDOMElement();
  });

  describe("root (the footer's only data surface)", () => {
    const root: FooterRoot = {
      key: "footer",
      items: [
        { label: "Ada Lovelace", url: "/account" },
        { label: "Notifications", url: "/notifications", slot: <span>3</span> },
        { label: "Log out", control: "button", onClick: vi.fn() },
      ],
    };

    it("renders each item with its given label", () => {
      render(<Footer root={root} />);
      expect(
        screen.getByRole("link", { name: "Ada Lovelace" }),
      ).toHaveAttribute("href", "/account");
      expect(
        screen.getByRole("link", { name: /^Notifications/ }),
      ).toHaveAttribute("href", "/notifications");
      expect(
        screen.getByRole("button", { name: "Log out" }),
      ).toBeInTheDocument();
    });

    it("renders navigable items as links and action items as buttons", () => {
      render(<Footer root={root} />);
      expect(
        screen.getByRole("link", { name: "Ada Lovelace" }),
      ).toBeInTheDocument();
      expect(
        screen.getByRole("button", { name: "Log out" }),
      ).toBeInTheDocument();
    });

    it("calls onClick for an action item", () => {
      const onClick = vi.fn();
      render(
        <Footer
          root={{
            key: "footer",
            items: [{ label: "Log out", control: "button", onClick }],
          }}
        />,
      );
      screen.getByRole("button", { name: "Log out" }).click();
      expect(onClick).toHaveBeenCalledOnce();
    });

    it("renders the leading icon", () => {
      const { container } = render(
        <Footer
          root={{
            key: "footer",
            items: [{ label: "Ada Lovelace", icon: "certificate" }],
          }}
        />,
      );
      expect(
        container.querySelector("use[href$='certificate.svg#certificate']"),
      ).toBeInTheDocument();
    });

    it("renders the trailing slot", () => {
      render(<Footer root={root} />);
      expect(screen.getByText("3")).toBeInTheDocument();
    });

    it("marks the active row (url matching currentUrl)", () => {
      render(<Footer root={root} currentUrl="/account" />);
      expect(
        screen.getByRole("link", { name: "Ada Lovelace" }).closest("li"),
      ).toHaveAttribute("data-active", "true");
      expect(
        screen.getByRole("link", { name: /^Notifications/ }).closest("li"),
      ).not.toHaveAttribute("data-active");
    });

    it("control: button always wins over url, even when both are given", () => {
      const onClick = vi.fn();
      render(
        <Footer
          root={{
            key: "footer",
            items: [
              {
                label: "Ada Lovelace",
                url: "/account",
                control: "button",
                onClick,
              },
            ],
          }}
        />,
      );
      expect(
        screen.getByRole("button", { name: "Ada Lovelace" }),
      ).toBeInTheDocument();
      expect(screen.queryByRole("link")).not.toBeInTheDocument();
    });

    it("renders a depth-1 expandable disclosure with leaf children", () => {
      render(
        <Footer
          root={{
            key: "footer",
            items: [
              {
                label: "Theme",
                icon: "dark-theme",
                items: [
                  { label: "Light", icon: "light-theme" },
                  { label: "Dark", icon: "dark-theme" },
                ],
              },
            ],
          }}
        />,
      );
      expect(screen.getByText("Theme")).toBeInTheDocument();
      expect(document.querySelector("details")).toBeInTheDocument();
      expect(screen.getByText("Light")).toBeInTheDocument();
      expect(screen.getByText("Dark")).toBeInTheDocument();
    });

    it("marks the active leaf under its open expandable parent", () => {
      const { container } = render(
        <Footer
          root={{
            key: "footer",
            items: [
              {
                label: "Theme",
                items: [{ label: "Dark", url: "/settings/appearance" }],
              },
            ],
          }}
          currentUrl="/settings/appearance"
        />,
      );
      const details = container.querySelector("details") as HTMLDetailsElement;
      expect(details).toHaveAttribute("open");
      expect(
        screen.getByRole("link", { name: "Dark" }).closest("li"),
      ).toHaveAttribute("data-active", "true");
    });

    it("does not seed an expandable open when its label-only children match an unset currentUrl", () => {
      // `undefined === undefined` must not read as "this child is the
      // current location": an expandable of label-only children stays
      // closed when currentUrl isn't wired.
      const { container } = render(
        <Footer
          root={{
            key: "footer",
            items: [
              {
                label: "Theme",
                items: [
                  { label: "Light", icon: "light-theme" },
                  { label: "Dark", icon: "dark-theme" },
                ],
              },
            ],
          }}
        />,
      );
      const details = container.querySelector("details") as HTMLDetailsElement;
      expect(details).not.toHaveAttribute("open");
    });

    it("collapses the expandable when a leaf child row is activated", () => {
      const { container } = render(
        <Footer
          currentUrl="/theme/light"
          root={{
            key: "footer",
            items: [
              {
                label: "Theme",
                items: [
                  { label: "Light", url: "/theme/light" },
                  { label: "Log out", control: "button", onClick: vi.fn() },
                ],
              },
            ],
          }}
        />,
      );
      const details = container.querySelector("details") as HTMLDetailsElement;

      // Starts open — the seed derives from the current leaf (currentUrl)…
      expect(details).toHaveAttribute("open");

      // …and activating the link leaf row collapses it. (Seeded open per
      // row kind rather than re-opening via the summary between clicks:
      // jsdom queues the summary's toggle event as a task, so React's
      // expanded state would lag the DOM across an immediate next click.)
      fireEvent.click(screen.getByRole("link", { name: "Light" }));
      expect(details).not.toHaveAttribute("open");
    });

    it("collapses the expandable when a button child row is activated", () => {
      const { container } = render(
        <Footer
          currentUrl="/theme/light"
          root={{
            key: "footer",
            items: [
              {
                label: "Theme",
                items: [
                  { label: "Light", url: "/theme/light" },
                  { label: "Log out", control: "button", onClick: vi.fn() },
                ],
              },
            ],
          }}
        />,
      );
      const details = container.querySelector("details") as HTMLDetailsElement;
      expect(details).toHaveAttribute("open");

      fireEvent.click(screen.getByRole("button", { name: "Log out" }));
      expect(details).not.toHaveAttribute("open");
    });

    it("renders label-only rows as plain labels, not inert buttons", () => {
      // A label-only leaf (e.g. a logged-in username) is not an action —
      // rendering it as a <button> announces an action that does nothing.
      render(
        <Footer
          root={{
            key: "footer",
            items: [{ label: "Ada Lovelace", icon: "user" }],
          }}
        />,
      );
      expect(screen.getByText("Ada Lovelace")).toBeInTheDocument();
      expect(screen.queryByRole("button")).not.toBeInTheDocument();
      expect(screen.queryByRole("link")).not.toBeInTheDocument();
    });

    it("renders expandable children as plain (non-navigable) rows", () => {
      render(
        <Footer
          root={{
            key: "footer",
            items: [
              {
                label: "Theme",
                items: [{ label: "System" }],
              },
            ],
          }}
        />,
      );
      // Label-only children of an expandable are plain labels too — the
      // disclosure's toggle is the summary, not these rows.
      expect(screen.getByText("System")).toBeInTheDocument();
      expect(
        screen.queryByRole("button", { name: "System" }),
      ).not.toBeInTheDocument();
      expect(
        screen.queryByRole("link", { name: "System" }),
      ).not.toBeInTheDocument();
    });
  });
});
