<script lang="ts" module>
  // Generated by @canonical/summon:component-svelte v0.1.0

  import { MODIFIER_FAMILIES } from "@canonical/ds-types";
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import Badge from "./Badge.svelte";

  const { Story } = defineMeta({
    title: "Components/Badge",
    component: Badge,
    tags: ["autodocs"],
    argTypes: {
      value: { control: { type: "number", min: 0, step: 1 } },
      formatter: {
        control: false,
        table: { disable: true },
      },
    },
  });
</script>

<Story name="Default" args={{ value: 42 }} />

<Story
  name="Capped"
  argTypes={{ value: { table: { disable: true } } }}
  args={{ capped: true }}
>
  {#snippet template(args)}
    <div class="row">
      {#each [0, 42, 999, 2100] as value (value)}
        <Badge {...args} {value} />
      {/each}
    </div>
  {/snippet}
</Story>

<Story
  name="Non capped"
  argTypes={{ value: { table: { disable: true } } }}
  args={{ capped: false }}
>
  {#snippet template(args)}
    <div class="row">
      {#each [0, 42, 999, 2100, 10_000, 251_110, 8_899_500, 1_111_111_111, 98_123_456_789_890] as value (value)}
        <Badge {...args} {value} />
      {/each}
    </div>
  {/snippet}
</Story>

<Story name="Disabled" args={{ value: 42 }} >
{#snippet template(args)}
    <div class="disabled" style="border: 1px dashed var(--color-border); width: 200px; min-height: 100px;">
      <span style="display: block;">Disabled parent</span>
      <Badge {...args} />
    </div>
  {/snippet}
</Story>

<Story
  name="Criticalities"
  argTypes={{ criticality: { table: { disable: true } } }}
  args={{ value: 42 }}
>
  {#snippet template(args)}
    {#each [undefined, ...MODIFIER_FAMILIES.criticality] as criticality (criticality)}
      <div class="row">
        <Badge {...args} {criticality} />
        {criticality ?? "default"}
      </div>
    {/each}
  {/snippet}
</Story>
