// Generated by @canonical/summon-component:react v0.1.0

import {
  createMemoryAdapter,
  createRouter,
  type RouteMap,
  route,
} from "@canonical/router-core";
import { RouterProvider } from "@canonical/router-react";
import { act } from "react";
import { hydrateRoot, type Root } from "react-dom/client";
import { renderToString } from "react-dom/server";
import { afterEach, describe, expect, it, vi } from "vitest";
import { appRoutes, notFoundRoute } from "../../routes.js";
import createStaticRouter from "../router/createStaticRouter.js";
import { SHELL_STRIP_META_KEY } from "./constants.js";
import Shell from "./Shell.js";
import type { StripSlotsEntry } from "./types.js";

describe("Shell SSR", () => {
  it("server-renders the whole frame with children in the canvas", () => {
    const html = renderToString(
      <RouterProvider
        router={createStaticRouter(appRoutes, "/", { notFound: notFoundRoute })}
      >
        <Shell>Test content</Shell>
      </RouterProvider>,
    );
    expect(html).toContain("ds shell");
    expect(html).toContain('data-region="primary-nav"');
    expect(html).toContain('data-region="mode-strip"');
    expect(html).toContain('data-region="canvas"');
    expect(html).toContain('data-region="footer"');
    expect(html).toContain("Test content");
  });
});

// Driving `act` directly (no Testing Library wrapper) needs the flag.
(
  globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }
).IS_REACT_ACT_ENVIRONMENT = true;

/** The strip claim under hydration — the same fixture voice as
 * `Shell.tests.tsx`'s handshake test. */
const stripEntry: StripSlotsEntry = {
  Context: () => <span>Definitions</span>,
  Controls: () => <button type="button">Governance lens</button>,
  Status: () => <span>19 of 31 validated</span>,
};

/** A name-complete synthetic route map (the rail's links must all resolve)
 * whose home route claims the strip via `meta` — `Shell.tests.tsx`'s
 * synthetic-route pattern, here driven through SSR + hydration. */
const claimRoutes: RouteMap = {
  home: route({
    url: "/",
    content: () => null,
    meta: { [SHELL_STRIP_META_KEY]: stripEntry },
  }),
  components: route({ url: "/components", content: () => null }),
  definitions: route({ url: "/definitions", content: () => null }),
  standards: route({ url: "/standards", content: () => null }),
  journeys: route({ url: "/journeys", content: () => null }),
  guides: route({ url: "/guides", content: () => null }),
  playground: route({ url: "/playground", content: () => null }),
  account: route({ url: "/account", content: () => null }),
} as const;

/**
 * The meta-present strip path under hydration (the P-5 seam, proven before
 * P-5 mounts real claims). `hydrateApp.tests.tsx` certifies the seam over
 * `/playground` — a strip-LESS route; this suite hydrates a route whose
 * `meta` carries a `SHELL_STRIP_META_KEY` claim, per the repo-standard
 * method: direct `hydrateRoot`, `onRecoverableError` spy asserted never
 * called (React 19's mismatch channel — a `console.error` spy does NOT
 * catch it), and a deliberate-breakage control proving the spy can fail.
 */
describe("Shell hydration over a strip claim (the P-5 seam)", () => {
  const roots: Root[] = [];
  const containers: HTMLElement[] = [];

  afterEach(async () => {
    for (const root of roots.splice(0)) {
      await act(async () => {
        root.unmount();
      });
    }
    for (const container of containers.splice(0)) {
      container.remove();
    }
  });

  const renderClaimedServerHtml = (): string =>
    renderToString(
      <RouterProvider router={createStaticRouter(claimRoutes, "/")}>
        <Shell>Canvas content</Shell>
      </RouterProvider>,
    );

  /** Hydrates the claimed composition over `serverHtml`; returns the spy. */
  async function hydrateInto(serverHtml: string) {
    const container = document.createElement("div");
    container.innerHTML = serverHtml;
    document.body.appendChild(container);
    containers.push(container);
    const onRecoverableError = vi.fn();
    await act(async () => {
      roots.push(
        hydrateRoot(
          container,
          <RouterProvider
            router={createRouter(claimRoutes, {
              adapter: createMemoryAdapter("/"),
            })}
          >
            <Shell>Canvas content</Shell>
          </RouterProvider>,
          { onRecoverableError },
        ),
      );
    });
    return { container, onRecoverableError };
  }

  it("hydrates the claimed sockets without a recoverable error", async () => {
    const serverHtml = renderClaimedServerHtml();
    // The claim is in the server bytes — the seam has something to hydrate.
    expect(serverHtml).toContain("Governance lens");

    const { container, onRecoverableError } = await hydrateInto(serverHtml);

    // React 19's hydration-mismatch channel stayed silent…
    expect(onRecoverableError).not.toHaveBeenCalled();
    // …and every claimed socket is live in the hydrated tree.
    expect(container.querySelector('[data-slot="context"]')?.textContent).toBe(
      "Definitions",
    );
    expect(container.querySelector('[data-slot="controls"]')?.textContent).toBe(
      "Governance lens",
    );
    expect(container.querySelector('[data-slot="status"]')?.textContent).toBe(
      "19 of 31 validated",
    );
  });

  it("control: tampered strip bytes report a recoverable error", async () => {
    const serverHtml = renderClaimedServerHtml();
    const tampered = serverHtml.replace("Governance lens", "Impostor lens");
    expect(tampered).not.toBe(serverHtml);
    // React also prints the mismatch diff via console.error; silence it so
    // the deliberate failure does not pollute the run's output.
    const consoleError = vi
      .spyOn(console, "error")
      .mockImplementation(() => {});
    try {
      const { onRecoverableError } = await hydrateInto(tampered);
      expect(onRecoverableError).toHaveBeenCalled();
    } finally {
      consoleError.mockRestore();
    }
  });
});
