// Generated by @canonical/summon-component:react v0.1.0

import {
  createMemoryAdapter,
  createRouter,
  type RouteMap,
  route,
} from "@canonical/router-core";
import { RouterProvider } from "@canonical/router-react";
import { render, screen } from "@testing-library/react";
import type { ReactElement, ReactNode } from "react";
import { describe, expect, it } from "vitest";
import { CANVAS_ELEMENT_ID, SHELL_STRIP_META_KEY } from "./constants.js";
import Shell from "./Shell.js";
import type { StripSlotsEntry } from "./types.js";

/** A name-complete bare route map (the rail's links must all resolve),
 * with the home route's `meta` injectable for the strip-claim tests. */
const bareRoutes = (homeMeta?: Readonly<Record<string, unknown>>): RouteMap =>
  ({
    home: route({ url: "/", content: () => null, meta: homeMeta }),
    components: route({ url: "/components", content: () => null }),
    definitions: route({ url: "/definitions", content: () => null }),
    standards: route({ url: "/standards", content: () => null }),
    journeys: route({ url: "/journeys", content: () => null }),
    guides: route({ url: "/guides", content: () => null }),
    playground: route({ url: "/playground", content: () => null }),
    account: route({ url: "/account", content: () => null }),
  }) as const;

const renderShell = (
  children: ReactNode,
  homeMeta?: Readonly<Record<string, unknown>>,
): ReactElement => (
  <RouterProvider
    router={createRouter(bareRoutes(homeMeta), {
      adapter: createMemoryAdapter("/"),
    })}
  >
    <Shell>{children}</Shell>
  </RouterProvider>
);

describe("Shell", () => {
  it("renders the frame regions around the canvas", () => {
    render(renderShell(<p>Canvas content</p>));
    // Rail (the one global region), strip band, canvas, footer.
    expect(
      screen.getByRole("navigation", { name: "Primary" }),
    ).toBeInTheDocument();
    expect(
      document.querySelector('[data-region="mode-strip"]'),
    ).toBeInTheDocument();
    expect(
      document.querySelector('[data-region="footer"]'),
    ).toBeInTheDocument();
    const canvas = screen.getByRole("main");
    expect(canvas.id).toBe(CANVAS_ELEMENT_ID);
    expect(canvas.dataset.region).toBe("canvas");
    // Children mount inside the canvas plate, nowhere else.
    expect(canvas.contains(screen.getByText("Canvas content"))).toBe(true);
  });

  it("offers a skip link targeting the canvas", () => {
    render(renderShell(<p>Content</p>));
    expect(
      screen.getByRole("link", { name: "Skip to content" }),
    ).toHaveAttribute("href", `#${CANVAS_ELEMENT_ID}`);
  });

  it("renders empty strip sockets when the route claims none", () => {
    render(renderShell(<p>Content</p>));
    for (const slot of ["context", "controls", "status"]) {
      expect(document.querySelector(`[data-slot="${slot}"]`)?.textContent).toBe(
        "",
      );
    }
  });

  it("mounts a route's strip claim into the sockets (the P-5 handshake)", () => {
    const entry: StripSlotsEntry = {
      Context: () => <span>Definitions</span>,
      Controls: () => <button type="button">Governance lens</button>,
      Status: () => <span>19 of 31 validated</span>,
    };
    render(renderShell(<p>Content</p>, { [SHELL_STRIP_META_KEY]: entry }));
    expect(document.querySelector('[data-slot="context"]')?.textContent).toBe(
      "Definitions",
    );
    expect(
      screen.getByRole("button", { name: "Governance lens" }),
    ).toBeInTheDocument();
    expect(document.querySelector('[data-slot="status"]')?.textContent).toBe(
      "19 of 31 validated",
    );
  });
});
