// Generated by @canonical/summon-component:react v0.1.0

import { route } from "@canonical/router-core";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { withRouter } from "../../../.storybook/decorators/index.js";
import Shell from "./Shell.js";

/** Name-compatible bare routes so the rail's links resolve without
 * mounting the app's real pages (whose wrapper would nest a Shell). */
const bareRoutes = {
  home: route({ url: "/", content: () => null }),
  components: route({ url: "/components", content: () => null }),
  definitions: route({ url: "/definitions", content: () => null }),
  standards: route({ url: "/standards", content: () => null }),
  guides: route({ url: "/guides", content: () => null }),
  playground: route({ url: "/playground", content: () => null }),
  account: route({ url: "/account", content: () => null }),
} as const;

const meta: Meta<typeof Shell> = {
  title: "Shell/Shell",
  component: Shell,
  tags: ["autodocs"],
  decorators: [withRouter({ routes: bareRoutes })],
  parameters: { layout: "fullscreen" },
};

export default meta;
type Story = StoryObj<typeof Shell>;

/** The whole frame: rail west, strip/canvas/footer east. The canvas holds
 * whatever the active lens composes — here, placeholder prose. */
export const Frame: Story = {
  args: {
    children: (
      <section>
        <h1>The canvas plate</h1>
        <p>
          Everything around this section is the stationary frame; a lens switch
          repaints only this plate.
        </p>
      </section>
    ),
  },
};

/** The underground surface hook (AX.3): a well sunk below the sheet,
 * where P-5's graph canvases will live. */
export const UndergroundWell: Story = {
  args: {
    children: (
      <section>
        <h1>Underground</h1>
        <div
          className="underground"
          style={{ blockSize: "16rem", display: "grid", placeItems: "center" }}
        >
          <p>A graph well sinks here (P-5).</p>
        </div>
      </section>
    ),
  },
};
