// Generated by @canonical/summon-component:react v0.1.0

import type { ComponentType, HTMLAttributes, ReactNode } from "react";

export interface ShellProps extends HTMLAttributes<HTMLDivElement> {
  /** The active lens's content, mounted into the canvas region. */
  children?: ReactNode;
}

/**
 * The mode strip's socket claims — the P-5 handshake.
 *
 * A composed layout claims the strip's sockets by parking this entry on its
 * route's `meta` under {@link SHELL_STRIP_META_KEY}. Route `meta` is static
 * per route and never serialised, so the claim renders identically on the
 * server and the client — the identical-tree invariant holds by construction.
 *
 * All members optional: a mode that declares nothing gets the empty sockets
 * (the strip band itself is stationary frame and never comes or goes —
 * AX.6). `Controls` and `Status` are component types, not elements, so the
 * entry stays plain data on the route table and mounts fresh per render.
 */
export interface StripSlotsEntry {
  /**
   * The mode's context region (`slot.*-context`), the strip's west slot: a
   * component rendering the breadcrumb trail to the current page. P-6 moved
   * the page title out of the canvas and into this socket as the DS
   * Breadcrumbs pattern, so the context is a COMPONENT now (mirroring
   * `Controls`/`Status`), not a static string — the trail's terminal crumb
   * is the route param, which only a component reading the route can build.
   * It reads no query and derives everything from the URL, so it never
   * suspends the frame and renders identically on the server and client.
   */
  readonly Context?: ComponentType;
  /** The composed layout's controls region (`slot.*-controls`). */
  readonly Controls?: ComponentType;
  /** The composed layout's status region (`slot.*-status`). */
  readonly Status?: ComponentType;
}
