/**
 * Fields every navigation item carries, independent of its identity.
 * Composed into `Item` alongside `ItemIdentity`.
 */
interface ItemFields {
  /**
   * Display text for the item in the navigation UI.
   * e.g. 'Dashboard' as the visible label.
   */
  label?: string;

  /**
   * Flag indicating whether the item is interactive or disabled.
   * e.g. true to prevent clicks on unavailable features.
   */
  disabled?: boolean;

  /**
   * Flag marking a node that exists to structure or decorate the list rather
   * than to be chosen — a separator, a group heading, a spacer.
   * e.g. true on the rule drawn between two groups of menu items.
   *
   * This is not a stronger `disabled`. `disabled` says "an item you may not
   * choose right now"; `presentational` says "not an item", which makes
   * `disabled` meaningless rather than false. Keyboard navigation skips both,
   * but only `presentational` nodes are absent from the count a user perceives.
   */
  presentational?: boolean;

  /**
   * Array of child items for nested navigation structures.
   * e.g. Submenu items under a parent like 'Settings'.
   */
  items?: Item[];
}

/**
 * The identity of a navigation item - Public API (WD405)
 *
 * Every item must be addressable: the shared navigation utilities index a tree
 * by item id, so an item with no identity has no place in that index. One of
 * `url` or `key` is therefore required — either, or both — and the requirement
 * is carried by the type instead of being checked at runtime.
 *
 * `url` wins when both are present, so the union discriminates on it: the
 * `key`-only arm states `url?: undefined`, which is what lets a check on `url`
 * prove that `key` is there.
 */
type ItemIdentity =
  | {
      /**
       * Unique identifier for the item, required when no URL is provided.
       * Unique within the whole tree; a collision leaves only the later
       * item in the index (warned in development).
       * This is the answer for a non-navigable node,
       * e.g. 'section-header' for a grouping item.
       */
      key: string;

      /** Absent — an item without a URL is identified by its `key`. */
      url?: undefined;
    }
  | {
      /**
       * Unique identifier for the item, optional alongside a URL.
       * `url` takes precedence over it when both are present.
       */
      key?: string;

      /**
       * Navigation URL for the item, used for navigable links.
       * e.g. '/dashboard' for directing to the dashboard page.
       * Doubles as the item's identity, taking precedence over `key`.
       * Unique within the whole tree; a collision leaves only the later
       * item in the index (warned in development).
       */
      url: string;
    };

/**
 * Navigation item - Public API (WD405)
 *
 * A unified type for navigation items across the design system.
 * Used by Breadcrumbs, SiteNavigation, FileTree, MegaMenu, etc.
 *
 * Only fields consumed by the shared navigation utilities belong here.
 * Styling and rendering customization (CSS classes, custom renderers)
 * belong on the item types that components declare by composing this
 * one (e.g. BreadcrumbItem, MenuItem), using each framework's own idioms.
 *
 * The identity requirement makes `Item` a union, so compose it with `&`
 * rather than `interface … extends` (which cannot extend a union), and drop
 * fields from it with `_DistributiveOmit` rather than `Omit`.
 */
export type Item = ItemFields & ItemIdentity;

/** Type-level assertion: fails to compile unless `T` resolves to `true`. */
type Assert<T extends true> = T;

/**
 * Compile-time proof of the identity requirement: an object carrying neither a
 * `key` nor a `url` is not an `Item`. That is what lets `getItemId` be total,
 * so it is asserted where the type is declared rather than left to a runtime
 * check downstream.
 */
type _IdentityIsRequired = Assert<
  { label: string } extends Item ? false : true
>;

/**
 * Annotated navigation item - Private API (WD405)
 *
 * Internal type with parent reference and depth annotations.
 * Generated by annotateTree() helper.
 *
 * Generic over the **whole item type** `T` it annotates, so an enhanced item
 * (extra fields beyond the base WD405 `Item`, e.g. `icon`/`slot`) survives
 * annotation with its fields intact and fully typed.
 *
 * Distributes over union item types: `_Item<A | B>` annotates each member
 * separately (`_Item<A> | _Item<B>`-shaped), so a discriminated union of entry
 * kinds (e.g. a menu item vs a separator) keeps its discriminant and
 * member-specific fields after annotation. A plain `Omit<A | B, "items">`
 * would collapse the union to its common keys. Children remain the **whole**
 * union: a tree of `A | B` entries has `_Item<A | B>[]` children on every
 * member, whichever member the parent is.
 *
 * Instantiate `_Item` with the tree's FULL entry union: `_Item<OneMember>`
 * re-types `items` with just that member, statically hiding the other entry
 * kinds a heterogeneous tree's children can hold at runtime.
 *
 * @template T - The item type being annotated (defaults to the base `Item`)
 */
export type _Item<T extends Item = Item> = _DistributiveOmit<T, "items"> & {
  /**
   * URL (or key) of the parent item in the navigation hierarchy.
   * e.g. '/parent' for a child item under '/parent', or null for the root.
   */
  parentUrl: string | null;

  /**
   * Integer representing the nesting level in the tree.
   * e.g. 0 for top-level items, 1 for their children, 2 for grandchildren.
   */
  depth: number;

  /**
   * Array of annotated child items, if any.
   * e.g. Prepared sub-items with their own parentUrl and depth.
   *
   * `T`'s own `items` is omitted before intersecting so this annotated form
   * (`_Item<T>[]`) is the one surfaced when iterating children — otherwise the
   * intersection would expose `T`'s base element type. `T` here is the whole
   * (possibly union) entry type, so children stay heterogeneous regardless of
   * which member the parent is.
   */
  items?: _Item<T>[];
};

/**
 * A distributing `Omit` - Private API (WD405)
 *
 * An `Omit` that distributes over union types: `_DistributiveOmit<A | B, K>`
 * is `Omit<A, K> | Omit<B, K>`, where the plain `Omit<A | B, K>` would first
 * collapse the union to its common keys. `Item` is itself a union — its
 * identity requirement is one — so dropping a field from it (a flat trail with
 * no `items`, say) needs this rather than `Omit`, which would quietly make
 * both `key` and `url` optional again. Intersecting the annotation fields
 * with the distributed union then distributes too, keeping `_Item<A | B>`
 * member-shaped. The conditional is only on the `Omit` half — the annotation
 * fields above stay a concrete object type, so generic code can access
 * `parentUrl`/`depth`/`items` without resolving the conditional.
 *
 * Exported, but private in the same sense as `_Item` and `_Index`: it is for
 * code that DEFINES an item type, not for code that passes items around. An
 * application composing its own item adds fields with `&` and needs nothing
 * from here; it is the packages declaring `BreadcrumbItem`, `TabItem` and the
 * rest that must drop a field from a union, and they live behind this same
 * `_` convention.
 */
export type _DistributiveOmit<T, K extends PropertyKey> = T extends unknown
  ? Omit<T, K>
  : never;

/**
 * Index for quick lookup of items by URL or key - Private API (WD405)
 *
 * A dictionary for O(1) lookup of prepared items.
 *
 * @template T - The item type being annotated (defaults to the base `Item`)
 */
export type _Index<T extends Item = Item> = {
  [url: string]: _Item<T>;
};
