// Generated by @canonical/summon-component:react v0.1.0

import type { GridPreset } from "@canonical/ds-types";
import type { ComponentProps, ReactNode } from "react";

/**
 * The grid preset laying out the content items — `GridPreset` from
 * \@canonical/ds-types, rendered by the `.grid` presets in
 * \@canonical/styles: `responsive` (fixed-responsive, breakpoint-driven
 * 4/8/16 columns) or `intrinsic` (fluid auto-fill groups of four
 * `minmax(--grid-col-min, 1fr)` columns).
 */
export type ContentLayoutGrid = GridPreset;

type OwnProps = {
  /** Content items (default slot) — direct grid items. */
  children?: ReactNode;
  /** Grid preset. Defaults to `responsive` (fixed-responsive). */
  grid?: ContentLayoutGrid;
};

export type ContentLayoutProps = OwnProps &
  Omit<ComponentProps<"div">, keyof OwnProps>;
