// Generated by @canonical/summon-component:react v0.1.0

// The sub-domain's own surface, beside the components above.
export { default as standardsRoutes } from "./routes.js";
export * from "./StandardArticle/index.js";
export * from "./StandardReadingPage/index.js";
export * from "./StandardsIndex/index.js";
export * from "./StandardsPage/index.js";
export {
  STANDARDS_PAGE_SIZE,
  standardsIndexQueryNode,
  standardsIndexRouteEntry,
  standardsIndexVariables,
} from "./standardsIndexQuery.js";
