// Generated by @canonical/summon-component:react v0.1.0

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import Content from "./Content.js";

describe("Content", () => {
  it("applies custom className", () => {
    render(<Content className="custom-class" />);
    const element = screen.getByRole("navigation");
    expect(element.className).toContain("ds content");
    expect(element.className).toContain("custom-class");
  });

  it("passes through additional props", () => {
    render(<Content data-testid="test-component" />);
    expect(screen.getByTestId("test-component")).toBeInTheDocument();
  });

  it("renders an empty landmark with no root (the landmark contract stays stable)", () => {
    render(<Content />);
    const nav = screen.getByRole("navigation");
    expect(nav).toBeInTheDocument();
    expect(nav).toBeEmptyDOMElement();
  });
});
