// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import * as decorators from "storybook/decorators.js";
import { PasswordInput } from "./PasswordInput.js";

const meta: Meta<typeof PasswordInput> = {
  title: "subcomponents/PasswordInput",
  component: PasswordInput,
};

export default meta;
type Story = StoryObj<typeof PasswordInput>;

export const Default: Story = {
  args: { name: "password", defaultValue: "hunter2" },
};

export const NotRevealable: Story = {
  args: { name: "password", defaultValue: "hunter2", revealable: false },
};

export const Disabled: Story = {
  args: { name: "password", defaultValue: "hunter2", disabled: true },
};

/**
 * Presentational error state: the bare input wrapped in the field `.danger`
 * context (the visual layer the Wrapper applies on a real validation error).
 * For the react-hook-form-driven error see PasswordField's `WithError`.
 */
export const ErrorState: Story = {
  decorators: [decorators.danger()],
  args: { name: "password" },
};
