// Generated by @canonical/summon-component:react v0.1.0

import type { ComponentProps } from "react";

type OwnProps = {
  /** Whether the reveal/mask (eye) toggle is offered. Defaults to `true`. */
  revealable?: boolean;

  /** Accessible label for the toggle while the value is masked. */
  revealLabel?: string;

  /** Accessible label for the toggle while the value is revealed. */
  maskLabel?: string;
};

/**
 * Props for the presentational Password input (no react-hook-form).
 *
 * The rendered root is a presentational `<div class="ds input password chrome">`
 * that positions the reveal toggle; the component's native props are the inner
 * `<input>`'s — the labelable, registered control every attribute is spread
 * onto. `className` and `style` are applied to the chrome wrapper, `id` to the
 * control so the field label's `htmlFor` targets a labelable element.
 *
 * `type` is omitted: it is driven by the reveal toggle (`password`/`text`).
 * `prefix` is omitted: the password input has no prefix slot.
 */
export type PasswordInputProps = OwnProps &
  Omit<ComponentProps<"input">, keyof OwnProps | "type" | "prefix">;
