// AUTO-GENERATED by scripts/build.ts — do not edit by hand.
// Regenerate: `bun run scripts/build.ts`. The serializable projection of
// every declared generator binding (`projectGenerator` over the live
// generators, captured at build time): the create surface's params, the CLI
// mount, completion, and the MCP schemas all derive from THIS data, so the
// `--help`/`__complete` fast path never imports a generator. The
// projection-fidelity test in create.test.ts loads the LIVE generators and
// fails when this file drifts; rerunning the build fixes it.

import type { SurfaceCommand } from "@canonical/summon-core/projection";
import type { PromptCliSyntax } from "./types.js";

/** Declared command path → its projected command surface. */
export const CREATE_SURFACE: Readonly<Record<string, SurfaceCommand>> = {
  "application/react": {
    "path": [
      "application",
      "react"
    ],
    "description": "Scaffold a complete React application with routing, and either server-side rendering or a client-only SPA",
    "prompts": [
      {
        "name": "appPath",
        "type": "text",
        "message": "Application directory name:",
        "default": "my-app",
        "positional": true,
        "group": "Application"
      },
      {
        "name": "forms",
        "type": "confirm",
        "message": "Include form components?",
        "default": true,
        "group": "Application"
      },
      {
        "name": "intl",
        "type": "confirm",
        "message": "Include internationalisation (locale negotiation, translated UI, locale switcher)?",
        "default": false,
        "group": "Application"
      },
      {
        "name": "rendering",
        "type": "select",
        "message": "Rendering — ssr keeps the server layer (SSR servers and sitemap), spa is client-only",
        "default": "ssr",
        "choices": [
          {
            "label": "ssr - server-side rendering (Express + Bun servers, sitemap)",
            "value": "ssr"
          },
          {
            "label": "spa - client-only single-page app (no server layer)",
            "value": "spa"
          }
        ],
        "group": "Application"
      },
      {
        "name": "relay",
        "type": "confirm",
        "message": "Include a Relay (GraphQL) data layer with a local mock schema?",
        "default": false,
        "group": "Application"
      },
      {
        "name": "runInstall",
        "type": "confirm",
        "message": "Install dependencies now?",
        "default": true,
        "group": "Application"
      }
    ]
  },
  "component/lit": {
    "path": [
      "component",
      "lit"
    ],
    "description": "Generate a Lit web component with TypeScript, tests, stories, and styles",
    "prompts": [
      {
        "name": "componentPath",
        "type": "text",
        "message": "Component path:",
        "default": "src/lib/components/MyComponent",
        "positional": true,
        "group": "Component"
      },
      {
        "name": "withStyles",
        "type": "confirm",
        "message": "Include styles?",
        "default": true,
        "group": "Options"
      },
      {
        "name": "withStories",
        "type": "confirm",
        "message": "Include Storybook stories?",
        "default": true,
        "group": "Options"
      }
    ]
  },
  "component/react": {
    "path": [
      "component",
      "react"
    ],
    "description": "Generate a React component with TypeScript, tests, stories, and styles",
    "prompts": [
      {
        "name": "componentPath",
        "type": "text",
        "message": "Component path:",
        "default": "src/components/MyComponent",
        "positional": true,
        "group": "Component"
      },
      {
        "name": "withStyles",
        "type": "confirm",
        "message": "Include styles?",
        "default": true,
        "group": "Options"
      },
      {
        "name": "withStories",
        "type": "confirm",
        "message": "Include Storybook stories?",
        "default": true,
        "group": "Options"
      },
      {
        "name": "withSsrTests",
        "type": "confirm",
        "message": "Include SSR tests?",
        "default": true,
        "group": "Options"
      }
    ]
  },
  "component/svelte": {
    "path": [
      "component",
      "svelte"
    ],
    "description": "Generate a Svelte 5 component with TypeScript, tests, stories, and styles",
    "prompts": [
      {
        "name": "componentPath",
        "type": "text",
        "message": "Component path:",
        "default": "src/lib/components/MyComponent",
        "positional": true,
        "group": "Component"
      },
      {
        "name": "withStyles",
        "type": "confirm",
        "message": "Include styles?",
        "default": true,
        "group": "Options"
      },
      {
        "name": "withStories",
        "type": "confirm",
        "message": "Include Storybook stories?",
        "default": true,
        "group": "Options"
      },
      {
        "name": "withSsrTests",
        "type": "confirm",
        "message": "Include SSR tests?",
        "default": true,
        "group": "Options"
      },
      {
        "name": "useTsStories",
        "type": "confirm",
        "message": "Use TypeScript stories format? (otherwise Svelte CSF)",
        "default": false,
        "group": "Options",
        "conditional": true
      }
    ]
  },
  "package": {
    "path": [
      "package"
    ],
    "description": "Generate a new npm package with proper configuration for the pragma monorepo",
    "prompts": [
      {
        "name": "name",
        "type": "text",
        "message": "Package name:",
        "default": "@canonical/my-package",
        "group": "Package"
      },
      {
        "name": "type",
        "type": "select",
        "message": "Package type:",
        "default": "tool-ts",
        "choices": [
          {
            "label": "tool-ts - TypeScript tool (runs from src/, no build)",
            "value": "tool-ts"
          },
          {
            "label": "library - Publishable library (dist/ build output)",
            "value": "library"
          },
          {
            "label": "css - CSS package (src/index.css, no build)",
            "value": "css"
          }
        ],
        "group": "Package"
      },
      {
        "name": "description",
        "type": "text",
        "message": "Package description:",
        "default": "",
        "group": "Package"
      },
      {
        "name": "withReact",
        "type": "confirm",
        "message": "Include React dependencies?",
        "default": false,
        "group": "Options"
      },
      {
        "name": "withStorybook",
        "type": "confirm",
        "message": "Include Storybook setup?",
        "default": false,
        "group": "Options"
      },
      {
        "name": "withCli",
        "type": "confirm",
        "message": "Include CLI binary entry point?",
        "default": false,
        "group": "Options"
      },
      {
        "name": "withPrTemplate",
        "type": "confirm",
        "message": "Include a .github/PULL_REQUEST_TEMPLATE.md?",
        "default": false,
        "group": "Options"
      },
      {
        "name": "runInstall",
        "type": "confirm",
        "message": "Run package manager install after creation?",
        "default": true,
        "group": "Post-setup"
      }
    ]
  },
  "page": {
    "path": [
      "page"
    ],
    "description": "Add a page component to an existing domain",
    "prompts": [
      {
        "name": "pagePath",
        "type": "text",
        "message": "Page path, as <domain>/<name> (for example invoices/detail):",
        "positional": true,
        "group": "Page"
      }
    ]
  },
};

/**
 * Declared command path → prompt name → the REGISTERED CLI spelling
 * (`buildOptionInfo`/`toKebabCase` over the projected prompts, captured at
 * build time). Completion and the reference emitter read THIS record, so the
 * `--help`/`__complete` fast paths never import the registration machinery
 * to learn a token it already decided.
 */
export const CREATE_CLI_SYNTAX: Readonly<
  Record<string, Readonly<Record<string, PromptCliSyntax>>>
> = {
  "application/react": {
    "appPath": {
      "flag": "--app-path",
      "takesValue": true,
      "kebabName": "app-path"
    },
    "forms": {
      "flag": "--no-forms",
      "takesValue": false,
      "kebabName": "forms"
    },
    "intl": {
      "flag": "--intl",
      "takesValue": false,
      "kebabName": "intl"
    },
    "rendering": {
      "flag": "--rendering",
      "takesValue": true,
      "kebabName": "rendering"
    },
    "relay": {
      "flag": "--relay",
      "takesValue": false,
      "kebabName": "relay"
    },
    "runInstall": {
      "flag": "--no-run-install",
      "takesValue": false,
      "kebabName": "run-install"
    }
  },
  "component/lit": {
    "componentPath": {
      "flag": "--component-path",
      "takesValue": true,
      "kebabName": "component-path"
    },
    "withStyles": {
      "flag": "--no-with-styles",
      "takesValue": false,
      "kebabName": "with-styles"
    },
    "withStories": {
      "flag": "--no-with-stories",
      "takesValue": false,
      "kebabName": "with-stories"
    }
  },
  "component/react": {
    "componentPath": {
      "flag": "--component-path",
      "takesValue": true,
      "kebabName": "component-path"
    },
    "withStyles": {
      "flag": "--no-with-styles",
      "takesValue": false,
      "kebabName": "with-styles"
    },
    "withStories": {
      "flag": "--no-with-stories",
      "takesValue": false,
      "kebabName": "with-stories"
    },
    "withSsrTests": {
      "flag": "--no-with-ssr-tests",
      "takesValue": false,
      "kebabName": "with-ssr-tests"
    }
  },
  "component/svelte": {
    "componentPath": {
      "flag": "--component-path",
      "takesValue": true,
      "kebabName": "component-path"
    },
    "withStyles": {
      "flag": "--no-with-styles",
      "takesValue": false,
      "kebabName": "with-styles"
    },
    "withStories": {
      "flag": "--no-with-stories",
      "takesValue": false,
      "kebabName": "with-stories"
    },
    "withSsrTests": {
      "flag": "--no-with-ssr-tests",
      "takesValue": false,
      "kebabName": "with-ssr-tests"
    },
    "useTsStories": {
      "flag": "--use-ts-stories",
      "takesValue": false,
      "kebabName": "use-ts-stories"
    }
  },
  "package": {
    "name": {
      "flag": "--name",
      "takesValue": true,
      "kebabName": "name"
    },
    "type": {
      "flag": "--type",
      "takesValue": true,
      "kebabName": "type"
    },
    "description": {
      "flag": "--description",
      "takesValue": true,
      "kebabName": "description"
    },
    "withReact": {
      "flag": "--with-react",
      "takesValue": false,
      "kebabName": "with-react"
    },
    "withStorybook": {
      "flag": "--with-storybook",
      "takesValue": false,
      "kebabName": "with-storybook"
    },
    "withCli": {
      "flag": "--with-cli",
      "takesValue": false,
      "kebabName": "with-cli"
    },
    "withPrTemplate": {
      "flag": "--with-pr-template",
      "takesValue": false,
      "kebabName": "with-pr-template"
    },
    "runInstall": {
      "flag": "--no-run-install",
      "takesValue": false,
      "kebabName": "run-install"
    }
  },
  "page": {
    "pagePath": {
      "flag": "--page-path",
      "takesValue": true,
      "kebabName": "page-path"
    }
  },
};
