// Generated by @canonical/summon-component:react v0.1.0

import type React from "react";
import { CollapseToggle } from "../CollapseToggle/index.js";
import type { HeaderProps } from "./types.js";
import "./styles.css";

const componentCssClassName = "ds side-navigation-header";

/**
 * SideNavigation.Header — top region holding the brand (the `brand` node, at the
 * start) and the collapse toggle (at the end). The toggle is omitted when no
 * `onToggle` handler is provided. Collapsed (the 24.04 spec §1.2): the layout
 * switches to a centred column — the toggle relocates below the logo rather
 * than beside it — driven by `data-expanded` on the root.
 *
 * @implements ds:apps.subcomponent.side-navigation-header
 */
const Header = ({
  className,
  brand,
  applicationName,
  expanded,
  onToggle,
  collapseControls,
  ...props
}: HeaderProps): React.ReactElement => {
  return (
    <header
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      data-expanded={expanded}
      {...props}
    >
      <div className="brand-container">
        <div className="brand">{brand}</div>
        {/* Optional, consumer-supplied; the grid's middle column is empty
        without it. Hidden when collapsed — the spec's collapsed header has
        no title. */}
        {applicationName != null && (
          <h1 className="title">{applicationName}</h1>
        )}
      </div>
      {onToggle && (
        <CollapseToggle
          expanded={expanded}
          aria-controls={collapseControls}
          onClick={onToggle}
        />
      )}
    </header>
  );
};

export default Header;
