// Generated by @canonical/summon:component-svelte v0.1.0

import type { Locator } from "@vitest/browser/context";
import type { ComponentProps, Snippet } from "svelte";
import { createRawSnippet } from "svelte";
import { describe, expect, it, vi } from "vitest";
import type { RenderResult } from "vitest-browser-svelte";
import { render } from "vitest-browser-svelte";
import Component from "./Chip.svelte";

describe("Chip component", () => {
  const baseProps = {
    value: "Chip",
    "data-testid": "chip",
  } satisfies ComponentProps<typeof Component>;

  it("renders", async () => {
    const page = await render(Component, { ...baseProps });
    await expect.element(componentLocator(page)).toBeInTheDocument();
  });

  describe("attributes", () => {
    it.each([
      ["id", "test-id"],
      ["aria-label", "test-aria-label"],
    ])("applies %s", async (attribute, expected) => {
      const page = await render(Component, {
        ...baseProps,
        [attribute]: expected,
      });
      await expect
        .element(componentLocator(page))
        .toHaveAttribute(attribute, expected);
    });

    it("applies classes", async () => {
      const page = await render(Component, {
        ...baseProps,
        class: "test-class",
      });
      await expect.element(componentLocator(page)).toHaveClass("test-class");
      await expect.element(componentLocator(page)).toHaveClass("ds");
      await expect.element(componentLocator(page)).toHaveClass("chip");
    });

    it("applies style", async () => {
      const page = await render(Component, {
        ...baseProps,
        style: "color: orange;",
      });
      await expect
        .element(componentLocator(page))
        .toHaveStyle({ color: "orange" });
    });
  });

  describe("Initial Rendering", () => {
    it("should render with default props as a non-interactive element", async () => {
      const page = await render(Component, {
        ...baseProps,
        value: "Default Chip",
      });

      await expect.element(page.getByRole("button")).not.toBeInTheDocument();
    });

    it("should render with a lead element", async () => {
      const page = await render(Component, {
        ...baseProps,
        lead: "Key",
        value: "Value",
      });

      await expect.element(page.getByText("Key")).toBeInTheDocument();
      await expect.element(page.getByText("Value")).toBeInTheDocument();
    });

    it("should render with an icon", async () => {
      const icon: Snippet = createRawSnippet(() => ({
        render: () => `<div data-testid="custom-icon"></div>`,
      }));
      const page = await render(Component, {
        ...baseProps,
        value: "Icon Chip",
        icon,
      });

      await expect.element(page.getByTestId("custom-icon")).toBeInTheDocument();
    });

    it("should apply custom class and modifiers", async () => {
      const page = await render(Component, {
        ...baseProps,
        value: "Styled Chip",
        class: "extra-class",
        criticality: "warning",
      });

      await expect.element(componentLocator(page)).toHaveClass("extra-class");
      await expect.element(componentLocator(page)).toHaveClass("warning");
    });

    it("should not render a button when dismiss is provided", async () => {
      const page = await render(Component, {
        ...baseProps,
        value: "Dismissible",
        ondismiss: () => {},
      });

      await expect
        .element(componentLocator(page))
        .not.toHaveAttribute("type", "button");
      await expect
        .element(page.getByRole("button"))
        .toHaveAccessibleName("Dismiss");
    });

    it("should not render a button when readonly is provided", async () => {
      const page = await render(Component, {
        ...baseProps,
        value: "Readonly",
        readonly: true,
        onclick: () => {},
      });

      await expect.element(componentLocator(page)).toBeInTheDocument();
      await expect.element(page.getByRole("button")).not.toBeInTheDocument();
    });
  });

  describe("Interactions & States", () => {
    it("should render a working button when onclick is provided", async () => {
      const onclick = vi.fn();
      const page = await render(Component, {
        ...baseProps,
        value: "Clickable",
        onclick,
      });

      const element = page.getByRole("button");
      await expect.element(element).toBeInTheDocument();
      await element.click();
      expect(onclick).toHaveBeenCalled();
    });

    it("should render a working dismiss button when ondismiss is provided", async () => {
      const ondismiss = vi.fn();
      const page = await render(Component, {
        ...baseProps,
        value: "Dismissible",
        ondismiss,
      });

      const dissmissButton = page.getByLabelText("Dismiss");
      await expect.element(dissmissButton).toBeInTheDocument();

      await expect.element(dissmissButton).toBeInTheDocument();
      await dissmissButton.click();
      expect(ondismiss).toHaveBeenCalled();
    });
  });
});

function componentLocator(page: RenderResult<typeof Component>): Locator {
  return page.getByTestId("chip");
}
