// Generated by @canonical/summon-component:react v0.1.0

import { RouterProvider } from "@canonical/router-react";
import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { appRoutes, notFoundRoute } from "../../routes.js";
import createStaticRouter from "../router/createStaticRouter.js";
import Rail from "./Rail.js";

const renderRailHtml = (url: string): string =>
  renderToString(
    <RouterProvider
      router={createStaticRouter(appRoutes, url, { notFound: notFoundRoute })}
    >
      <Rail />
    </RouterProvider>,
  );

describe("Rail SSR", () => {
  it("server-renders the full rail with the active lens marked", () => {
    const html = renderRailHtml("/definitions");
    expect(html).toContain("ds rail");
    expect(html).toContain('aria-label="Primary"');
    // The active entry carries the router's aria-current on the server too.
    expect(html).toContain('aria-current="page"');
    expect(html).toContain('href="/definitions"');
    // Displayed hints survive SSR (they are markup, not effects).
    expect(html).toContain("aria-keyshortcuts=");
  });
});
