// Generated by @canonical/summon-component:react v0.1.0

import { Link } from "@canonical/router-react";
import type React from "react";
import ThemeSelector from "#lib/ThemeSelector";
import { LENS_ENTRIES } from "./constants.js";
import { LENS_ICONS, PlaygroundIcon, SignInIcon } from "./icons.js";
import type { RailProps } from "./types.js";
import { useLensShortcuts } from "./useLensShortcuts.js";
import "./styles.css";

const componentCssClassName = "ds rail";

/**
 * The primary rail — the shell's west column and only global region
 * (AX.2, `slot.shell-nav`). Anatomy per A.06 §3, top to bottom: brand
 * (dot + wordmark → Home, the star-topology hub) · the lens entries
 * (icon + label + displayed keyboard hint) · spacer · the utility
 * cluster (the non-lenses, kept out of the switcher).
 *
 * Navigation is the classic model (P-D17 deferred): one flat rank of
 * lenses here, per-layout secondary nav inside the modes — no two-level
 * tree. Active state is the router's own `aria-current="page"` (exact
 * pathname match), styled from the attribute; the rail carries no other
 * route-dependent markup, which is what keeps the frame byte-identical
 * across lens switches (`frameStability.tests.tsx`).
 *
 * The digit hints are wired for real (`useLensShortcuts`, an ephemeral
 * listener honouring P-D7) and displayed as `kbd` + `aria-keyshortcuts`.
 * The digit itself is read from the route's own allocation: the rail
 * DISPLAYS it, it does not own it — so a lens that allocates no key simply
 * renders no `kbd`, and the shown digit is the wired digit by construction.
 */
const Rail = ({ className, ...props }: RailProps): React.ReactElement => {
  const { byRoute } = useLensShortcuts();

  return (
    <nav
      aria-label="Primary"
      className={[componentCssClassName, className].filter(Boolean).join(" ")}
      data-region="primary-nav"
      {...props}
    >
      <Link className="rail-brand" to="home">
        <span aria-hidden="true" className="rail-brand-dot" />
        <span className="rail-brand-word">
          Pragma
          <small>design system docs</small>
        </span>
      </Link>

      <ul className="rail-lenses">
        {LENS_ENTRIES.map(({ to, label }) => {
          const Icon = LENS_ICONS[to];
          const hint = byRoute.get(to);
          return (
            <li key={to}>
              {/* aria-label pins the accessible name to the lens name alone:
                  the displayed kbd digit stays out of it (the shortcut
                  reaches AT through aria-keyshortcuts instead). title gives
                  the collapsed icon-only entry a pointer-hover affordance —
                  identical on every lens, so the frame stays byte-stable. */}
              <Link
                aria-keyshortcuts={hint}
                aria-label={label}
                className="rail-item"
                title={label}
                to={to}
              >
                <Icon />
                <span className="rail-label">{label}</span>
                {hint === undefined ? null : (
                  <kbd className="rail-kbd">{hint}</kbd>
                )}
              </Link>
            </li>
          );
        })}
      </ul>

      <div aria-hidden="true" className="rail-spacer" />

      <p className="rail-util-label" id="rail-utilities-label">
        Utilities
      </p>
      <ul aria-labelledby="rail-utilities-label" className="rail-utilities">
        <li>
          {/* The SSR-certified demo canvas keeps a door (P-4.1 brief). */}
          <Link
            className="rail-item rail-util"
            title="Playground"
            to="playground"
          >
            <PlaygroundIcon />
            <span className="rail-label">Playground</span>
          </Link>
        </li>
        <li>
          <Link
            className="rail-item rail-util"
            search={{ auth: "1" }}
            title="Demo sign-in"
            to="account"
          >
            <SignInIcon />
            <span className="rail-label">Demo sign-in</span>
          </Link>
        </li>
        <li className="rail-theme">
          {/* Chrome preference — cookie-backed via usePreferredTheme (P-D7). */}
          <ThemeSelector />
        </li>
      </ul>
    </nav>
  );
};

export default Rail;
