// Generated by @canonical/summon-application:application/react v0.1.0

import type { SitemapItem } from "@canonical/react-ssr/renderer";

/**
 * Returns sitemap entries for all known routes.
 *
 * Update this list as you add domains and routes. For dynamic content
 * (blog posts, product pages), fetch entries from your data source.
 *
 * @example
 * const posts = await fetchPosts();
 * return [
 *   ...staticEntries,
 *   ...posts.map((post) => ({
 *     loc: `/blog/${post.slug}`,
 *     lastmod: post.updatedAt,
 *     changefreq: "weekly" as const,
 *     priority: 0.7,
 *   })),
 * ];
 */
export default async function getSitemapItems(): Promise<SitemapItem[]> {
  return [
    { loc: "/", changefreq: "weekly", priority: 1.0 },
    // The v1 lens routes (P-4.1). "/catalog" was boilerplate with no route
    // behind it; the real lens URLs replace it.
    { loc: "/components", changefreq: "weekly", priority: 0.8 },
    { loc: "/definitions", changefreq: "weekly", priority: 0.8 },
    { loc: "/standards", changefreq: "weekly", priority: 0.8 },
    { loc: "/journeys", changefreq: "weekly", priority: 0.8 },
    { loc: "/guides", changefreq: "weekly", priority: 0.8 },
    { loc: "/guides/router-core", changefreq: "monthly", priority: 0.7 },
    { loc: "/account", changefreq: "monthly", priority: 0.5 },
    { loc: "/login", changefreq: "yearly", priority: 0.3 },
  ];
}
