/**
 * A serialised Relay store snapshot for `DefinitionsExplorerQuery` at
 * { uri: "ds:Component", hasTerm: true } — captured VERBATIM from a dev
 * server's `__INITIAL_DATA__.relay.records` at /definitions/ds%3AComponent
 * (the output of the prepare step's `getStore().getSource().toJSON()`).
 * The instance-bearing twin of `definitionsExplorerRecords`.
 *
 * HAND-TRANSFORMED, NOT RE-CAPTURED (the converged-base migration). A
 * re-capture in an environment without the semantics tree would silently
 * drop the `surface` ontology — 31 of the 60 classes — so this file was
 * migrated from its previous capture by the base's own three rules:
 * records re-keyed by `uri` (what `getDataID` now returns), the deleted
 * `id` field dropped, and `_meta { curie }` attached. The transform is
 * VALIDATED, not assumed: applied to the three ontologies a live boot does
 * serve, it reproduces the booted graph's own records exactly — 125
 * records compared, zero structural differences, the only diffs being
 * `instanceCount` drift (ds:Component 111 -> 109, the documented lesson).
 * The `surface` records ride the same proven rule but are UNVERIFIED
 * against a live graph; re-capture on a machine with the semantics tree.
 *
 * CORRECTED after that transform: the 12 `Component` ABox records were
 * missed by rule 1 and kept the pre-migration compact form as both their
 * store key and their `uri`. That was not a harmless cosmetic — it was the
 * one thing keeping the inspector's D31 href assertion green while the
 * shipped lens minted a DIFFERENT address, because a fixture that disagrees
 * with the graph tests the fixture. They now carry the absolute IRI the
 * graph actually returns, with the compact form where the graph actually
 * puts it (`_meta.curie`, now that the fragment selects it). The ONLY
 * compact strings left are the root query-field keys — those are the route
 * ARGUMENT (`/definitions/ds%3AComponent`), not an identity, and are
 * correct as they stand.
 *
 * RESHAPED AGAIN when the inspector despecialised. The instances block
 * used to select `__typename` and `... on Entity { name }`; it now selects
 * `_meta { curie title type { uri } }`, so the 12 `EntityMeta` records
 * gained `title` (the same string `name` carried — `_meta.title` resolves
 * an entity's `ds:name` through the compiler's label tier) and `type`, a
 * link to the `ds:Component` class record that was already in this file.
 * The 12 `Component` node records lost `name` for the same reason the
 * property fixture lost its two annotation fields: nothing selects it, so
 * a re-capture would not carry it. `__typename` stays — Relay writes it on
 * every record regardless of the selection.
 *
 * Regenerate: boot `dev:bun`, copy `relay.records` out of the
 * `__INITIAL_DATA__` script served at /definitions/ds%3AComponent.
 */

import type { RecordMap } from "relay-runtime/store/RelayStoreTypes.js";

const definitionsExplorerRecordsComponent = {
  "client:__type:Component": {
    __id: "client:__type:Component",
    __isEntity: true,
    __typename: "__TypeSchema",
  },
  "client:https://ds.canonical.com/Component:instances(first:12)": {
    __id: "client:https://ds.canonical.com/Component:instances(first:12)",
    __typename: "NodeConnection",
    edges: {
      __refs: [
        "client:https://ds.canonical.com/Component:instances(first:12):edges:0",
        "client:https://ds.canonical.com/Component:instances(first:12):edges:1",
        "client:https://ds.canonical.com/Component:instances(first:12):edges:2",
        "client:https://ds.canonical.com/Component:instances(first:12):edges:3",
        "client:https://ds.canonical.com/Component:instances(first:12):edges:4",
        "client:https://ds.canonical.com/Component:instances(first:12):edges:5",
        "client:https://ds.canonical.com/Component:instances(first:12):edges:6",
        "client:https://ds.canonical.com/Component:instances(first:12):edges:7",
        "client:https://ds.canonical.com/Component:instances(first:12):edges:8",
        "client:https://ds.canonical.com/Component:instances(first:12):edges:9",
        "client:https://ds.canonical.com/Component:instances(first:12):edges:10",
        "client:https://ds.canonical.com/Component:instances(first:12):edges:11",
      ],
    },
    pageInfo: {
      __ref:
        "client:https://ds.canonical.com/Component:instances(first:12):pageInfo",
    },
  },
  "client:https://ds.canonical.com/Component:instances(first:12):edges:0": {
    __id: "client:https://ds.canonical.com/Component:instances(first:12):edges:0",
    __typename: "NodeEdge",
    node: {
      __ref: "https://ds.canonical.com/global.component.accordion",
    },
  },
  "client:https://ds.canonical.com/Component:instances(first:12):edges:1": {
    __id: "client:https://ds.canonical.com/Component:instances(first:12):edges:1",
    __typename: "NodeEdge",
    node: {
      __ref: "https://ds.canonical.com/global.component.announcement",
    },
  },
  "client:https://ds.canonical.com/Component:instances(first:12):edges:10": {
    __id: "client:https://ds.canonical.com/Component:instances(first:12):edges:10",
    __typename: "NodeEdge",
    node: {
      __ref: "https://ds.canonical.com/apps_launchpad.component.breadcrumbs",
    },
  },
  "client:https://ds.canonical.com/Component:instances(first:12):edges:11": {
    __id: "client:https://ds.canonical.com/Component:instances(first:12):edges:11",
    __typename: "NodeEdge",
    node: {
      __ref: "https://ds.canonical.com/global.component.breadcrumbs",
    },
  },
  "client:https://ds.canonical.com/Component:instances(first:12):edges:2": {
    __id: "client:https://ds.canonical.com/Component:instances(first:12):edges:2",
    __typename: "NodeEdge",
    node: {
      __ref: "https://ds.canonical.com/apps_launchpad.component.avatar",
    },
  },
  "client:https://ds.canonical.com/Component:instances(first:12):edges:3": {
    __id: "client:https://ds.canonical.com/Component:instances(first:12):edges:3",
    __typename: "NodeEdge",
    node: {
      __ref: "https://ds.canonical.com/global.component.avatar",
    },
  },
  "client:https://ds.canonical.com/Component:instances(first:12):edges:4": {
    __id: "client:https://ds.canonical.com/Component:instances(first:12):edges:4",
    __typename: "NodeEdge",
    node: {
      __ref: "https://ds.canonical.com/apps_lxd.component.back_link",
    },
  },
  "client:https://ds.canonical.com/Component:instances(first:12):edges:5": {
    __id: "client:https://ds.canonical.com/Component:instances(first:12):edges:5",
    __typename: "NodeEdge",
    node: {
      __ref: "https://ds.canonical.com/apps_launchpad.component.badge",
    },
  },
  "client:https://ds.canonical.com/Component:instances(first:12):edges:6": {
    __id: "client:https://ds.canonical.com/Component:instances(first:12):edges:6",
    __typename: "NodeEdge",
    node: {
      __ref: "https://ds.canonical.com/apps_portal.component.badge",
    },
  },
  "client:https://ds.canonical.com/Component:instances(first:12):edges:7": {
    __id: "client:https://ds.canonical.com/Component:instances(first:12):edges:7",
    __typename: "NodeEdge",
    node: {
      __ref: "https://ds.canonical.com/global.component.badge",
    },
  },
  "client:https://ds.canonical.com/Component:instances(first:12):edges:8": {
    __id: "client:https://ds.canonical.com/Component:instances(first:12):edges:8",
    __typename: "NodeEdge",
    node: {
      __ref: "https://ds.canonical.com/sites.component.blog_card",
    },
  },
  "client:https://ds.canonical.com/Component:instances(first:12):edges:9": {
    __id: "client:https://ds.canonical.com/Component:instances(first:12):edges:9",
    __typename: "NodeEdge",
    node: {
      __ref:
        "https://ds.canonical.com/sites_webcomponentsprototype.component.blog_cards",
    },
  },
  "client:https://ds.canonical.com/Component:instances(first:12):pageInfo": {
    __id: "client:https://ds.canonical.com/Component:instances(first:12):pageInfo",
    __typename: "PageInfo",
    hasNextPage: true,
  },
  "client:https://ds.canonical.com/Component:properties:0": {
    __id: "client:https://ds.canonical.com/Component:properties:0",
    __typename: "ClassProperty",
    inherited: false,
    property: {
      __ref: "https://ds.canonical.com/hasSubcomponent",
    },
    required: false,
    singular: false,
  },
  "client:https://ds.canonical.com/Component:properties:1": {
    __id: "client:https://ds.canonical.com/Component:properties:1",
    __typename: "ClassProperty",
    inherited: true,
    property: {
      __ref: "https://ds.canonical.com/hasVariant",
    },
    required: false,
    singular: false,
  },
  "client:https://ds.canonical.com/Component:properties:10": {
    __id: "client:https://ds.canonical.com/Component:properties:10",
    __typename: "ClassProperty",
    inherited: true,
    property: {
      __ref: "https://ds.canonical.com/guidelines",
    },
    required: false,
    singular: true,
  },
  "client:https://ds.canonical.com/Component:properties:11": {
    __id: "client:https://ds.canonical.com/Component:properties:11",
    __typename: "ClassProperty",
    inherited: true,
    property: {
      __ref: "https://ds.canonical.com/usage",
    },
    required: false,
    singular: true,
  },
  "client:https://ds.canonical.com/Component:properties:12": {
    __id: "client:https://ds.canonical.com/Component:properties:12",
    __typename: "ClassProperty",
    inherited: true,
    property: {
      __ref: "https://ds.canonical.com/anatomyDsl",
    },
    required: false,
    singular: true,
  },
  "client:https://ds.canonical.com/Component:properties:13": {
    __id: "client:https://ds.canonical.com/Component:properties:13",
    __typename: "ClassProperty",
    inherited: true,
    property: {
      __ref: "https://ds.canonical.com/anatomyClassic",
    },
    required: false,
    singular: true,
  },
  "client:https://ds.canonical.com/Component:properties:14": {
    __id: "client:https://ds.canonical.com/Component:properties:14",
    __typename: "ClassProperty",
    inherited: true,
    property: {
      __ref: "https://ds.canonical.com/figmaLink",
    },
    required: false,
    singular: true,
  },
  "client:https://ds.canonical.com/Component:properties:15": {
    __id: "client:https://ds.canonical.com/Component:properties:15",
    __typename: "ClassProperty",
    inherited: true,
    property: {
      __ref: "https://ds.canonical.com/decisionLog",
    },
    required: false,
    singular: true,
  },
  "client:https://ds.canonical.com/Component:properties:16": {
    __id: "client:https://ds.canonical.com/Component:properties:16",
    __typename: "ClassProperty",
    inherited: true,
    property: {
      __ref: "https://ds.canonical.com/version",
    },
    required: false,
    singular: true,
  },
  "client:https://ds.canonical.com/Component:properties:17": {
    __id: "client:https://ds.canonical.com/Component:properties:17",
    __typename: "ClassProperty",
    inherited: true,
    property: {
      __ref: "https://ds.canonical.com/summary",
    },
    required: false,
    singular: true,
  },
  "client:https://ds.canonical.com/Component:properties:18": {
    __id: "client:https://ds.canonical.com/Component:properties:18",
    __typename: "ClassProperty",
    inherited: true,
    property: {
      __ref: "https://ds.canonical.com/name",
    },
    required: false,
    singular: true,
  },
  "client:https://ds.canonical.com/Component:properties:2": {
    __id: "client:https://ds.canonical.com/Component:properties:2",
    __typename: "ClassProperty",
    inherited: true,
    property: {
      __ref: "https://ds.canonical.com/variantOf",
    },
    required: false,
    singular: false,
  },
  "client:https://ds.canonical.com/Component:properties:3": {
    __id: "client:https://ds.canonical.com/Component:properties:3",
    __typename: "ClassProperty",
    inherited: true,
    property: {
      __ref: "https://ds.canonical.com/specializedBy",
    },
    required: false,
    singular: false,
  },
  "client:https://ds.canonical.com/Component:properties:4": {
    __id: "client:https://ds.canonical.com/Component:properties:4",
    __typename: "ClassProperty",
    inherited: true,
    property: {
      __ref: "https://ds.canonical.com/inheritsFrom",
    },
    required: false,
    singular: false,
  },
  "client:https://ds.canonical.com/Component:properties:5": {
    __id: "client:https://ds.canonical.com/Component:properties:5",
    __typename: "ClassProperty",
    inherited: true,
    property: {
      __ref: "https://ds.canonical.com/changeLog",
    },
    required: false,
    singular: false,
  },
  "client:https://ds.canonical.com/Component:properties:6": {
    __id: "client:https://ds.canonical.com/Component:properties:6",
    __typename: "ClassProperty",
    inherited: true,
    property: {
      __ref: "https://ds.canonical.com/documentationStage",
    },
    required: false,
    singular: false,
  },
  "client:https://ds.canonical.com/Component:properties:7": {
    __id: "client:https://ds.canonical.com/Component:properties:7",
    __typename: "ClassProperty",
    inherited: true,
    property: {
      __ref: "https://ds.canonical.com/hasProperty",
    },
    required: false,
    singular: false,
  },
  "client:https://ds.canonical.com/Component:properties:8": {
    __id: "client:https://ds.canonical.com/Component:properties:8",
    __typename: "ClassProperty",
    inherited: true,
    property: {
      __ref: "https://ds.canonical.com/hasModifierFamily",
    },
    required: false,
    singular: false,
  },
  "client:https://ds.canonical.com/Component:properties:9": {
    __id: "client:https://ds.canonical.com/Component:properties:9",
    __typename: "ClassProperty",
    inherited: true,
    property: {
      __ref: "https://ds.canonical.com/tier",
    },
    required: false,
    singular: true,
  },
  "client:https://ds.canonical.com/apps_launchpad.component.avatar:_meta": {
    __id: "client:https://ds.canonical.com/apps_launchpad.component.avatar:_meta",
    __typename: "EntityMeta",
    curie: "ds:apps_launchpad.component.avatar",
    title: "Avatar",
    type: {
      __ref: "https://ds.canonical.com/Component",
    },
  },
  "client:https://ds.canonical.com/apps_launchpad.component.badge:_meta": {
    __id: "client:https://ds.canonical.com/apps_launchpad.component.badge:_meta",
    __typename: "EntityMeta",
    curie: "ds:apps_launchpad.component.badge",
    title: "Badge",
    type: {
      __ref: "https://ds.canonical.com/Component",
    },
  },
  "client:https://ds.canonical.com/apps_launchpad.component.breadcrumbs:_meta":
    {
      __id: "client:https://ds.canonical.com/apps_launchpad.component.breadcrumbs:_meta",
      __typename: "EntityMeta",
      curie: "ds:apps_launchpad.component.breadcrumbs",
      title: "Breadcrumbs",
      type: {
        __ref: "https://ds.canonical.com/Component",
      },
    },
  "client:https://ds.canonical.com/apps_lxd.component.back_link:_meta": {
    __id: "client:https://ds.canonical.com/apps_lxd.component.back_link:_meta",
    __typename: "EntityMeta",
    curie: "ds:apps_lxd.component.back_link",
    title: "BackLink",
    type: {
      __ref: "https://ds.canonical.com/Component",
    },
  },
  "client:https://ds.canonical.com/apps_portal.component.badge:_meta": {
    __id: "client:https://ds.canonical.com/apps_portal.component.badge:_meta",
    __typename: "EntityMeta",
    curie: "ds:apps_portal.component.badge",
    title: "Badge",
    type: {
      __ref: "https://ds.canonical.com/Component",
    },
  },
  "client:https://ds.canonical.com/global.component.accordion:_meta": {
    __id: "client:https://ds.canonical.com/global.component.accordion:_meta",
    __typename: "EntityMeta",
    curie: "ds:global.component.accordion",
    title: "Accordion",
    type: {
      __ref: "https://ds.canonical.com/Component",
    },
  },
  "client:https://ds.canonical.com/global.component.announcement:_meta": {
    __id: "client:https://ds.canonical.com/global.component.announcement:_meta",
    __typename: "EntityMeta",
    curie: "ds:global.component.announcement",
    title: "Announcement",
    type: {
      __ref: "https://ds.canonical.com/Component",
    },
  },
  "client:https://ds.canonical.com/global.component.avatar:_meta": {
    __id: "client:https://ds.canonical.com/global.component.avatar:_meta",
    __typename: "EntityMeta",
    curie: "ds:global.component.avatar",
    title: "Avatar",
    type: {
      __ref: "https://ds.canonical.com/Component",
    },
  },
  "client:https://ds.canonical.com/global.component.badge:_meta": {
    __id: "client:https://ds.canonical.com/global.component.badge:_meta",
    __typename: "EntityMeta",
    curie: "ds:global.component.badge",
    title: "Badge",
    type: {
      __ref: "https://ds.canonical.com/Component",
    },
  },
  "client:https://ds.canonical.com/global.component.breadcrumbs:_meta": {
    __id: "client:https://ds.canonical.com/global.component.breadcrumbs:_meta",
    __typename: "EntityMeta",
    curie: "ds:global.component.breadcrumbs",
    title: "Breadcrumbs",
    type: {
      __ref: "https://ds.canonical.com/Component",
    },
  },
  "client:https://ds.canonical.com/sites.component.blog_card:_meta": {
    __id: "client:https://ds.canonical.com/sites.component.blog_card:_meta",
    __typename: "EntityMeta",
    curie: "ds:sites.component.blog_card",
    title: "BlogCard",
    type: {
      __ref: "https://ds.canonical.com/Component",
    },
  },
  "client:https://ds.canonical.com/sites_webcomponentsprototype.component.blog_cards:_meta":
    {
      __id: "client:https://ds.canonical.com/sites_webcomponentsprototype.component.blog_cards:_meta",
      __typename: "EntityMeta",
      curie: "ds:sites_webcomponentsprototype.component.blog_cards",
      title: "BlogCards",
      type: {
        __ref: "https://ds.canonical.com/Component",
      },
    },
  "client:root": {
    __id: "client:root",
    __typename: "__Root",
    ontologies: {
      __refs: [
        "client:root:ontologies:0",
        "client:root:ontologies:1",
        "client:root:ontologies:2",
        "client:root:ontologies:3",
      ],
    },
    'ontologyClass(uri:"ds:Component")': {
      __ref: "https://ds.canonical.com/Component",
    },
    'ontologyProperty(uri:"ds:Component")': null,
  },
  "client:root:ontologies:0": {
    __id: "client:root:ontologies:0",
    __typename: "Ontology",
    classes: {
      __refs: [
        "sem://surface#Validity",
        "sem://surface#Verdict",
        "sem://surface#Exemplar",
        "sem://surface#Law",
        "sem://surface#Bet",
        "sem://surface#Slot",
        "sem://surface#Region",
        "sem://surface#Pairing",
        "sem://surface#PairingRole",
        "sem://surface#Preservation",
        "sem://surface#Port",
        "sem://surface#Editor",
        "sem://surface#ComposerSurface",
        "sem://surface#Mechanism",
        "sem://surface#Peek",
        "sem://surface#Detail",
        "sem://surface#View",
        "sem://surface#Lens",
        "sem://surface#Anchoring",
        "sem://surface#Direction",
        "sem://surface#Rendering",
        "sem://surface#Surface",
        "sem://surface#AuthorityFamily",
        "sem://surface#Capability",
        "sem://surface#Substrate",
        "sem://surface#Persona",
        "sem://surface#Fluency",
        "sem://surface#Role",
        "sem://surface#Actor",
        "sem://surface#Coordinate",
        "sem://surface#Job",
      ],
    },
    label: "surface",
    namespace: "sem://surface#",
    prefix: "surface",
    properties: {
      __refs: [
        "sem://surface#homedIn",
        "sem://surface#supersededBy",
        "sem://surface#validity",
        "sem://surface#verdict",
        "sem://surface#walksSurface",
        "sem://surface#walksJob",
        "sem://surface#bets",
        "sem://surface#rendersIn",
        "sem://surface#summonedBy",
        "sem://surface#ofRegion",
        "sem://surface#declaresSlot",
        "sem://surface#composes",
        "sem://surface#pairingRole",
        "sem://surface#pairedIn",
        "sem://surface#arrival",
        "sem://surface#pairsSurface",
        "sem://surface#forJob",
        "sem://surface#exposes",
        "sem://surface#dominantJob",
        "sem://surface#within",
        "sem://surface#expandsTo",
        "sem://surface#anchoring",
        "sem://surface#direction",
        "sem://surface#rendering",
        "sem://surface#granted",
        "sem://surface#attenuates",
        "sem://surface#bundles",
        "sem://surface#requiresAuthority",
        "sem://surface#serves",
        "sem://surface#over",
        "sem://surface#region",
        "sem://surface#fluency",
        "sem://surface#role",
        "sem://surface#actor",
        "sem://surface#coordinates",
        "sem://surface#validityNote",
        "sem://surface#finding",
        "sem://surface#narrative",
        "sem://surface#wakeCondition",
        "sem://surface#deferred",
        "sem://surface#confidence",
        "sem://surface#threshold",
        "sem://surface#instrument",
        "sem://surface#test",
        "sem://surface#required",
        "sem://surface#reorientationOrder",
        "sem://surface#protocol",
        "sem://surface#kindOfLooking",
        "sem://surface#slice",
        "sem://surface#contract",
        "sem://surface#essence",
        "sem://surface#fluencyOrder",
        "sem://surface#acceptance",
        "sem://surface#story",
      ],
    },
  },
  "client:root:ontologies:1": {
    __id: "client:root:ontologies:1",
    __typename: "Ontology",
    classes: {
      __refs: [
        "https://ds.canonical.com/ChangeLogEntry",
        "https://ds.canonical.com/TagCategory",
        "https://ds.canonical.com/Tag",
        "https://ds.canonical.com/ImplementationLibrary",
        "https://ds.canonical.com/ImplementationObject",
        "https://ds.canonical.com/Tier",
        "https://ds.canonical.com/Property",
        "https://ds.canonical.com/ModifierFamily",
        "https://ds.canonical.com/Modifier",
        "https://ds.canonical.com/Group",
        "https://ds.canonical.com/Subcomponent",
        "https://ds.canonical.com/Layout",
        "https://ds.canonical.com/Pattern",
        "https://ds.canonical.com/Component",
        "https://ds.canonical.com/UIBlock",
        "https://ds.canonical.com/UIElement",
        "https://ds.canonical.com/Entity",
      ],
    },
    label: "ds",
    namespace: "https://ds.canonical.com/",
    prefix: "ds",
    properties: {
      __refs: [
        "https://ds.canonical.com/libraryTier",
        "https://ds.canonical.com/library",
        "https://ds.canonical.com/implementsBlock",
        "https://ds.canonical.com/category",
        "https://ds.canonical.com/hasSubcomponent",
        "https://ds.canonical.com/parentComponent",
        "https://ds.canonical.com/hasModifier",
        "https://ds.canonical.com/modifierFamily",
        "https://ds.canonical.com/hasVariant",
        "https://ds.canonical.com/variantOf",
        "https://ds.canonical.com/specializedBy",
        "https://ds.canonical.com/inheritsFrom",
        "https://ds.canonical.com/changeLog",
        "https://ds.canonical.com/documentationStage",
        "https://ds.canonical.com/hasProperty",
        "https://ds.canonical.com/hasModifierFamily",
        "https://ds.canonical.com/tier",
        "https://ds.canonical.com/documentation",
        "https://ds.canonical.com/link",
        "https://ds.canonical.com/platform",
        "https://ds.canonical.com/libraryName",
        "https://ds.canonical.com/isDraft",
        "https://ds.canonical.com/versionedLink",
        "https://ds.canonical.com/headLink",
        "https://ds.canonical.com/implementationVersion",
        "https://ds.canonical.com/constraints",
        "https://ds.canonical.com/defaultValue",
        "https://ds.canonical.com/optional",
        "https://ds.canonical.com/propertyType",
        "https://ds.canonical.com/targetDevices",
        "https://ds.canonical.com/changeType",
        "https://ds.canonical.com/githubLink",
        "https://ds.canonical.com/owner",
        "https://ds.canonical.com/change",
        "https://ds.canonical.com/timestamp",
        "https://ds.canonical.com/whenToRemove",
        "https://ds.canonical.com/whenToApply",
        "https://ds.canonical.com/gridAreas",
        "https://ds.canonical.com/domain",
        "https://ds.canonical.com/grid",
        "https://ds.canonical.com/standalone",
        "https://ds.canonical.com/guidelines",
        "https://ds.canonical.com/usage",
        "https://ds.canonical.com/anatomyDsl",
        "https://ds.canonical.com/anatomyClassic",
        "https://ds.canonical.com/figmaLink",
        "https://ds.canonical.com/decisionLog",
        "https://ds.canonical.com/version",
        "https://ds.canonical.com/summary",
        "https://ds.canonical.com/name",
        "https://ds.canonical.com/completionGuidance",
        "https://ds.canonical.com/acceptanceCriteria",
      ],
    },
  },
  "client:root:ontologies:2": {
    __id: "client:root:ontologies:2",
    __typename: "Ontology",
    classes: {
      __refs: [
        "http://pragma.canonical.com/codestandards#Example",
        "http://pragma.canonical.com/codestandards#Category",
        "http://pragma.canonical.com/codestandards#CodeStandard",
      ],
    },
    label: "cs",
    namespace: "http://pragma.canonical.com/codestandards#",
    prefix: "cs",
    properties: {
      __refs: [
        "http://pragma.canonical.com/codestandards#dont",
        "http://pragma.canonical.com/codestandards#do",
        "http://pragma.canonical.com/codestandards#extends",
        "http://pragma.canonical.com/codestandards#hasCategory",
        "http://pragma.canonical.com/codestandards#code",
        "http://pragma.canonical.com/codestandards#language",
        "http://pragma.canonical.com/codestandards#description",
        "http://pragma.canonical.com/codestandards#slug",
        "http://pragma.canonical.com/codestandards#name",
      ],
    },
  },
  "client:root:ontologies:3": {
    __id: "client:root:ontologies:3",
    __typename: "Ontology",
    classes: {
      __refs: [
        "http://anatomy-dsl.example.org/ontology#SwitchCase",
        "http://anatomy-dsl.example.org/ontology#Switch",
        "http://anatomy-dsl.example.org/ontology#Style",
        "http://anatomy-dsl.example.org/ontology#Relation",
        "http://anatomy-dsl.example.org/ontology#Edge",
        "http://anatomy-dsl.example.org/ontology#AnonymousNode",
        "http://anatomy-dsl.example.org/ontology#NamedNode",
        "http://anatomy-dsl.example.org/ontology#Node",
        "http://anatomy-dsl.example.org/ontology#Specification",
      ],
    },
    label: "anatomy",
    namespace: "http://anatomy-dsl.example.org/ontology#",
    prefix: "anatomy",
    properties: {
      __refs: [
        "http://anatomy-dsl.example.org/ontology#hasStyle",
        "http://anatomy-dsl.example.org/ontology#caseNode",
        "http://anatomy-dsl.example.org/ontology#hasCase",
        "http://anatomy-dsl.example.org/ontology#edgeSwitch",
        "http://anatomy-dsl.example.org/ontology#edgeTarget",
        "http://anatomy-dsl.example.org/ontology#hasRelation",
        "http://anatomy-dsl.example.org/ontology#hasEdge",
        "http://anatomy-dsl.example.org/ontology#rootNode",
        "http://anatomy-dsl.example.org/ontology#styleValue",
        "http://anatomy-dsl.example.org/ontology#styleKey",
        "http://anatomy-dsl.example.org/ontology#slotName",
        "http://anatomy-dsl.example.org/ontology#cardinality",
        "http://anatomy-dsl.example.org/ontology#discriminator",
        "http://anatomy-dsl.example.org/ontology#role",
        "http://anatomy-dsl.example.org/ontology#uri",
      ],
    },
  },
  "http://anatomy-dsl.example.org/ontology#AnonymousNode": {
    __id: "http://anatomy-dsl.example.org/ontology#AnonymousNode",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#AnonymousNode",
    instanceCount: 0,
    isAbstract: false,
    label: "Anonymous Node",
    superclass: {
      __ref: "http://anatomy-dsl.example.org/ontology#Node",
    },
  },
  "http://anatomy-dsl.example.org/ontology#Edge": {
    __id: "http://anatomy-dsl.example.org/ontology#Edge",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#Edge",
    instanceCount: 0,
    isAbstract: false,
    label: "Edge",
    superclass: null,
  },
  "http://anatomy-dsl.example.org/ontology#NamedNode": {
    __id: "http://anatomy-dsl.example.org/ontology#NamedNode",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#NamedNode",
    instanceCount: 0,
    isAbstract: false,
    label: "Named Node",
    superclass: {
      __ref: "http://anatomy-dsl.example.org/ontology#Node",
    },
  },
  "http://anatomy-dsl.example.org/ontology#Node": {
    __id: "http://anatomy-dsl.example.org/ontology#Node",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#Node",
    instanceCount: 0,
    isAbstract: true,
    label: "Node",
    superclass: null,
  },
  "http://anatomy-dsl.example.org/ontology#Relation": {
    __id: "http://anatomy-dsl.example.org/ontology#Relation",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#Relation",
    instanceCount: 0,
    isAbstract: false,
    label: "Relation",
    superclass: null,
  },
  "http://anatomy-dsl.example.org/ontology#Specification": {
    __id: "http://anatomy-dsl.example.org/ontology#Specification",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#Specification",
    instanceCount: 0,
    isAbstract: false,
    label: "Specification",
    superclass: null,
  },
  "http://anatomy-dsl.example.org/ontology#Style": {
    __id: "http://anatomy-dsl.example.org/ontology#Style",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#Style",
    instanceCount: 0,
    isAbstract: false,
    label: "Style",
    superclass: null,
  },
  "http://anatomy-dsl.example.org/ontology#Switch": {
    __id: "http://anatomy-dsl.example.org/ontology#Switch",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#Switch",
    instanceCount: 0,
    isAbstract: false,
    label: "Switch",
    superclass: null,
  },
  "http://anatomy-dsl.example.org/ontology#SwitchCase": {
    __id: "http://anatomy-dsl.example.org/ontology#SwitchCase",
    __typename: "OntologyClass",
    uri: "http://anatomy-dsl.example.org/ontology#SwitchCase",
    instanceCount: 0,
    isAbstract: false,
    label: "Switch Case",
    superclass: null,
  },
  "http://anatomy-dsl.example.org/ontology#cardinality": {
    __id: "http://anatomy-dsl.example.org/ontology#cardinality",
    __typename: "OntologyProperty",
    domain: {
      __ref: "http://anatomy-dsl.example.org/ontology#Relation",
    },
    kind: "DATATYPE",
    label: "cardinality",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "http://anatomy-dsl.example.org/ontology#cardinality",
  },
  "http://anatomy-dsl.example.org/ontology#caseNode": {
    __id: "http://anatomy-dsl.example.org/ontology#caseNode",
    __typename: "OntologyProperty",
    domain: {
      __ref: "http://anatomy-dsl.example.org/ontology#SwitchCase",
    },
    kind: "OBJECT",
    label: "case node",
    range: "http://anatomy-dsl.example.org/ontology#Node",
    uri: "http://anatomy-dsl.example.org/ontology#caseNode",
  },
  "http://anatomy-dsl.example.org/ontology#discriminator": {
    __id: "http://anatomy-dsl.example.org/ontology#discriminator",
    __typename: "OntologyProperty",
    domain: {
      __ref: "http://anatomy-dsl.example.org/ontology#Switch",
    },
    kind: "DATATYPE",
    label: "discriminator",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "http://anatomy-dsl.example.org/ontology#discriminator",
  },
  "http://anatomy-dsl.example.org/ontology#edgeSwitch": {
    __id: "http://anatomy-dsl.example.org/ontology#edgeSwitch",
    __typename: "OntologyProperty",
    domain: {
      __ref: "http://anatomy-dsl.example.org/ontology#Edge",
    },
    kind: "OBJECT",
    label: "edge switch",
    range: "http://anatomy-dsl.example.org/ontology#Switch",
    uri: "http://anatomy-dsl.example.org/ontology#edgeSwitch",
  },
  "http://anatomy-dsl.example.org/ontology#edgeTarget": {
    __id: "http://anatomy-dsl.example.org/ontology#edgeTarget",
    __typename: "OntologyProperty",
    domain: {
      __ref: "http://anatomy-dsl.example.org/ontology#Edge",
    },
    kind: "OBJECT",
    label: "edge target",
    range: "http://anatomy-dsl.example.org/ontology#Node",
    uri: "http://anatomy-dsl.example.org/ontology#edgeTarget",
  },
  "http://anatomy-dsl.example.org/ontology#hasCase": {
    __id: "http://anatomy-dsl.example.org/ontology#hasCase",
    __typename: "OntologyProperty",
    domain: {
      __ref: "http://anatomy-dsl.example.org/ontology#Switch",
    },
    kind: "OBJECT",
    label: "has case",
    range: "http://anatomy-dsl.example.org/ontology#SwitchCase",
    uri: "http://anatomy-dsl.example.org/ontology#hasCase",
  },
  "http://anatomy-dsl.example.org/ontology#hasEdge": {
    __id: "http://anatomy-dsl.example.org/ontology#hasEdge",
    __typename: "OntologyProperty",
    domain: {
      __ref: "http://anatomy-dsl.example.org/ontology#Node",
    },
    kind: "OBJECT",
    label: "has edge",
    range: "http://anatomy-dsl.example.org/ontology#Edge",
    uri: "http://anatomy-dsl.example.org/ontology#hasEdge",
  },
  "http://anatomy-dsl.example.org/ontology#hasRelation": {
    __id: "http://anatomy-dsl.example.org/ontology#hasRelation",
    __typename: "OntologyProperty",
    domain: {
      __ref: "http://anatomy-dsl.example.org/ontology#Edge",
    },
    kind: "OBJECT",
    label: "has relation",
    range: "http://anatomy-dsl.example.org/ontology#Relation",
    uri: "http://anatomy-dsl.example.org/ontology#hasRelation",
  },
  "http://anatomy-dsl.example.org/ontology#hasStyle": {
    __id: "http://anatomy-dsl.example.org/ontology#hasStyle",
    __typename: "OntologyProperty",
    domain: {
      __ref: "http://anatomy-dsl.example.org/ontology#Node",
    },
    kind: "OBJECT",
    label: "has style",
    range: "http://anatomy-dsl.example.org/ontology#Style",
    uri: "http://anatomy-dsl.example.org/ontology#hasStyle",
  },
  "http://anatomy-dsl.example.org/ontology#role": {
    __id: "http://anatomy-dsl.example.org/ontology#role",
    __typename: "OntologyProperty",
    domain: {
      __ref: "http://anatomy-dsl.example.org/ontology#AnonymousNode",
    },
    kind: "DATATYPE",
    label: "role",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "http://anatomy-dsl.example.org/ontology#role",
  },
  "http://anatomy-dsl.example.org/ontology#rootNode": {
    __id: "http://anatomy-dsl.example.org/ontology#rootNode",
    __typename: "OntologyProperty",
    domain: {
      __ref: "http://anatomy-dsl.example.org/ontology#Specification",
    },
    kind: "OBJECT",
    label: "root node",
    range: "http://anatomy-dsl.example.org/ontology#NamedNode",
    uri: "http://anatomy-dsl.example.org/ontology#rootNode",
  },
  "http://anatomy-dsl.example.org/ontology#slotName": {
    __id: "http://anatomy-dsl.example.org/ontology#slotName",
    __typename: "OntologyProperty",
    domain: {
      __ref: "http://anatomy-dsl.example.org/ontology#Relation",
    },
    kind: "DATATYPE",
    label: "slot name",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "http://anatomy-dsl.example.org/ontology#slotName",
  },
  "http://anatomy-dsl.example.org/ontology#styleKey": {
    __id: "http://anatomy-dsl.example.org/ontology#styleKey",
    __typename: "OntologyProperty",
    domain: {
      __ref: "http://anatomy-dsl.example.org/ontology#Style",
    },
    kind: "DATATYPE",
    label: "style key",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "http://anatomy-dsl.example.org/ontology#styleKey",
  },
  "http://anatomy-dsl.example.org/ontology#styleValue": {
    __id: "http://anatomy-dsl.example.org/ontology#styleValue",
    __typename: "OntologyProperty",
    domain: {
      __ref: "http://anatomy-dsl.example.org/ontology#Style",
    },
    kind: "DATATYPE",
    label: "style value",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "http://anatomy-dsl.example.org/ontology#styleValue",
  },
  "http://anatomy-dsl.example.org/ontology#uri": {
    __id: "http://anatomy-dsl.example.org/ontology#uri",
    __typename: "OntologyProperty",
    domain: {
      __ref: "http://anatomy-dsl.example.org/ontology#NamedNode",
    },
    kind: "DATATYPE",
    label: "uri",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "http://anatomy-dsl.example.org/ontology#uri",
  },
  "http://pragma.canonical.com/codestandards#Category": {
    __id: "http://pragma.canonical.com/codestandards#Category",
    __typename: "OntologyClass",
    uri: "http://pragma.canonical.com/codestandards#Category",
    instanceCount: 19,
    isAbstract: false,
    label: "Category",
    superclass: null,
  },
  "http://pragma.canonical.com/codestandards#CodeStandard": {
    __id: "http://pragma.canonical.com/codestandards#CodeStandard",
    __typename: "OntologyClass",
    uri: "http://pragma.canonical.com/codestandards#CodeStandard",
    instanceCount: 131,
    isAbstract: false,
    label: "Code Standard",
    superclass: null,
  },
  "http://pragma.canonical.com/codestandards#Example": {
    __id: "http://pragma.canonical.com/codestandards#Example",
    __typename: "OntologyClass",
    uri: "http://pragma.canonical.com/codestandards#Example",
    instanceCount: 0,
    isAbstract: false,
    label: "Example",
    superclass: null,
  },
  "http://pragma.canonical.com/codestandards#code": {
    __id: "http://pragma.canonical.com/codestandards#code",
    __typename: "OntologyProperty",
    domain: {
      __ref: "http://pragma.canonical.com/codestandards#Example",
    },
    kind: "DATATYPE",
    label: "code",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "http://pragma.canonical.com/codestandards#code",
  },
  "http://pragma.canonical.com/codestandards#description": {
    __id: "http://pragma.canonical.com/codestandards#description",
    __typename: "OntologyProperty",
    domain: null,
    kind: "DATATYPE",
    label: "description",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "http://pragma.canonical.com/codestandards#description",
  },
  "http://pragma.canonical.com/codestandards#do": {
    __id: "http://pragma.canonical.com/codestandards#do",
    __typename: "OntologyProperty",
    domain: {
      __ref: "http://pragma.canonical.com/codestandards#CodeStandard",
    },
    kind: "OBJECT",
    label: "do",
    range: "http://pragma.canonical.com/codestandards#Example",
    uri: "http://pragma.canonical.com/codestandards#do",
  },
  "http://pragma.canonical.com/codestandards#dont": {
    __id: "http://pragma.canonical.com/codestandards#dont",
    __typename: "OntologyProperty",
    domain: {
      __ref: "http://pragma.canonical.com/codestandards#CodeStandard",
    },
    kind: "OBJECT",
    label: "don't",
    range: "http://pragma.canonical.com/codestandards#Example",
    uri: "http://pragma.canonical.com/codestandards#dont",
  },
  "http://pragma.canonical.com/codestandards#extends": {
    __id: "http://pragma.canonical.com/codestandards#extends",
    __typename: "OntologyProperty",
    domain: {
      __ref: "http://pragma.canonical.com/codestandards#CodeStandard",
    },
    kind: "OBJECT",
    label: "extends",
    range: "http://pragma.canonical.com/codestandards#CodeStandard",
    uri: "http://pragma.canonical.com/codestandards#extends",
  },
  "http://pragma.canonical.com/codestandards#hasCategory": {
    __id: "http://pragma.canonical.com/codestandards#hasCategory",
    __typename: "OntologyProperty",
    domain: {
      __ref: "http://pragma.canonical.com/codestandards#CodeStandard",
    },
    kind: "OBJECT",
    label: "has category",
    range: "http://pragma.canonical.com/codestandards#Category",
    uri: "http://pragma.canonical.com/codestandards#hasCategory",
  },
  "http://pragma.canonical.com/codestandards#language": {
    __id: "http://pragma.canonical.com/codestandards#language",
    __typename: "OntologyProperty",
    domain: {
      __ref: "http://pragma.canonical.com/codestandards#Example",
    },
    kind: "DATATYPE",
    label: "language",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "http://pragma.canonical.com/codestandards#language",
  },
  "http://pragma.canonical.com/codestandards#name": {
    __id: "http://pragma.canonical.com/codestandards#name",
    __typename: "OntologyProperty",
    domain: {
      __ref: "http://pragma.canonical.com/codestandards#CodeStandard",
    },
    kind: "DATATYPE",
    label: "name",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "http://pragma.canonical.com/codestandards#name",
  },
  "http://pragma.canonical.com/codestandards#slug": {
    __id: "http://pragma.canonical.com/codestandards#slug",
    __typename: "OntologyProperty",
    domain: {
      __ref: "http://pragma.canonical.com/codestandards#Category",
    },
    kind: "DATATYPE",
    label: "slug",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "http://pragma.canonical.com/codestandards#slug",
  },
  "https://ds.canonical.com/ChangeLogEntry": {
    __id: "https://ds.canonical.com/ChangeLogEntry",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/ChangeLogEntry",
    instanceCount: 0,
    isAbstract: false,
    label: "Change Log Entry",
    superclass: {
      __ref: "https://ds.canonical.com/Entity",
    },
  },
  "https://ds.canonical.com/Component": {
    __id: "https://ds.canonical.com/Component",
    __typename: "OntologyClass",
    definition:
      "An implementable piece of user interface defined by its appearance and behaviour",
    instanceCount: 111,
    "instances(first:12)": {
      __ref: "client:https://ds.canonical.com/Component:instances(first:12)",
    },
    isAbstract: false,
    label: "Component",
    namespace: "ds",
    properties: {
      __refs: [
        "client:https://ds.canonical.com/Component:properties:0",
        "client:https://ds.canonical.com/Component:properties:1",
        "client:https://ds.canonical.com/Component:properties:2",
        "client:https://ds.canonical.com/Component:properties:3",
        "client:https://ds.canonical.com/Component:properties:4",
        "client:https://ds.canonical.com/Component:properties:5",
        "client:https://ds.canonical.com/Component:properties:6",
        "client:https://ds.canonical.com/Component:properties:7",
        "client:https://ds.canonical.com/Component:properties:8",
        "client:https://ds.canonical.com/Component:properties:9",
        "client:https://ds.canonical.com/Component:properties:10",
        "client:https://ds.canonical.com/Component:properties:11",
        "client:https://ds.canonical.com/Component:properties:12",
        "client:https://ds.canonical.com/Component:properties:13",
        "client:https://ds.canonical.com/Component:properties:14",
        "client:https://ds.canonical.com/Component:properties:15",
        "client:https://ds.canonical.com/Component:properties:16",
        "client:https://ds.canonical.com/Component:properties:17",
        "client:https://ds.canonical.com/Component:properties:18",
      ],
    },
    subclasses: {
      __refs: [],
    },
    superclass: {
      __ref: "https://ds.canonical.com/UIBlock",
    },
    superclasses: {
      __refs: [
        "https://ds.canonical.com/UIBlock",
        "https://ds.canonical.com/UIElement",
        "https://ds.canonical.com/Entity",
      ],
    },
    uri: "https://ds.canonical.com/Component",
  },
  "https://ds.canonical.com/Entity": {
    __id: "https://ds.canonical.com/Entity",
    __typename: "OntologyClass",
    label: "Entity",
    uri: "https://ds.canonical.com/Entity",
    instanceCount: 0,
    isAbstract: true,
    superclass: null,
  },
  "https://ds.canonical.com/Group": {
    __id: "https://ds.canonical.com/Group",
    __typename: "OntologyClass",
    instanceCount: 9,
    isAbstract: false,
    label: "Group",
    superclass: {
      __ref: "https://ds.canonical.com/UIBlock",
    },
    uri: "https://ds.canonical.com/Group",
  },
  "https://ds.canonical.com/ImplementationLibrary": {
    __id: "https://ds.canonical.com/ImplementationLibrary",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/ImplementationLibrary",
    instanceCount: 0,
    isAbstract: false,
    label: "Implementation Library",
    superclass: {
      __ref: "https://ds.canonical.com/Entity",
    },
  },
  "https://ds.canonical.com/ImplementationObject": {
    __id: "https://ds.canonical.com/ImplementationObject",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/ImplementationObject",
    instanceCount: 0,
    isAbstract: false,
    label: "Implementation Object",
    superclass: {
      __ref: "https://ds.canonical.com/Entity",
    },
  },
  "https://ds.canonical.com/Layout": {
    __id: "https://ds.canonical.com/Layout",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Layout",
    instanceCount: 21,
    isAbstract: false,
    label: "Layout",
    superclass: {
      __ref: "https://ds.canonical.com/UIBlock",
    },
  },
  "https://ds.canonical.com/Modifier": {
    __id: "https://ds.canonical.com/Modifier",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Modifier",
    instanceCount: 27,
    isAbstract: false,
    label: "Modifier",
    superclass: {
      __ref: "https://ds.canonical.com/UIElement",
    },
  },
  "https://ds.canonical.com/ModifierFamily": {
    __id: "https://ds.canonical.com/ModifierFamily",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/ModifierFamily",
    instanceCount: 9,
    isAbstract: false,
    label: "Modifier Family",
    superclass: {
      __ref: "https://ds.canonical.com/UIElement",
    },
  },
  "https://ds.canonical.com/Pattern": {
    __id: "https://ds.canonical.com/Pattern",
    __typename: "OntologyClass",
    instanceCount: 41,
    isAbstract: false,
    label: "Pattern",
    superclass: {
      __ref: "https://ds.canonical.com/UIBlock",
    },
    uri: "https://ds.canonical.com/Pattern",
  },
  "https://ds.canonical.com/Property": {
    __id: "https://ds.canonical.com/Property",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Property",
    instanceCount: 0,
    isAbstract: false,
    label: "Property",
    superclass: {
      __ref: "https://ds.canonical.com/Entity",
    },
  },
  "https://ds.canonical.com/Subcomponent": {
    __id: "https://ds.canonical.com/Subcomponent",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Subcomponent",
    instanceCount: 85,
    isAbstract: false,
    label: "Subcomponent",
    superclass: {
      __ref: "https://ds.canonical.com/UIBlock",
    },
  },
  "https://ds.canonical.com/Tag": {
    __id: "https://ds.canonical.com/Tag",
    __typename: "OntologyClass",
    uri: "https://ds.canonical.com/Tag",
    instanceCount: 42,
    isAbstract: false,
    label: "Tag",
    superclass: {
      __ref: "https://ds.canonical.com/Entity",
    },
  },
  "https://ds.canonical.com/TagCategory": {
    __id: "https://ds.canonical.com/TagCategory",
    __typename: "OntologyClass",
    instanceCount: 8,
    isAbstract: false,
    label: "Tag Category",
    superclass: {
      __ref: "https://ds.canonical.com/Entity",
    },
    uri: "https://ds.canonical.com/TagCategory",
  },
  "https://ds.canonical.com/Tier": {
    __id: "https://ds.canonical.com/Tier",
    __typename: "OntologyClass",
    instanceCount: 15,
    isAbstract: false,
    label: "Tier",
    superclass: {
      __ref: "https://ds.canonical.com/Entity",
    },
    uri: "https://ds.canonical.com/Tier",
  },
  "https://ds.canonical.com/UIBlock": {
    __id: "https://ds.canonical.com/UIBlock",
    __typename: "OntologyClass",
    label: "UI Block",
    uri: "https://ds.canonical.com/UIBlock",
    instanceCount: 0,
    isAbstract: true,
    superclass: {
      __ref: "https://ds.canonical.com/UIElement",
    },
  },
  "https://ds.canonical.com/UIElement": {
    __id: "https://ds.canonical.com/UIElement",
    __typename: "OntologyClass",
    label: "UI Element",
    uri: "https://ds.canonical.com/UIElement",
    instanceCount: 0,
    isAbstract: true,
    superclass: {
      __ref: "https://ds.canonical.com/Entity",
    },
  },
  "https://ds.canonical.com/acceptanceCriteria": {
    __id: "https://ds.canonical.com/acceptanceCriteria",
    __typename: "OntologyProperty",
    domain: null,
    kind: "ANNOTATION",
    label: "acceptanceCriteria",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "https://ds.canonical.com/acceptanceCriteria",
  },
  "https://ds.canonical.com/anatomyClassic": {
    __id: "https://ds.canonical.com/anatomyClassic",
    __typename: "OntologyProperty",
    definition:
      "DEPRECATED. Legacy anatomy field (free-form text). Superseded by ds:anatomyDsl.",
    kind: "DATATYPE",
    label: "anatomyClassic",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "https://ds.canonical.com/anatomyClassic",
    domain: {
      __ref: "https://ds.canonical.com/UIBlock",
    },
  },
  "https://ds.canonical.com/anatomyDsl": {
    __id: "https://ds.canonical.com/anatomyDsl",
    __typename: "OntologyProperty",
    definition:
      "YAML specification of component structure using the Anatomy DSL. Describes nodes (named/anonymous), edges with cardinality, slots, and CTI-inspired styles.",
    kind: "DATATYPE",
    label: "anatomyDsl",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "https://ds.canonical.com/anatomyDsl",
    domain: {
      __ref: "https://ds.canonical.com/UIBlock",
    },
  },
  "https://ds.canonical.com/apps_launchpad.component.avatar": {
    __id: "https://ds.canonical.com/apps_launchpad.component.avatar",
    __typename: "Component",
    uri: "https://ds.canonical.com/apps_launchpad.component.avatar",
    _meta: {
      __ref:
        "client:https://ds.canonical.com/apps_launchpad.component.avatar:_meta",
    },
  },
  "https://ds.canonical.com/apps_launchpad.component.badge": {
    __id: "https://ds.canonical.com/apps_launchpad.component.badge",
    __typename: "Component",
    uri: "https://ds.canonical.com/apps_launchpad.component.badge",
    _meta: {
      __ref:
        "client:https://ds.canonical.com/apps_launchpad.component.badge:_meta",
    },
  },
  "https://ds.canonical.com/apps_launchpad.component.breadcrumbs": {
    __id: "https://ds.canonical.com/apps_launchpad.component.breadcrumbs",
    __typename: "Component",
    uri: "https://ds.canonical.com/apps_launchpad.component.breadcrumbs",
    _meta: {
      __ref:
        "client:https://ds.canonical.com/apps_launchpad.component.breadcrumbs:_meta",
    },
  },
  "https://ds.canonical.com/apps_lxd.component.back_link": {
    __id: "https://ds.canonical.com/apps_lxd.component.back_link",
    __typename: "Component",
    uri: "https://ds.canonical.com/apps_lxd.component.back_link",
    _meta: {
      __ref:
        "client:https://ds.canonical.com/apps_lxd.component.back_link:_meta",
    },
  },
  "https://ds.canonical.com/apps_portal.component.badge": {
    __id: "https://ds.canonical.com/apps_portal.component.badge",
    __typename: "Component",
    uri: "https://ds.canonical.com/apps_portal.component.badge",
    _meta: {
      __ref:
        "client:https://ds.canonical.com/apps_portal.component.badge:_meta",
    },
  },
  "https://ds.canonical.com/category": {
    __id: "https://ds.canonical.com/category",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/Tag",
    },
    kind: "OBJECT",
    label: "category",
    range: "https://ds.canonical.com/TagCategory",
    uri: "https://ds.canonical.com/category",
  },
  "https://ds.canonical.com/change": {
    __id: "https://ds.canonical.com/change",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/ChangeLogEntry",
    },
    kind: "DATATYPE",
    label: "change",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "https://ds.canonical.com/change",
  },
  "https://ds.canonical.com/changeLog": {
    __id: "https://ds.canonical.com/changeLog",
    __typename: "OntologyProperty",
    definition: "Links a UI Block to its dated change log entries.",
    kind: "OBJECT",
    label: "changeLog",
    range: "https://ds.canonical.com/ChangeLogEntry",
    uri: "https://ds.canonical.com/changeLog",
    domain: {
      __ref: "https://ds.canonical.com/UIBlock",
    },
  },
  "https://ds.canonical.com/changeType": {
    __id: "https://ds.canonical.com/changeType",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/ChangeLogEntry",
    },
    kind: "DATATYPE",
    label: "changeType",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "https://ds.canonical.com/changeType",
  },
  "https://ds.canonical.com/completionGuidance": {
    __id: "https://ds.canonical.com/completionGuidance",
    __typename: "OntologyProperty",
    domain: null,
    kind: "ANNOTATION",
    label: "completionGuidance",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "https://ds.canonical.com/completionGuidance",
  },
  "https://ds.canonical.com/constraints": {
    __id: "https://ds.canonical.com/constraints",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/Property",
    },
    kind: "DATATYPE",
    label: "constraints",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "https://ds.canonical.com/constraints",
  },
  "https://ds.canonical.com/decisionLog": {
    __id: "https://ds.canonical.com/decisionLog",
    __typename: "OntologyProperty",
    definition: "Log of decisions with [date][author][content]",
    kind: "DATATYPE",
    label: "decisionLog",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "https://ds.canonical.com/decisionLog",
    domain: {
      __ref: "https://ds.canonical.com/Entity",
    },
  },
  "https://ds.canonical.com/defaultValue": {
    __id: "https://ds.canonical.com/defaultValue",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/Property",
    },
    kind: "DATATYPE",
    label: "defaultValue",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "https://ds.canonical.com/defaultValue",
  },
  "https://ds.canonical.com/documentation": {
    __id: "https://ds.canonical.com/documentation",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/ImplementationLibrary",
    },
    kind: "DATATYPE",
    label: "documentation",
    range: "http://www.w3.org/2001/XMLSchema#anyURI",
    uri: "https://ds.canonical.com/documentation",
  },
  "https://ds.canonical.com/documentationStage": {
    __id: "https://ds.canonical.com/documentationStage",
    __typename: "OntologyProperty",
    definition:
      "Links a UI Block to the documentation-stage Tag(s) applied to it (e.g. needs:documentation). One facet of the wider Tag vocabulary; the other tag facets are tracked as future work.",
    kind: "OBJECT",
    label: "documentationStage",
    range: "https://ds.canonical.com/Tag",
    uri: "https://ds.canonical.com/documentationStage",
    domain: {
      __ref: "https://ds.canonical.com/UIBlock",
    },
  },
  "https://ds.canonical.com/domain": {
    __id: "https://ds.canonical.com/domain",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/Layout",
    },
    kind: "DATATYPE",
    label: "domain",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "https://ds.canonical.com/domain",
  },
  "https://ds.canonical.com/figmaLink": {
    __id: "https://ds.canonical.com/figmaLink",
    __typename: "OntologyProperty",
    definition: "Link to the Figma design file for this UI block",
    kind: "DATATYPE",
    label: "figmaLink",
    range: "http://www.w3.org/2001/XMLSchema#anyURI",
    uri: "https://ds.canonical.com/figmaLink",
    domain: {
      __ref: "https://ds.canonical.com/UIBlock",
    },
  },
  "https://ds.canonical.com/githubLink": {
    __id: "https://ds.canonical.com/githubLink",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/ChangeLogEntry",
    },
    kind: "DATATYPE",
    label: "githubLink",
    range: "http://www.w3.org/2001/XMLSchema#anyURI",
    uri: "https://ds.canonical.com/githubLink",
  },
  "https://ds.canonical.com/global.component.accordion": {
    __id: "https://ds.canonical.com/global.component.accordion",
    __typename: "Component",
    uri: "https://ds.canonical.com/global.component.accordion",
    _meta: {
      __ref: "client:https://ds.canonical.com/global.component.accordion:_meta",
    },
  },
  "https://ds.canonical.com/global.component.announcement": {
    __id: "https://ds.canonical.com/global.component.announcement",
    __typename: "Component",
    uri: "https://ds.canonical.com/global.component.announcement",
    _meta: {
      __ref:
        "client:https://ds.canonical.com/global.component.announcement:_meta",
    },
  },
  "https://ds.canonical.com/global.component.avatar": {
    __id: "https://ds.canonical.com/global.component.avatar",
    __typename: "Component",
    uri: "https://ds.canonical.com/global.component.avatar",
    _meta: {
      __ref: "client:https://ds.canonical.com/global.component.avatar:_meta",
    },
  },
  "https://ds.canonical.com/global.component.badge": {
    __id: "https://ds.canonical.com/global.component.badge",
    __typename: "Component",
    uri: "https://ds.canonical.com/global.component.badge",
    _meta: {
      __ref: "client:https://ds.canonical.com/global.component.badge:_meta",
    },
  },
  "https://ds.canonical.com/global.component.breadcrumbs": {
    __id: "https://ds.canonical.com/global.component.breadcrumbs",
    __typename: "Component",
    uri: "https://ds.canonical.com/global.component.breadcrumbs",
    _meta: {
      __ref:
        "client:https://ds.canonical.com/global.component.breadcrumbs:_meta",
    },
  },
  "https://ds.canonical.com/grid": {
    __id: "https://ds.canonical.com/grid",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/Layout",
    },
    kind: "DATATYPE",
    label: "grid",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "https://ds.canonical.com/grid",
  },
  "https://ds.canonical.com/gridAreas": {
    __id: "https://ds.canonical.com/gridAreas",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/Layout",
    },
    kind: "DATATYPE",
    label: "gridAreas",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "https://ds.canonical.com/gridAreas",
  },
  "https://ds.canonical.com/guidelines": {
    __id: "https://ds.canonical.com/guidelines",
    __typename: "OntologyProperty",
    definition:
      "Detailed specification for correctly using and implementing the UI block.",
    kind: "DATATYPE",
    label: "guidelines",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "https://ds.canonical.com/guidelines",
    domain: {
      __ref: "https://ds.canonical.com/UIBlock",
    },
  },
  "https://ds.canonical.com/hasModifier": {
    __id: "https://ds.canonical.com/hasModifier",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/ModifierFamily",
    },
    kind: "OBJECT",
    label: "hasModifier",
    range: "https://ds.canonical.com/Modifier",
    uri: "https://ds.canonical.com/hasModifier",
  },
  "https://ds.canonical.com/hasModifierFamily": {
    __id: "https://ds.canonical.com/hasModifierFamily",
    __typename: "OntologyProperty",
    definition: "Links a UI Block to applicable modifier families",
    kind: "OBJECT",
    label: "hasModifierFamily",
    range: "https://ds.canonical.com/ModifierFamily",
    uri: "https://ds.canonical.com/hasModifierFamily",
    domain: {
      __ref: "https://ds.canonical.com/UIBlock",
    },
  },
  "https://ds.canonical.com/hasProperty": {
    __id: "https://ds.canonical.com/hasProperty",
    __typename: "OntologyProperty",
    definition: "Links a UI Block to its configurable properties",
    kind: "OBJECT",
    label: "hasProperty",
    range: "https://ds.canonical.com/Property",
    uri: "https://ds.canonical.com/hasProperty",
    domain: {
      __ref: "https://ds.canonical.com/UIBlock",
    },
  },
  "https://ds.canonical.com/hasSubcomponent": {
    __id: "https://ds.canonical.com/hasSubcomponent",
    __typename: "OntologyProperty",
    definition: "Subcomponents that are structural parts of this component",
    kind: "OBJECT",
    label: "hasSubcomponent",
    range: "https://ds.canonical.com/Subcomponent",
    uri: "https://ds.canonical.com/hasSubcomponent",
    domain: {
      __ref: "https://ds.canonical.com/Component",
    },
  },
  "https://ds.canonical.com/hasVariant": {
    __id: "https://ds.canonical.com/hasVariant",
    __typename: "OntologyProperty",
    definition:
      "The variants of this UI Block (inverse of ds:variantOf). E.g. Tooltip has variant Tooltip+Dense.",
    kind: "OBJECT",
    label: "hasVariant",
    range: "https://ds.canonical.com/UIBlock",
    uri: "https://ds.canonical.com/hasVariant",
    domain: {
      __ref: "https://ds.canonical.com/UIBlock",
    },
  },
  "https://ds.canonical.com/headLink": {
    __id: "https://ds.canonical.com/headLink",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/ImplementationObject",
    },
    kind: "DATATYPE",
    label: "headLink",
    range: "http://www.w3.org/2001/XMLSchema#anyURI",
    uri: "https://ds.canonical.com/headLink",
  },
  "https://ds.canonical.com/implementationVersion": {
    __id: "https://ds.canonical.com/implementationVersion",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/ImplementationObject",
    },
    kind: "DATATYPE",
    label: "implementationVersion",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "https://ds.canonical.com/implementationVersion",
  },
  "https://ds.canonical.com/implementsBlock": {
    __id: "https://ds.canonical.com/implementsBlock",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/ImplementationObject",
    },
    kind: "OBJECT",
    label: "implementsBlock",
    range: "https://ds.canonical.com/UIBlock",
    uri: "https://ds.canonical.com/implementsBlock",
  },
  "https://ds.canonical.com/inheritsFrom": {
    __id: "https://ds.canonical.com/inheritsFrom",
    __typename: "OntologyProperty",
    definition:
      "The UI Block this block inherits from / specialises (e.g. a Data tooltip inherits from Tooltip). Distinct from subcomponent containment: inheritance is an is-a-specialisation relationship.",
    kind: "OBJECT",
    label: "inheritsFrom",
    range: "https://ds.canonical.com/UIBlock",
    uri: "https://ds.canonical.com/inheritsFrom",
    domain: {
      __ref: "https://ds.canonical.com/UIBlock",
    },
  },
  "https://ds.canonical.com/isDraft": {
    __id: "https://ds.canonical.com/isDraft",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/ImplementationObject",
    },
    kind: "DATATYPE",
    label: "isDraft",
    range: "http://www.w3.org/2001/XMLSchema#boolean",
    uri: "https://ds.canonical.com/isDraft",
  },
  "https://ds.canonical.com/library": {
    __id: "https://ds.canonical.com/library",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/ImplementationObject",
    },
    kind: "OBJECT",
    label: "library",
    range: "https://ds.canonical.com/ImplementationLibrary",
    uri: "https://ds.canonical.com/library",
  },
  "https://ds.canonical.com/libraryName": {
    __id: "https://ds.canonical.com/libraryName",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/ImplementationLibrary",
    },
    kind: "DATATYPE",
    label: "libraryName",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "https://ds.canonical.com/libraryName",
  },
  "https://ds.canonical.com/libraryTier": {
    __id: "https://ds.canonical.com/libraryTier",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/ImplementationLibrary",
    },
    kind: "OBJECT",
    label: "libraryTier",
    range: "https://ds.canonical.com/Tier",
    uri: "https://ds.canonical.com/libraryTier",
  },
  "https://ds.canonical.com/link": {
    __id: "https://ds.canonical.com/link",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/ImplementationLibrary",
    },
    kind: "DATATYPE",
    label: "link",
    range: "http://www.w3.org/2001/XMLSchema#anyURI",
    uri: "https://ds.canonical.com/link",
  },
  "https://ds.canonical.com/modifierFamily": {
    __id: "https://ds.canonical.com/modifierFamily",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/Modifier",
    },
    kind: "OBJECT",
    label: "modifierFamily",
    range: "https://ds.canonical.com/ModifierFamily",
    uri: "https://ds.canonical.com/modifierFamily",
  },
  "https://ds.canonical.com/name": {
    __id: "https://ds.canonical.com/name",
    __typename: "OntologyProperty",
    definition:
      "A human-readable text for the entity. The primary identifier, used for referencing and display purposes.",
    kind: "DATATYPE",
    label: "name",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "https://ds.canonical.com/name",
    domain: {
      __ref: "https://ds.canonical.com/Entity",
    },
  },
  "https://ds.canonical.com/optional": {
    __id: "https://ds.canonical.com/optional",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/Property",
    },
    kind: "DATATYPE",
    label: "optional",
    range: "http://www.w3.org/2001/XMLSchema#boolean",
    uri: "https://ds.canonical.com/optional",
  },
  "https://ds.canonical.com/owner": {
    __id: "https://ds.canonical.com/owner",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/ChangeLogEntry",
    },
    kind: "DATATYPE",
    label: "owner",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "https://ds.canonical.com/owner",
  },
  "https://ds.canonical.com/parentComponent": {
    __id: "https://ds.canonical.com/parentComponent",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/Subcomponent",
    },
    kind: "OBJECT",
    label: "parentComponent",
    range: "https://ds.canonical.com/Component",
    uri: "https://ds.canonical.com/parentComponent",
  },
  "https://ds.canonical.com/platform": {
    __id: "https://ds.canonical.com/platform",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/ImplementationLibrary",
    },
    kind: "DATATYPE",
    label: "platform",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "https://ds.canonical.com/platform",
  },
  "https://ds.canonical.com/propertyType": {
    __id: "https://ds.canonical.com/propertyType",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/Property",
    },
    kind: "DATATYPE",
    label: "propertyType",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "https://ds.canonical.com/propertyType",
  },
  "https://ds.canonical.com/sites.component.blog_card": {
    __id: "https://ds.canonical.com/sites.component.blog_card",
    __typename: "Component",
    uri: "https://ds.canonical.com/sites.component.blog_card",
    _meta: {
      __ref: "client:https://ds.canonical.com/sites.component.blog_card:_meta",
    },
  },
  "https://ds.canonical.com/sites_webcomponentsprototype.component.blog_cards":
    {
      __id: "https://ds.canonical.com/sites_webcomponentsprototype.component.blog_cards",
      __typename: "Component",
      uri: "https://ds.canonical.com/sites_webcomponentsprototype.component.blog_cards",
      _meta: {
        __ref:
          "client:https://ds.canonical.com/sites_webcomponentsprototype.component.blog_cards:_meta",
      },
    },
  "https://ds.canonical.com/specializedBy": {
    __id: "https://ds.canonical.com/specializedBy",
    __typename: "OntologyProperty",
    definition:
      "The UI Blocks that inherit from / specialise this block (inverse of ds:inheritsFrom). E.g. Tooltip is specialised by DataTooltip.",
    kind: "OBJECT",
    label: "specializedBy",
    range: "https://ds.canonical.com/UIBlock",
    uri: "https://ds.canonical.com/specializedBy",
    domain: {
      __ref: "https://ds.canonical.com/UIBlock",
    },
  },
  "https://ds.canonical.com/standalone": {
    __id: "https://ds.canonical.com/standalone",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/Subcomponent",
    },
    kind: "DATATYPE",
    label: "standalone",
    range: "http://www.w3.org/2001/XMLSchema#boolean",
    uri: "https://ds.canonical.com/standalone",
  },
  "https://ds.canonical.com/summary": {
    __id: "https://ds.canonical.com/summary",
    __typename: "OntologyProperty",
    definition:
      "A comprehensive paragraph of text that states the singular purpose of the entity.",
    kind: "DATATYPE",
    label: "summary",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "https://ds.canonical.com/summary",
    domain: {
      __ref: "https://ds.canonical.com/Entity",
    },
  },
  "https://ds.canonical.com/targetDevices": {
    __id: "https://ds.canonical.com/targetDevices",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/Layout",
    },
    kind: "DATATYPE",
    label: "targetDevices",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "https://ds.canonical.com/targetDevices",
  },
  "https://ds.canonical.com/tier": {
    __id: "https://ds.canonical.com/tier",
    __typename: "OntologyProperty",
    definition: "The tier to which the UI block belongs to",
    kind: "OBJECT",
    label: "tier",
    range: "https://ds.canonical.com/Tier",
    uri: "https://ds.canonical.com/tier",
    domain: {
      __ref: "https://ds.canonical.com/UIBlock",
    },
  },
  "https://ds.canonical.com/timestamp": {
    __id: "https://ds.canonical.com/timestamp",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/ChangeLogEntry",
    },
    kind: "DATATYPE",
    label: "timestamp",
    range: "http://www.w3.org/2001/XMLSchema#dateTime",
    uri: "https://ds.canonical.com/timestamp",
  },
  "https://ds.canonical.com/usage": {
    __id: "https://ds.canonical.com/usage",
    __typename: "OntologyProperty",
    definition:
      "Free-text (Markdown) usage documentation for the UI block. Subsumes the former whenToUse/whenNotToUse: a usage entry describes the contexts where the component is most appropriate ('When to use'), the contexts where it is NOT appropriate and what to use instead ('When not to use'), and a general description, typically as Markdown sub-sections.",
    kind: "DATATYPE",
    label: "usage",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "https://ds.canonical.com/usage",
    domain: {
      __ref: "https://ds.canonical.com/UIBlock",
    },
  },
  "https://ds.canonical.com/variantOf": {
    __id: "https://ds.canonical.com/variantOf",
    __typename: "OntologyProperty",
    definition:
      "The base UI Block this block is a variant of, by the '+' naming convention (e.g. Tooltip+Dense is a variant of Tooltip). Distinct from ds:inheritsFrom: a variant is a modifier-style derivative rather than a prefixed specialisation.",
    kind: "OBJECT",
    label: "variantOf",
    range: "https://ds.canonical.com/UIBlock",
    uri: "https://ds.canonical.com/variantOf",
    domain: {
      __ref: "https://ds.canonical.com/UIBlock",
    },
  },
  "https://ds.canonical.com/version": {
    __id: "https://ds.canonical.com/version",
    __typename: "OntologyProperty",
    definition: "Semantic version of the entity following semver specification",
    kind: "DATATYPE",
    label: "version",
    range: "https://ds.canonical.com/SemverString",
    uri: "https://ds.canonical.com/version",
    domain: {
      __ref: "https://ds.canonical.com/Entity",
    },
  },
  "https://ds.canonical.com/versionedLink": {
    __id: "https://ds.canonical.com/versionedLink",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/ImplementationObject",
    },
    kind: "DATATYPE",
    label: "versionedLink",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "https://ds.canonical.com/versionedLink",
  },
  "https://ds.canonical.com/whenToApply": {
    __id: "https://ds.canonical.com/whenToApply",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/Tag",
    },
    kind: "DATATYPE",
    label: "whenToApply",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "https://ds.canonical.com/whenToApply",
  },
  "https://ds.canonical.com/whenToRemove": {
    __id: "https://ds.canonical.com/whenToRemove",
    __typename: "OntologyProperty",
    domain: {
      __ref: "https://ds.canonical.com/Tag",
    },
    kind: "DATATYPE",
    label: "whenToRemove",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "https://ds.canonical.com/whenToRemove",
  },
  "sem://surface#Actor": {
    __id: "sem://surface#Actor",
    __typename: "OntologyClass",
    instanceCount: 2,
    isAbstract: false,
    label: "Actor",
    superclass: null,
    uri: "sem://surface#Actor",
  },
  "sem://surface#Anchoring": {
    __id: "sem://surface#Anchoring",
    __typename: "OntologyClass",
    instanceCount: 2,
    isAbstract: false,
    label: "Anchoring",
    superclass: null,
    uri: "sem://surface#Anchoring",
  },
  "sem://surface#AuthorityFamily": {
    __id: "sem://surface#AuthorityFamily",
    __typename: "OntologyClass",
    instanceCount: 5,
    isAbstract: false,
    label: "Authority Family",
    superclass: null,
    uri: "sem://surface#AuthorityFamily",
  },
  "sem://surface#Bet": {
    __id: "sem://surface#Bet",
    __typename: "OntologyClass",
    uri: "sem://surface#Bet",
    instanceCount: 13,
    isAbstract: false,
    label: "Bet",
    superclass: null,
  },
  "sem://surface#Capability": {
    __id: "sem://surface#Capability",
    __typename: "OntologyClass",
    uri: "sem://surface#Capability",
    instanceCount: 42,
    isAbstract: false,
    label: "Capability",
    superclass: null,
  },
  "sem://surface#ComposerSurface": {
    __id: "sem://surface#ComposerSurface",
    __typename: "OntologyClass",
    instanceCount: 6,
    isAbstract: false,
    label: "Composer",
    superclass: {
      __ref: "sem://surface#Surface",
    },
    uri: "sem://surface#ComposerSurface",
  },
  "sem://surface#Coordinate": {
    __id: "sem://surface#Coordinate",
    __typename: "OntologyClass",
    uri: "sem://surface#Coordinate",
    instanceCount: 30,
    isAbstract: false,
    label: "Coordinate",
    superclass: null,
  },
  "sem://surface#Detail": {
    __id: "sem://surface#Detail",
    __typename: "OntologyClass",
    instanceCount: 4,
    isAbstract: false,
    label: "Detail",
    superclass: {
      __ref: "sem://surface#View",
    },
    uri: "sem://surface#Detail",
  },
  "sem://surface#Direction": {
    __id: "sem://surface#Direction",
    __typename: "OntologyClass",
    instanceCount: 2,
    isAbstract: false,
    label: "Direction",
    superclass: null,
    uri: "sem://surface#Direction",
  },
  "sem://surface#Editor": {
    __id: "sem://surface#Editor",
    __typename: "OntologyClass",
    instanceCount: 1,
    isAbstract: false,
    label: "Editor",
    superclass: {
      __ref: "sem://surface#Surface",
    },
    uri: "sem://surface#Editor",
  },
  "sem://surface#Exemplar": {
    __id: "sem://surface#Exemplar",
    __typename: "OntologyClass",
    uri: "sem://surface#Exemplar",
    instanceCount: 1,
    isAbstract: false,
    label: "Exemplar",
    superclass: null,
  },
  "sem://surface#Fluency": {
    __id: "sem://surface#Fluency",
    __typename: "OntologyClass",
    uri: "sem://surface#Fluency",
    instanceCount: 3,
    isAbstract: false,
    label: "Fluency",
    superclass: null,
  },
  "sem://surface#Job": {
    __id: "sem://surface#Job",
    __typename: "OntologyClass",
    uri: "sem://surface#Job",
    instanceCount: 65,
    isAbstract: false,
    label: "Job",
    superclass: null,
  },
  "sem://surface#Law": {
    __id: "sem://surface#Law",
    __typename: "OntologyClass",
    instanceCount: 24,
    isAbstract: false,
    label: "Law",
    superclass: null,
    uri: "sem://surface#Law",
  },
  "sem://surface#Lens": {
    __id: "sem://surface#Lens",
    __typename: "OntologyClass",
    uri: "sem://surface#Lens",
    instanceCount: 11,
    isAbstract: false,
    label: "Lens",
    superclass: {
      __ref: "sem://surface#Surface",
    },
  },
  "sem://surface#Mechanism": {
    __id: "sem://surface#Mechanism",
    __typename: "OntologyClass",
    instanceCount: 2,
    isAbstract: false,
    label: "Mechanism",
    superclass: {
      __ref: "sem://surface#View",
    },
    uri: "sem://surface#Mechanism",
  },
  "sem://surface#Pairing": {
    __id: "sem://surface#Pairing",
    __typename: "OntologyClass",
    uri: "sem://surface#Pairing",
    instanceCount: 146,
    isAbstract: false,
    label: "Pairing",
    superclass: null,
  },
  "sem://surface#PairingRole": {
    __id: "sem://surface#PairingRole",
    __typename: "OntologyClass",
    instanceCount: 2,
    isAbstract: false,
    label: "Pairing Role",
    superclass: null,
    uri: "sem://surface#PairingRole",
  },
  "sem://surface#Peek": {
    __id: "sem://surface#Peek",
    __typename: "OntologyClass",
    instanceCount: 3,
    isAbstract: false,
    label: "Peek",
    superclass: {
      __ref: "sem://surface#View",
    },
    uri: "sem://surface#Peek",
  },
  "sem://surface#Persona": {
    __id: "sem://surface#Persona",
    __typename: "OntologyClass",
    uri: "sem://surface#Persona",
    instanceCount: 8,
    isAbstract: false,
    label: "Persona",
    superclass: null,
  },
  "sem://surface#Port": {
    __id: "sem://surface#Port",
    __typename: "OntologyClass",
    uri: "sem://surface#Port",
    instanceCount: 2,
    isAbstract: false,
    label: "Port",
    superclass: {
      __ref: "sem://surface#Surface",
    },
  },
  "sem://surface#Preservation": {
    __id: "sem://surface#Preservation",
    __typename: "OntologyClass",
    uri: "sem://surface#Preservation",
    instanceCount: 4,
    isAbstract: false,
    label: "Preservation",
    superclass: null,
  },
  "sem://surface#Region": {
    __id: "sem://surface#Region",
    __typename: "OntologyClass",
    instanceCount: 8,
    isAbstract: false,
    label: "Region",
    superclass: null,
    uri: "sem://surface#Region",
  },
  "sem://surface#Rendering": {
    __id: "sem://surface#Rendering",
    __typename: "OntologyClass",
    instanceCount: 2,
    isAbstract: false,
    label: "Rendering",
    superclass: null,
    uri: "sem://surface#Rendering",
  },
  "sem://surface#Role": {
    __id: "sem://surface#Role",
    __typename: "OntologyClass",
    instanceCount: 3,
    isAbstract: false,
    label: "Role",
    superclass: null,
    uri: "sem://surface#Role",
  },
  "sem://surface#Slot": {
    __id: "sem://surface#Slot",
    __typename: "OntologyClass",
    uri: "sem://surface#Slot",
    instanceCount: 24,
    isAbstract: false,
    label: "Slot",
    superclass: null,
  },
  "sem://surface#Substrate": {
    __id: "sem://surface#Substrate",
    __typename: "OntologyClass",
    instanceCount: 2,
    isAbstract: false,
    label: "Substrate",
    superclass: null,
    uri: "sem://surface#Substrate",
  },
  "sem://surface#Surface": {
    __id: "sem://surface#Surface",
    __typename: "OntologyClass",
    uri: "sem://surface#Surface",
    instanceCount: 0,
    isAbstract: true,
    label: "Surface",
    superclass: null,
  },
  "sem://surface#Validity": {
    __id: "sem://surface#Validity",
    __typename: "OntologyClass",
    instanceCount: 4,
    isAbstract: false,
    label: "Validity",
    superclass: null,
    uri: "sem://surface#Validity",
  },
  "sem://surface#Verdict": {
    __id: "sem://surface#Verdict",
    __typename: "OntologyClass",
    instanceCount: 3,
    isAbstract: false,
    label: "Verdict",
    superclass: null,
    uri: "sem://surface#Verdict",
  },
  "sem://surface#View": {
    __id: "sem://surface#View",
    __typename: "OntologyClass",
    instanceCount: 32,
    isAbstract: false,
    label: "View",
    superclass: {
      __ref: "sem://surface#Surface",
    },
    uri: "sem://surface#View",
  },
  "sem://surface#acceptance": {
    __id: "sem://surface#acceptance",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Job",
    },
    kind: "DATATYPE",
    label: "acceptance",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "sem://surface#acceptance",
  },
  "sem://surface#actor": {
    __id: "sem://surface#actor",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Coordinate",
    },
    kind: "OBJECT",
    label: "actor",
    range: "sem://surface#Actor",
    uri: "sem://surface#actor",
  },
  "sem://surface#anchoring": {
    __id: "sem://surface#anchoring",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Surface",
    },
    kind: "OBJECT",
    label: "anchoring",
    range: "sem://surface#Anchoring",
    uri: "sem://surface#anchoring",
  },
  "sem://surface#arrival": {
    __id: "sem://surface#arrival",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Pairing",
    },
    kind: "OBJECT",
    label: "arrival",
    range: "sem://surface#Preservation",
    uri: "sem://surface#arrival",
  },
  "sem://surface#attenuates": {
    __id: "sem://surface#attenuates",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Capability",
    },
    kind: "OBJECT",
    label: "attenuates",
    range: "sem://surface#Capability",
    uri: "sem://surface#attenuates",
  },
  "sem://surface#bets": {
    __id: "sem://surface#bets",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Job",
    },
    kind: "OBJECT",
    label: "bets",
    range: "sem://assume#Assumption",
    uri: "sem://surface#bets",
  },
  "sem://surface#bundles": {
    __id: "sem://surface#bundles",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Capability",
    },
    kind: "OBJECT",
    label: "bundles",
    range: "sem://surface#Capability",
    uri: "sem://surface#bundles",
  },
  "sem://surface#composes": {
    __id: "sem://surface#composes",
    __typename: "OntologyProperty",
    domain: null,
    kind: "OBJECT",
    label: "composes",
    range: "https://ds.canonical.com/Layout",
    uri: "sem://surface#composes",
  },
  "sem://surface#confidence": {
    __id: "sem://surface#confidence",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Bet",
    },
    kind: "DATATYPE",
    label: "confidence",
    range: "http://www.w3.org/2001/XMLSchema#decimal",
    uri: "sem://surface#confidence",
  },
  "sem://surface#contract": {
    __id: "sem://surface#contract",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Capability",
    },
    kind: "DATATYPE",
    label: "contract",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "sem://surface#contract",
  },
  "sem://surface#coordinates": {
    __id: "sem://surface#coordinates",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Job",
    },
    kind: "OBJECT",
    label: "coordinates",
    range: "sem://surface#Coordinate",
    uri: "sem://surface#coordinates",
  },
  "sem://surface#declaresSlot": {
    __id: "sem://surface#declaresSlot",
    __typename: "OntologyProperty",
    domain: null,
    kind: "OBJECT",
    label: "declares slot",
    range: "sem://surface#Slot",
    uri: "sem://surface#declaresSlot",
  },
  "sem://surface#deferred": {
    __id: "sem://surface#deferred",
    __typename: "OntologyProperty",
    domain: null,
    kind: "DATATYPE",
    label: "deferred",
    range: "http://www.w3.org/2001/XMLSchema#boolean",
    uri: "sem://surface#deferred",
  },
  "sem://surface#direction": {
    __id: "sem://surface#direction",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Surface",
    },
    kind: "OBJECT",
    label: "direction",
    range: "sem://surface#Direction",
    uri: "sem://surface#direction",
  },
  "sem://surface#dominantJob": {
    __id: "sem://surface#dominantJob",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Lens",
    },
    kind: "OBJECT",
    label: "dominant job",
    range: "sem://surface#Job",
    uri: "sem://surface#dominantJob",
  },
  "sem://surface#essence": {
    __id: "sem://surface#essence",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Persona",
    },
    kind: "DATATYPE",
    label: "essence",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "sem://surface#essence",
  },
  "sem://surface#expandsTo": {
    __id: "sem://surface#expandsTo",
    __typename: "OntologyProperty",
    domain: null,
    kind: "OBJECT",
    label: "expands to",
    range: "sem://surface#Region",
    uri: "sem://surface#expandsTo",
  },
  "sem://surface#exposes": {
    __id: "sem://surface#exposes",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Port",
    },
    kind: "OBJECT",
    label: "exposes",
    range: "sem://surface#Capability",
    uri: "sem://surface#exposes",
  },
  "sem://surface#finding": {
    __id: "sem://surface#finding",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Exemplar",
    },
    kind: "DATATYPE",
    label: "finding",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "sem://surface#finding",
  },
  "sem://surface#fluency": {
    __id: "sem://surface#fluency",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Coordinate",
    },
    kind: "OBJECT",
    label: "fluency",
    range: "sem://surface#Fluency",
    uri: "sem://surface#fluency",
  },
  "sem://surface#fluencyOrder": {
    __id: "sem://surface#fluencyOrder",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Fluency",
    },
    kind: "DATATYPE",
    label: "fluency order",
    range: "http://www.w3.org/2001/XMLSchema#integer",
    uri: "sem://surface#fluencyOrder",
  },
  "sem://surface#forJob": {
    __id: "sem://surface#forJob",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Pairing",
    },
    kind: "OBJECT",
    label: "for job",
    range: "sem://surface#Job",
    uri: "sem://surface#forJob",
  },
  "sem://surface#granted": {
    __id: "sem://surface#granted",
    __typename: "OntologyProperty",
    domain: null,
    kind: "OBJECT",
    label: "granted",
    range: "sem://surface#Capability",
    uri: "sem://surface#granted",
  },
  "sem://surface#homedIn": {
    __id: "sem://surface#homedIn",
    __typename: "OntologyProperty",
    domain: null,
    kind: "OBJECT",
    label: "homed in",
    range: "sem://surface#Lens",
    uri: "sem://surface#homedIn",
  },
  "sem://surface#instrument": {
    __id: "sem://surface#instrument",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Bet",
    },
    kind: "DATATYPE",
    label: "instrument",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "sem://surface#instrument",
  },
  "sem://surface#kindOfLooking": {
    __id: "sem://surface#kindOfLooking",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Lens",
    },
    kind: "DATATYPE",
    label: "kind of looking",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "sem://surface#kindOfLooking",
  },
  "sem://surface#narrative": {
    __id: "sem://surface#narrative",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Exemplar",
    },
    kind: "DATATYPE",
    label: "narrative",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "sem://surface#narrative",
  },
  "sem://surface#ofRegion": {
    __id: "sem://surface#ofRegion",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Slot",
    },
    kind: "OBJECT",
    label: "of region",
    range: "sem://surface#Region",
    uri: "sem://surface#ofRegion",
  },
  "sem://surface#over": {
    __id: "sem://surface#over",
    __typename: "OntologyProperty",
    domain: null,
    kind: "OBJECT",
    label: "over",
    range: "sem://surface#Substrate",
    uri: "sem://surface#over",
  },
  "sem://surface#pairedIn": {
    __id: "sem://surface#pairedIn",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Surface",
    },
    kind: "OBJECT",
    label: "paired in",
    range: "sem://surface#Pairing",
    uri: "sem://surface#pairedIn",
  },
  "sem://surface#pairingRole": {
    __id: "sem://surface#pairingRole",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Pairing",
    },
    kind: "OBJECT",
    label: "pairing role",
    range: "sem://surface#PairingRole",
    uri: "sem://surface#pairingRole",
  },
  "sem://surface#pairsSurface": {
    __id: "sem://surface#pairsSurface",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Pairing",
    },
    kind: "OBJECT",
    label: "pairs surface",
    range: "sem://surface#Surface",
    uri: "sem://surface#pairsSurface",
  },
  "sem://surface#protocol": {
    __id: "sem://surface#protocol",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Port",
    },
    kind: "DATATYPE",
    label: "protocol",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "sem://surface#protocol",
  },
  "sem://surface#region": {
    __id: "sem://surface#region",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Persona",
    },
    kind: "OBJECT",
    label: "region",
    range: "sem://surface#Coordinate",
    uri: "sem://surface#region",
  },
  "sem://surface#rendering": {
    __id: "sem://surface#rendering",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Surface",
    },
    kind: "OBJECT",
    label: "rendering",
    range: "sem://surface#Rendering",
    uri: "sem://surface#rendering",
  },
  "sem://surface#rendersIn": {
    __id: "sem://surface#rendersIn",
    __typename: "OntologyProperty",
    domain: null,
    kind: "OBJECT",
    label: "renders in",
    range: "sem://surface#Slot",
    uri: "sem://surface#rendersIn",
  },
  "sem://surface#reorientationOrder": {
    __id: "sem://surface#reorientationOrder",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Preservation",
    },
    kind: "DATATYPE",
    label: "reorientation order",
    range: "http://www.w3.org/2001/XMLSchema#integer",
    uri: "sem://surface#reorientationOrder",
  },
  "sem://surface#required": {
    __id: "sem://surface#required",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Slot",
    },
    kind: "DATATYPE",
    label: "required",
    range: "http://www.w3.org/2001/XMLSchema#boolean",
    uri: "sem://surface#required",
  },
  "sem://surface#requiresAuthority": {
    __id: "sem://surface#requiresAuthority",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Capability",
    },
    kind: "OBJECT",
    label: "requires authority",
    range: "sem://surface#AuthorityFamily",
    uri: "sem://surface#requiresAuthority",
  },
  "sem://surface#role": {
    __id: "sem://surface#role",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Coordinate",
    },
    kind: "OBJECT",
    label: "role",
    range: "sem://surface#Role",
    uri: "sem://surface#role",
  },
  "sem://surface#serves": {
    __id: "sem://surface#serves",
    __typename: "OntologyProperty",
    domain: null,
    kind: "OBJECT",
    label: "serves",
    range: "sem://surface#Job",
    uri: "sem://surface#serves",
  },
  "sem://surface#slice": {
    __id: "sem://surface#slice",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Lens",
    },
    kind: "DATATYPE",
    label: "slice",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "sem://surface#slice",
  },
  "sem://surface#story": {
    __id: "sem://surface#story",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Job",
    },
    kind: "DATATYPE",
    label: "story",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "sem://surface#story",
  },
  "sem://surface#summonedBy": {
    __id: "sem://surface#summonedBy",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Slot",
    },
    kind: "OBJECT",
    label: "summoned by",
    range: "sem://surface#Job",
    uri: "sem://surface#summonedBy",
  },
  "sem://surface#supersededBy": {
    __id: "sem://surface#supersededBy",
    __typename: "OntologyProperty",
    domain: null,
    kind: "OBJECT",
    label: "superseded by",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "sem://surface#supersededBy",
  },
  "sem://surface#test": {
    __id: "sem://surface#test",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Bet",
    },
    kind: "DATATYPE",
    label: "test",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "sem://surface#test",
  },
  "sem://surface#threshold": {
    __id: "sem://surface#threshold",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Bet",
    },
    kind: "DATATYPE",
    label: "threshold",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "sem://surface#threshold",
  },
  "sem://surface#validity": {
    __id: "sem://surface#validity",
    __typename: "OntologyProperty",
    domain: null,
    kind: "OBJECT",
    label: "validity",
    range: "sem://surface#Validity",
    uri: "sem://surface#validity",
  },
  "sem://surface#validityNote": {
    __id: "sem://surface#validityNote",
    __typename: "OntologyProperty",
    domain: null,
    kind: "DATATYPE",
    label: "validity note",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "sem://surface#validityNote",
  },
  "sem://surface#verdict": {
    __id: "sem://surface#verdict",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Exemplar",
    },
    kind: "OBJECT",
    label: "verdict",
    range: "sem://surface#Verdict",
    uri: "sem://surface#verdict",
  },
  "sem://surface#wakeCondition": {
    __id: "sem://surface#wakeCondition",
    __typename: "OntologyProperty",
    domain: null,
    kind: "DATATYPE",
    label: "wake condition",
    range: "http://www.w3.org/2001/XMLSchema#string",
    uri: "sem://surface#wakeCondition",
  },
  "sem://surface#walksJob": {
    __id: "sem://surface#walksJob",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Exemplar",
    },
    kind: "OBJECT",
    label: "walks job",
    range: "sem://surface#Job",
    uri: "sem://surface#walksJob",
  },
  "sem://surface#walksSurface": {
    __id: "sem://surface#walksSurface",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Exemplar",
    },
    kind: "OBJECT",
    label: "walks surface",
    range: "sem://surface#Surface",
    uri: "sem://surface#walksSurface",
  },
  "sem://surface#within": {
    __id: "sem://surface#within",
    __typename: "OntologyProperty",
    domain: {
      __ref: "sem://surface#Surface",
    },
    kind: "OBJECT",
    label: "within",
    range: "sem://surface#Surface",
    uri: "sem://surface#within",
  },
} as unknown as RecordMap;

export default definitionsExplorerRecordsComponent;
