// Generated by @canonical/summon-component:react v0.1.0

import type { Meta, StoryObj } from "@storybook/react-vite";
import ModeStrip from "./ModeStrip.js";

const meta: Meta<typeof ModeStrip> = {
  title: "Shell/ModeStrip",
  component: ModeStrip,
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof ModeStrip>;

/** The P-4.1 state: every socket renders its sensible empty. */
export const EmptySockets: Story = {};

/** A dense strip, as the explorer will claim it (P-5). */
export const Claimed: Story = {
  args: {
    context: "Definitions",
    controls: (
      <>
        <button type="button">Validated</button>
        <button type="button">Proposal</button>
      </>
    ),
    status: <span>19 of 31 classes validated</span>,
  },
};
