// Generated by @canonical/summon-component:react v0.1.0

import { fireEvent, render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import Option from "./Option.js";

const baseOption = { value: "a", label: "Option A" };

describe("Choices Option", () => {
  it("renders the label and a native input of the given type", () => {
    render(
      <Option
        name="group"
        type="radio"
        option={baseOption}
        checked={false}
        disabled={false}
        onChange={() => {}}
      />,
    );
    expect(screen.getByText("Option A")).toBeInTheDocument();
    const input = screen.getByRole("radio");
    expect(input).toHaveAttribute("name", "group");
    expect(input).toHaveAttribute("value", "a");
  });

  it("reflects the checked state", () => {
    render(
      <Option
        name="group"
        type="checkbox"
        option={baseOption}
        checked={true}
        disabled={false}
        onChange={() => {}}
      />,
    );
    expect(screen.getByRole("checkbox")).toBeChecked();
  });

  it("calls onChange when toggled", () => {
    const onChange = vi.fn();
    render(
      <Option
        name="group"
        type="radio"
        option={baseOption}
        checked={false}
        disabled={false}
        onChange={onChange}
      />,
    );
    fireEvent.click(screen.getByRole("radio"));
    expect(onChange).toHaveBeenCalledOnce();
  });

  it("disables the input when disabled", () => {
    render(
      <Option
        name="group"
        type="radio"
        option={baseOption}
        checked={false}
        disabled={true}
        onChange={() => {}}
      />,
    );
    expect(screen.getByRole("radio")).toBeDisabled();
  });

  it("renders the description and wires it to the input", () => {
    render(
      <Option
        name="group"
        type="radio"
        option={{ ...baseOption, description: "Described choice" }}
        checked={false}
        disabled={false}
        onChange={() => {}}
      />,
    );
    const input = screen.getByRole("radio");
    const description = screen.getByText("Described choice");
    expect(description).toHaveAttribute(
      "id",
      input.getAttribute("aria-describedby"),
    );
  });

  it("hides the description when showDescription is false", () => {
    render(
      <Option
        name="group"
        type="radio"
        option={{ ...baseOption, description: "Described choice" }}
        checked={false}
        disabled={false}
        onChange={() => {}}
        showDescription={false}
      />,
    );
    expect(screen.queryByText("Described choice")).not.toBeInTheDocument();
  });
});
