// Generated by @canonical/summon-component:react v0.1.0

import type React from "react";
import { CheckboxInput } from "../../../../subcomponent/CheckboxInput/index.js";
import { Label } from "../../../../subcomponent/Field/index.js";
import { RadioInput } from "../../../../subcomponent/RadioInput/index.js";
import useOptionAriaProperties from "../../../../utils/hooks/useOptionAriaProperties.js";
import type { OptionProps } from "./types.js";

const componentCssClassName = "ds option";

/**
 * A single plain-label option within a `Choices` group: a styled native
 * radio/checkbox paired with its label. Controlled by the parent group via
 * `checked`/`onChange`.
 * @returns {React.ReactElement} - Rendered Option
 */
const Option = ({
  name,
  type,
  option,
  checked,
  disabled,
  onChange,
}: OptionProps): React.ReactElement => {
  const ariaProps = useOptionAriaProperties(name, option.value);
  return (
    <div
      className={[componentCssClassName, disabled && "disabled"]
        .filter(Boolean)
        .join(" ")}
    >
      {type === "radio" ? (
        <RadioInput
          name={name}
          value={option.value}
          disabled={disabled}
          checked={checked}
          onChange={onChange}
          {...ariaProps.input}
        />
      ) : (
        <CheckboxInput
          name={name}
          value={option.value}
          disabled={disabled}
          checked={checked}
          onChange={onChange}
          {...ariaProps.input}
        />
      )}
      {/* Option labels are plain choice text: the Label subcomponent's
          required/optional markers belong to field chrome, not to individual
          options, so `isOptional` suppresses the required marker. */}
      <Label name={name} isOptional className="p" {...ariaProps.label}>
        {option.label}
      </Label>
    </div>
  );
};

export default Option;
