// Generated by @canonical/summon-component:react v0.1.0

import type { Option as ChoiceOption } from "../../../../subcomponent/types.js";

export interface OptionProps {
  /** Field name shared by every option input in the group */
  name: string;
  /** Native input type backing the option (radios vs checkboxes) */
  type: "checkbox" | "radio";
  /** The option to render */
  option: ChoiceOption;
  /** Whether the option's `description` is shown (the group's stacked layout only) */
  showDescription?: boolean;
  /** Whether this option is currently selected */
  checked: boolean;
  /** Whether this option is disabled */
  disabled: boolean;
  /** Called when the option is toggled */
  onChange: () => void;
}
