name: "react-ds-app-lxd/chromatic"
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]
    paths:
      - configs/storybook/**
      - packages/ds-assets/**
      - packages/tokens/**
      - packages/styles/**
      - packages/utils/**
      - packages/runtime/ds-utils/**
      - packages/react/ds-global/**
      - packages/react/ds-app-lxd/**
      - "!packages/react/ds-global/**/*.stories.*"
      - "!**/*.test.*"
      - "!**/*.md"
      - "!**/*.mdx"
  push:
    branches:
      - main
    paths:
      - configs/storybook/**
      - packages/ds-assets/**
      - packages/tokens/**
      - packages/styles/**
      - packages/utils/**
      - packages/runtime/ds-utils/**
      - packages/react/ds-global/**
      - packages/react/ds-app-lxd/**
      - "!packages/react/ds-global/**/*.stories.*"
      - "!**/*.test.*"
      - "!**/*.md"
      - "!**/*.mdx"
jobs:
  test-compile:
    uses: ./.github/workflows/chromatic._template.yml
    secrets:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_TOKEN_CANONICAL_REACT_DS_APP_LXD }}
    with:
      working-directory: packages/react/ds-app-lxd
      externals: '[
        "configs/storybook/**",
        "packages/ds-assets/**",
        "packages/tokens/**/!(*.test.*|*.stories.*|*.md|*.mdx)",
        "packages/styles/**/!(*.test.*|*.stories.*|*.md|*.mdx)",
        "packages/utils/**/!(*.test.*|*.stories.*|*.md|*.mdx)",
        "packages/runtime/ds-utils/**/!(*.test.*|*.stories.*|*.md|*.mdx)",
        "packages/react/ds-global/**/!(*.test.*|*.stories.*|*.md|*.mdx)"
      ]'
