name: "svelte-ds-app-wpe/chromatic"
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]
    paths:
      - configs/storybook/**
      - packages/ds-assets/**
      - packages/tokens/**
      - packages/styles/**
      - packages/utils/**
      - packages/runtime/ds-utils/**
      # TODO: Uncomment once the wpe package consumes ds-global
      # - packages/svelte/ds-global/**
      # TODO: Uncomment once package consumes ds-app package
      # - packages/svelte/ds-app/**
      - packages/svelte/ds-app-wpe/**
      - "!**/*.test.*"
      - "!**/*.md"
      - "!**/*.mdx"
  push:
    branches:
      - main
    paths:
      - configs/storybook/**
      - packages/ds-assets/**
      - packages/tokens/**
      - packages/styles/**
      - packages/utils/**
      - packages/runtime/ds-utils/**
      # TODO: Uncomment once the wpe package consumes ds-global
      # - packages/svelte/ds-global/**
      # TODO: Uncomment once package consumes ds-app package
      # - packages/svelte/ds-app/**
      - packages/svelte/ds-app-wpe/**
      - "!**/*.test.*"
      - "!**/*.md"
      - "!**/*.mdx"
jobs:
  test-compile:
    uses: ./.github/workflows/chromatic._template.yml
    secrets:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_TOKEN_CANONICAL_SVELTE_DS_APP_WPE }}
    with:
      working-directory: packages/svelte/ds-app-wpe
      # TODO: Add packages/svelte/ds-global once package consumes ds-global package
      # TODO: Add packages/svelte/ds-app once package consumes ds-app package
      externals: '[
        "configs/storybook/**",
        "packages/ds-assets/**",
        "packages/tokens/**/!(*.test.*|*.stories.*|*.md|*.mdx)",
        "packages/styles/**/!(*.test.*|*.stories.*|*.md|*.mdx)",
        "packages/utils/**/!(*.test.*|*.stories.*|*.md|*.mdx)",
        "packages/runtime/ds-utils/**/!(*.test.*|*.stories.*|*.md|*.mdx)"
      ]'
