name: "lit-ds-prototype/chromatic"
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]
    paths:
      - configs/storybook/**
      - packages/ds-assets/**
      - packages/tokens/**
      - packages/styles/**
      - packages/utils/**
      - packages/runtime/ds-utils/**
      - packages/lit/ds-prototype/**
      - "!**/*.test.*"
      - "!**/*.md"
      - "!**/*.mdx"
  push:
    branches:
      - main
    paths:
      - configs/storybook/**
      - packages/ds-assets/**
      - packages/tokens/**
      - packages/styles/**
      - packages/utils/**
      - packages/runtime/ds-utils/**
      - packages/lit/ds-prototype/**
      - "!**/*.test.*"
      - "!**/*.md"
      - "!**/*.mdx"
jobs:
  test-compile:
    uses: ./.github/workflows/chromatic._template.yml
    secrets:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_TOKEN_CANONICAL_LIT_POC }}
    with:
      working-directory: packages/lit/ds-prototype
      externals: '[
        "configs/storybook/**",
        "packages/ds-assets/**",
        "packages/tokens/**/!(*.test.*|*.stories.*|*.md|*.mdx)",
        "packages/styles/**/!(*.test.*|*.stories.*|*.md|*.mdx)",
        "packages/utils/**/!(*.test.*|*.stories.*|*.md|*.mdx)",
        "packages/runtime/ds-utils/**/!(*.test.*|*.stories.*|*.md|*.mdx)"
        ]'
