// Generated by @canonical/summon-application:application/react v0.1.0

import { hydrateApp } from "./hydrateApp.js";
import "../styles/index.css";

const root = document.getElementById("root");
if (!root) {
  throw new Error('Root element "#root" not found');
}

// The whole hydration composition — reading `__INITIAL_DATA__`, seeding the
// Relay environment, building the router — lives in `hydrateApp` so the
// seam is testable; this module only anchors it to the real DOM once.
hydrateApp(root);
